
USE [DATA_SCIENCE]
GO

DECLARE @D1 DATETIME	=	CONCAT('2022-06-01',' 00:00:00.000')   
DECLARE @D2 DATETIME	=	CONCAT('2022-06-15',' 23:59:59.599')
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: PAGAMENTOS EFETIVIDADE															*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/ 
DROP TABLE IF EXISTS #PRE_PAGAMENTO
SELECT *
INTO #PRE_PAGAMENTO 
FROM (
		  SELECT DISTINCT
		  DATA	=	CONVERT(DATE,DTPAG_PAG)
		, CGCPF_DEV  
		, IDCON_CON
		,	CASE 	
				WHEN DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				THEN 'CBR'
				WHEN DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	THEN 'CCR'
				WHEN DESCR_BND IN ('REPCFI','EPCFI')									THEN 'EP'
																						ELSE 'VERIFICAR'
			END PRODUTO
		, CASE  
		    WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN -9999  AND 30	 THEN '0001 A 0030'
		    WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 31	  AND 60	 THEN '0031 A 0060'
		    WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 61	  AND 90	 THEN '0061 A 0090' 
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 91	  AND 120	 THEN '0091 A 0120' 
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 121	  AND 180	 THEN '0121 A 0180'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 181	  AND 240	 THEN '0181 A 0240'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 241    AND 360	 THEN '0241 A 0360'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 361    AND 720	 THEN '0361 A 0720'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 721    AND 1080	 THEN '0721 A 1080'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 1081   AND 1440	 THEN '1081 A 1440'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 1441   AND 1800	 THEN '1441 A 1800'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO)) BETWEEN 1801   AND 9999	 THEN '1801 A 9999'
			WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTACO_ACO))	> 9999					 THEN '>9999' 		
													
		    ELSE '' END ATRASO    
		, CONVERT(MONEY, VLPAG_PAG) AS VALOR_PAGO  
		, CONVERT(DATE,DTPAG_PAG)   AS DATA_PGTO
		, CONVERT(DATE,DTVEN_PAG)   AS DATA_VENC
		FROM	  [10.251.1.36].NECTAR.DBO.TB_CONTRATO     WITH(NOLOCK)   
		JOIN	  [10.251.1.36].NECTAR.DBO.TB_ACORDO       WITH(NOLOCK) ON IDCON_CON = IDCON_ACO  
		JOIN	  [10.251.1.36].NECTAR.DBO.TB_PAGAMENTO    WITH(NOLOCK) ON IDACO_ACO = IDACO_PAG  
		JOIN	  [10.251.1.36].NECTAR.DBO.TB_DEVEDOR      WITH(NOLOCK) ON IDDEV_CON = IDDEV_DEV  
		JOIN	  [10.251.1.36].NECTAR.DBO.TB_BANDEIRA	   WITH(NOLOCK) ON IDBND_BND = IDBND_CON
		LEFT JOIN [10.251.1.36].NECTAR.DBO.TB_PESSOAL	   WITH(NOLOCK) ON IDPES_ACO = IDPES_PES  
		WHERE IDEMP_CON = 17 
		AND DTPAG_PAG BETWEEN CONVERT(DATE,@D1) AND CONVERT(DATE,@D2)
		AND PAGAM_PAG = 1  
		AND IDPES_ACO != 0) X  
WHERE ATRASO <> '' 
AND DATA_PGTO IS NOT NULL