
SELECT DISTINCT * 
FROM TB_RESPONDE WITH (NOLOCK)
INNER JOIN TB_RESPOSTA WITH (NOLOCK)	 ON IDRES_RPE = IDRES_RES 
INNER JOIN TB_PERGUNTA WITH (NOLOCK)	 ON IDPER_RES = IDPER_PER  
INNER JOIN TB_QUESTIONARIO WITH (NOLOCK) ON IDQUE_PER = IDQUE_QUE  
WHERE IDQUE_QUE = 4
AND IDCON_RPE = 77884275 
AND DTCAD_RPE BETWEEN '2023-06-02 ' AND ' 2023-06-03'
