
/***********************************************************************	PAGAMENTOS		***********************************************************************/

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: ANALITICO DE PAGAMENTOS														    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/	                                                                                                       
DROP TABLE IF EXISTS #VENC
SELECT DISTINCT
	IDACO_ACO,
	CONVERT(DATE,DTVEN_PAG) DATA_VENC,
	CONVERT(DATE,DTACO_ACO) DATA_ACO,
	(SELECT TOP 1 MIN(CONVERT(DATE,DTVEN_PAG)) FROM [10.251.1.36].NECTAR.DBO.[TB_PAGAMENTO] C WHERE C.IDACO_PAG = PG.IDACO_PAG) PRI_VENC,
	CONVERT(DATE,DTPAG_PAG) DATA_PAG,
	CONVERT(DATE,DTCAN_ACO) DATA_CAN,
CASE 
	WHEN STACO_ACO = 0 THEN 'ATIVO' ELSE 'CANCELADO'
END
	STATUS_ACORDO,
CASE
	WHEN STPAG_PAG = 0 THEN 'ABERTO' ELSE 'PAGO'
END
	STATUS_PAGTO,
CASE 
	WHEN CONVERT(DATE,DTVEN_PAG) > CONVERT(DATE, GETDATE()) THEN 'A VENCER'
	WHEN CONVERT(DATE,DTVEN_PAG) < CONVERT(DATE, GETDATE()) THEN 'VENCIDO'
	WHEN CONVERT(DATE,DTVEN_PAG) = CONVERT(DATE, GETDATE()) THEN 'VENCENDO'
END 
	STATUS_VENCIMENTO,
CASE
	WHEN IDPES_ACO = 0						THEN 'INDIRETO'
	WHEN SETOR     IN ('DIGITAL')			THEN 'DIGITAL' 
	WHEN USUAR_PES IN ('WILSONR','WHATSR')  THEN 'WILSON'
	WHEN USUAR_PES IN ('FACAACORDO')		THEN 'PORTAL' ELSE 'OPERAÇÃO'
END
	ORIGEM,
	DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTCAD_ACO)) AGING,
	CONVERT(MONEY,VLVEN_PAG)					[VALOR_ACORDO],
	CONVERT(MONEY,VLPAG_PAG)					[VALOR_PAGTO],
	CONVERT(MONEY,VLMAC_CON)					[CONTABIL],
	DESCR_BND	=	 
	CASE 	WHEN DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				THEN 'CBR'
			WHEN DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	THEN 'CCR'
			WHEN DESCR_BND IN ('REPCFI','EPCFI')									THEN 'EP'
																					ELSE 'VERIFICAR'
	END,						
	CGCPF_DEV AS CPFCNPJ,
	CONTR_CON AS CONTRATO,
	PAGAM_PAG PARCELA,
	(SELECT TOP 1 MAX(PAGAM_PAG) FROM [10.251.1.36].NECTAR.DBO.[TB_PAGAMENTO] P WHERE P.IDACO_PAG = PG.IDACO_PAG) PLANO,
	CASE WHEN CONVERT(DATE,DTCAN_ACO) < CONVERT(DATE,DTCAD_ACO) THEN 1 ELSE 0 END AUX_ACO
INTO
	#VENC
FROM	   [10.251.1.36].NECTAR.DBO.[TB_ACORDO]			WITH(NOLOCK)
INNER JOIN [10.251.1.36].[nectar].[dbo].[TB_ACORDOTIT]	WITH(NOLOCK) ON IDACO_ATI = IDACO_ACO
INNER JOIN [10.251.1.36].[nectar].[dbo].[TB_PARCELA]	WITH(NOLOCK) ON IDPAR_PAR = IDPAR_ACO
INNER JOIN [10.251.1.36].NECTAR.DBO.[TB_CONTRATO]		WITH(NOLOCK) ON IDCON_CON = IDCON_ACO 
INNER JOIN [10.251.1.36].NECTAR.DBO.[TB_DEVEDOR]		WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
INNER JOIN [10.251.1.36].NECTAR.DBO.TB_BANDEIRA			WITH(NOLOCK) ON IDBND_BND = IDBND_CON
INNER JOIN [10.251.1.36].NECTAR.DBO.[TB_PAGAMENTO] PG	WITH(NOLOCK) ON IDACO_PAG = IDACO_ACO
INNER JOIN [10.251.1.36].NECTAR.DBO.[TB_PESSOAL] U		WITH(NOLOCK) ON IDPES_PES = IDPES_ACO
INNER JOIN [10.251.1.36].NECTAR.DBO.[TB_CARTEIRA] CR	WITH(NOLOCK) ON IDCAR_CAR = IDCAR_CON
LEFT JOIN  [DATA_SCIENCE].[DBO].[OPERADORES]			WITH(NOLOCK) ON IDPES     = IDPES_ACO
WHERE CONVERT(DATE,DTVEN_PAG) BETWEEN '2022-06-01' and '2022-06-27' -- OU DTVEN_PAG / DTCAD_ACO É PRA PRODUÇÃO DE ACORDO
AND IDEMP_CON = 17
GROUP BY
	IDACO_ACO,
	CONVERT(DATE,DTVEN_PAG),
	CONVERT(DATE,DTACO_ACO),
	CONVERT(DATE,DTCAD_ACO),
	CONVERT(DATE,DTPAG_PAG),
	CONVERT(DATE,DTCAN_ACO),
	CONVERT(MONEY,VLVEN_PAG),
	CONVERT(MONEY,VLPAG_PAG),
	CONVERT(MONEY,VLMAC_CON),
	CASE 
		WHEN DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				THEN 'CBR'
		WHEN DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	THEN 'CCR'
		WHEN DESCR_BND IN ('REPCFI','EPCFI')									THEN 'EP'
																				ELSE 'VERIFICAR'
	END,
	CGCPF_DEV,
	CONTR_CON,
	IDACO_PAG,
	PAGAM_PAG,
CASE
	WHEN IDPES_ACO = 0						THEN 'INDIRETO'
	WHEN SETOR     IN ('DIGITAL')			THEN 'DIGITAL' 
	WHEN USUAR_PES IN ('WILSONR','WHATSR')  THEN 'WILSON'
	WHEN USUAR_PES IN ('FACAACORDO')		THEN 'PORTAL' ELSE 'OPERAÇÃO'
END,
CASE 
	WHEN CONVERT(DATE,DTVEN_PAG) > CONVERT(DATE, GETDATE()) THEN 'A VENCER'
	WHEN CONVERT(DATE,DTVEN_PAG) < CONVERT(DATE, GETDATE()) THEN 'VENCIDO'
	WHEN CONVERT(DATE,DTVEN_PAG) = CONVERT(DATE, GETDATE()) THEN 'VENCENDO'
END,
CASE 
	WHEN STACO_ACO = 0 THEN 'ATIVO' ELSE 'CANCELADO'
END,
CASE
	WHEN STPAG_PAG = 0 THEN 'ABERTO' ELSE 'PAGO'
END

/***************************************************************************************************/
DROP TABLE IF EXISTS #FINAL
SELECT 
	*,
CASE 
	WHEN CONVERT(DATE,DATA_CAN) < CONVERT(DATE,PRI_VENC) THEN 1 ELSE 0 END AUX_PRI_VENC,
CASE 
	WHEN CONVERT(DATE,DATA_CAN) < CONVERT(DATE,DATA_VENC) THEN 1 ELSE 0 END AUX_VENC
INTO
	#FINAL
FROM #VENC
/***************************************************************************************************/
DROP TABLE IF EXISTS #VENCIMENTO
SELECT
		CASE
			WHEN AGING BETWEEN	-9999  AND 30	 THEN '0001 A 0030'
			WHEN AGING BETWEEN	31	   AND 60	 THEN '0031 A 0060'
			WHEN AGING BETWEEN	61	   AND 90	 THEN '0061 A 0090'	
			WHEN AGING BETWEEN	91	   AND 120	 THEN '0091 A 0120'	
			WHEN AGING BETWEEN	121	   AND 180	 THEN '0121 A 0180'	
			WHEN AGING BETWEEN	181	   AND 240	 THEN '0181 A 0240'	
			WHEN AGING BETWEEN	241    AND 360	 THEN '0241 A 0360'	
			WHEN AGING BETWEEN	361    AND 720	 THEN '0361 A 0720'	
			WHEN AGING BETWEEN	721    AND 1080	 THEN '0721 A 1080'	
			WHEN AGING BETWEEN	1081   AND 1440	 THEN '1081 A 1440'	
			WHEN AGING BETWEEN	1441   AND 1800	 THEN '1441 A 1800'	
			WHEN AGING BETWEEN	1801   AND 9999	 THEN '1801 A 9999'	
			WHEN AGING > 9999					 THEN '>9999' 		
												 ELSE 'VERIFICAR'
		END AGING,
DESCR_BND,
PLANO,
CASE 
	WHEN PLANO = 1 THEN 'A VISTA' ELSE 'PARCELADO' 
END 
	TIPO_PLANO,
CASE 
	WHEN PLANO	 = 1 THEN 'A VISTA'
	WHEN PARCELA = 1 THEN '1ª PARCELA'
	WHEN PARCELA > 1 THEN 'COLCHÃO'
END
	TIPO_PARCELA,	
	ORIGEM,
	STATUS_VENCIMENTO,
CASE
	WHEN AUX_ACO = 1	  THEN 'ACOR'
	WHEN AUX_PRI_VENC = 1 THEN 'PRI_VENC' 
	WHEN AUX_VENC = 1	  THEN 'VENC'ELSE 'ATIVO'
END
	STATUS_CANCELAMENTO,
	DATA_ACO,
	DATA_VENC,
	STATUS_ACORDO,
	STATUS_PAGTO,
	COUNT(CPFCNPJ)																					[ACORDO #],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCIDO'  THEN 1 END)										[VENCIDO #],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCENDO' THEN 1 END)										[VENCENDO #],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'A VENCER' THEN 1 END)										[A VENCER #],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCIDO' AND STATUS_PAGTO = 'PAGO' THEN 1 END)				[RECEBIMENTO #],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCIDO' AND STATUS_PAGTO = 'ABERTO' THEN 1 END)				[QUEBRA #],
	SUM(VALOR_ACORDO)																				[ACORDO $],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCIDO'  THEN VALOR_ACORDO END)								[VENCIDO $],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCENDO' THEN VALOR_ACORDO END)								[VENCENDO $],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'A VENCER' THEN VALOR_ACORDO END)								[A VENCER $],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCIDO' AND STATUS_PAGTO = 'PAGO' THEN VALOR_PAGTO END)		[RECEBIMENTO $],
	SUM(CASE WHEN STATUS_VENCIMENTO = 'VENCIDO' AND STATUS_PAGTO = 'ABERTO' THEN VALOR_ACORDO END)	[QUEBRA $],
CASE
	WHEN AUX_ACO = 1	  THEN 'NÃO'
	WHEN AUX_PRI_VENC = 1 THEN 'SIM' 
	WHEN AUX_VENC = 1	  THEN 'SIM'ELSE 'NÃO'
END 
	EXPURGAR
INTO #VENCIMENTO
FROM #FINAL V
GROUP BY 
	DATA_ACO,
	DATA_VENC,
	PLANO,
	STATUS_ACORDO,
	STATUS_PAGTO,
	CASE WHEN PLANO = 1 THEN 'A VISTA' ELSE 'PARCELADO' END,
	CASE
			WHEN AGING BETWEEN	-9999  AND 30	 THEN '0001 A 0030'
			WHEN AGING BETWEEN	31	   AND 60	 THEN '0031 A 0060'
			WHEN AGING BETWEEN	61	   AND 90	 THEN '0061 A 0090'	
			WHEN AGING BETWEEN	91	   AND 120	 THEN '0091 A 0120'	
			WHEN AGING BETWEEN	121	   AND 180	 THEN '0121 A 0180'	
			WHEN AGING BETWEEN	181	   AND 240	 THEN '0181 A 0240'	
			WHEN AGING BETWEEN	241    AND 360	 THEN '0241 A 0360'	
			WHEN AGING BETWEEN	361    AND 720	 THEN '0361 A 0720'	
			WHEN AGING BETWEEN	721    AND 1080	 THEN '0721 A 1080'	
			WHEN AGING BETWEEN	1081   AND 1440	 THEN '1081 A 1440'	
			WHEN AGING BETWEEN	1441   AND 1800	 THEN '1441 A 1800'	
			WHEN AGING BETWEEN	1801   AND 9999	 THEN '1801 A 9999'	
			WHEN AGING > 9999					 THEN '>9999' 		
												 ELSE 'VERIFICAR'
		END,
	DATA_VENC,
	ORIGEM,
CASE 
	WHEN PLANO	 = 1 THEN 'A VISTA'
	WHEN PARCELA = 1 THEN '1ª PARCELA'
	WHEN PARCELA > 1 THEN 'COLCHÃO'
END,
DESCR_BND,
	STATUS_VENCIMENTO,
CASE
	WHEN AUX_ACO = 1	  THEN 'ACOR'
	WHEN AUX_PRI_VENC = 1 THEN 'PRI_VENC' 
	WHEN AUX_VENC = 1	  THEN 'VENC'ELSE 'ATIVO'
END,
CASE
	WHEN AUX_ACO = 1	  THEN 'NÃO'
	WHEN AUX_PRI_VENC = 1 THEN 'SIM' 
	WHEN AUX_VENC = 1	  THEN 'SIM'ELSE 'NÃO'
END 
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: ANALITICO DE PAGAMENTOS														    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
TRUNCATE TABLE DATA_SCIENCE.DBO.TEMP_ANALITICO_PAGAMENTOS_RENNER
INSERT INTO DATA_SCIENCE.DBO.TEMP_ANALITICO_PAGAMENTOS_RENNER
SELECT * FROM #VENCIMENTO