	
	DECLARE @D1		      VARCHAR(50)	=   CONCAT(CONVERT(DATE,GETDATE()-1), ' ' + '00:00:01.000')
	DECLARE @Ds_Diretorio VARCHAR(255)	=  '\\10.251.0.13\NectarServices\Nectar\Pra_Valer\Backup\Carga\Carga_Bat_Pagt'
    DECLARE @Query VARCHAR(8000)		=  'dir/ -C /4 /N "' + @Ds_Diretorio + '"'


	DECLARE @vArqDump table (
	DiretorioAqr varchar(1000) not null
	)


    DECLARE @ArqDiretorio table (
        LINHA INT IDENTITY(1, 1),
        RESULTADO VARCHAR(MAX)
    )

    DECLARE @Etl_Tabela table (
        LINHA INT IDENTITY(1,1),
        DT_CRIACAO DATE,
        QT_TAMANHO INT,
        NOME_ARQ VARCHAR(255),
		DIRETORIO VARCHAR(MAX)
    )
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: INSERE O COMANDO CMD NA VARIÁVEL @RETORNO											*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/ 
INSERT INTO @ArqDiretorio
EXEC MASTER.DBO.XP_CMDSHELL @COMMAND_STRING = @QUERY
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: INSERE AS INFOR DO ARQUIVOS LIDOS NA VARIÁVEL @TABELA FINAL						*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
INSERT INTO @ETL_TABELA(DT_CRIACAO, QT_TAMANHO, NOME_ARQ, DIRETORIO)
SELECT 
DT_CRIACAO	=	CONVERT(DATE,LEFT(RESULTADO, 17), 103) ,
TAM_ARQ		=  (SUBSTRING(LTRIM(RESULTADO), 18, 19))   ,
NOM_ARQ		=	SUBSTRING(RESULTADO, CHARINDEX(LTRIM(SUBSTRING(LTRIM(RESULTADO), 18, 19)), RESULTADO, 18) + LEN(LTRIM(SUBSTRING(LTRIM(RESULTADO), 18, 19))) + 1, LEN(RESULTADO)) ,
DIRETORIO	=	@DS_DIRETORIO + '\' + SUBSTRING(RESULTADO, CHARINDEX(LTRIM(SUBSTRING(LTRIM(RESULTADO), 18, 19)), RESULTADO, 18) + LEN(LTRIM(SUBSTRING(LTRIM(RESULTADO), 18, 19))) + 1, LEN(RESULTADO))
FROM @ARQDIRETORIO
WHERE RESULTADO IS NOT NULL
AND LINHA >= 6
AND LINHA < (SELECT MAX(LINHA) FROM @ARQDIRETORIO) - 2
AND RESULTADO NOT LIKE '%<DIR>%'
ORDER BY 3 ASC

INSERT INTO @vArqDump
SELECT DIRETORIO
FROM @Etl_Tabela X
WHERE DT_CRIACAO = (SELECT CONVERT(DATE,@D1))
AND SUBSTRING(TRIM(NOME_ARQ),16,2) = 'CA'



DROP TABLE IF EXISTS ##CARGA
CREATE TABLE		 ##CARGA (
	CPF						 VARCHAR(1000) NULL
,	RG						 VARCHAR(1000) NULL
,	NOME					 VARCHAR(1000) NULL
,	DATA_NASC				 VARCHAR(1000) NULL
,	SEXO					 VARCHAR(1000) NULL
,	ENDERECO				 VARCHAR(1000) NULL
,	ENDERECO_NUMERO			 VARCHAR(1000) NULL
,	ENDERECO_COMPLEMENTO	 VARCHAR(1000) NULL
,	BAIRRO					 VARCHAR(1000) NULL
,	CIDADE					 VARCHAR(1000) NULL
,	ESTADO					 VARCHAR(1000) NULL
,	CEP						 VARCHAR(1000) NULL
,	TELEFONE_DDD			 VARCHAR(1000) NULL
,	TELEFONE				 VARCHAR(1000) NULL
,	CELULAR_DDD				 VARCHAR(1000) NULL
,	CELULAR					 VARCHAR(1000) NULL
,	TELEFONE_COM_DDD		 VARCHAR(1000) NULL
,	TELEFONE_COM			 VARCHAR(1000) NULL
,	EMAIL					 VARCHAR(1000) NULL
,	FIA_CPF					 VARCHAR(1000) NULL
,	FIA_RG					 VARCHAR(1000) NULL
,	FIA_NOME				 VARCHAR(1000) NULL
,	FIA_DATA_NASC			 VARCHAR(1000) NULL
,	FIA_SEXO				 VARCHAR(1000) NULL
,	FIA_ENDERECO			 VARCHAR(1000) NULL
,	FIA_ENDERECO_NUMERO		 VARCHAR(1000) NULL
,	FIA_ENDERECO_COMPLEMENTO VARCHAR(1000) NULL
,	FIA_BAIRRO				 VARCHAR(1000) NULL
,	FIA_CIDADE				 VARCHAR(1000) NULL
,	FIA_ESTADO				 VARCHAR(1000) NULL
,	FIA_CEP					 VARCHAR(1000) NULL
,	FIA_TELEFONE_DDD		 VARCHAR(1000) NULL
,	FIA_TELEFONE			 VARCHAR(1000) NULL
,	FIA_CELULAR_DDD			 VARCHAR(1000) NULL
,	FIA_CELULAR				 VARCHAR(1000) NULL
,	FIA_TELEFONE_COM_DDD	 VARCHAR(1000) NULL
,	FIA_TELEFONE_COM		 VARCHAR(1000) NULL
,	FIA_EMAIL				 VARCHAR(1000) NULL
,	PAI						 VARCHAR(1000) NULL
,	PAI_TELEFONE_DDD		 VARCHAR(1000) NULL
,	PAI_TELEFONE			 VARCHAR(1000) NULL
,	PAI_CELULAR_DDD			 VARCHAR(1000) NULL
,	PAI_CELULAR				 VARCHAR(1000) NULL
,	PAI_TELEFONE_COM_DDD	 VARCHAR(1000) NULL
,	PAI_TELEFONE_COM		 VARCHAR(1000) NULL
,	MAE						 VARCHAR(1000) NULL
,	MAE_TELEFONE_DDD		 VARCHAR(1000) NULL
,	MAE_TELEFONE			 VARCHAR(1000) NULL
,	MAE_CELULAR_DDD			 VARCHAR(1000) NULL
,	MAE_CELULAR				 VARCHAR(1000) NULL
,	MAE_TELEFONE_COM_DDD	 VARCHAR(1000) NULL
,	MAE_TELEFONE_COM		 VARCHAR(1000) NULL
,	IES_GRUPO				 VARCHAR(1000) NULL
,	IES						 VARCHAR(1000) NULL
,	TIPO_CURSO				 VARCHAR(1000) NULL
,	CURSO					 VARCHAR(1000) NULL
,	VECTO					 VARCHAR(1000) NULL
,	ATRASO					 VARCHAR(1000) NULL
,	VALOR_EM_ATRASO			 VARCHAR(1000) NULL
,	FUNDO					 VARCHAR(1000) NULL );
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: LAYOUT FINAL UNFICANDO AS 2 E JÁ DEIXA COMO LAYOUT PARA CÓDIGO ABAIXO			    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

DECLARE @tableName VARCHAR(1000)      = '##CARGA'
DECLARE @filePath  VARCHAR(1000)      =  (SELECT * FROM @vArqDump)
DECLARE @ParametrosBulk varchar(1000) = 'WITH (FIRSTROW = 2 , FIELDTERMINATOR = '';'', ROWTERMINATOR = ''\n'')'


DECLARE @sql VARCHAR(MAX)
SET @sql = 'BULK INSERT ' + @tableName + ' FROM ''' + @filePath + '''' + ' ' + @ParametrosBulk 

print @sql

EXEC (@sql)

SELECT *
FROM ##CARGA
