


CREATE FUNCTION dbo.fn_RemoveEspaco(@TEXTO AS VARCHAR(MAX))
RETURNS VARCHAR(MAX) AS
BEGIN;

	IF @TEXTO IS NULL RETURN NULL
	
	DECLARE @NOVOTEXTO VARCHAR(MAX)

	SET @NOVOTEXTO =  @TEXTO
	SET @NOVOTEXTO =  LTRIM(@NOVOTEXTO)

	WHILE (CHARINDEX('  ',@NOVOTEXTO)) > 0
	BEGIN;
		SET @NOVOTEXTO = REPLACE(@NOVOTEXTO, '  ', ' ');
	END;

	RETURN @NOVOTEXTO

END;