

DECLARE @D1 VARCHAR(20) =	'2022-04-01 00:00:00'
DECLARE @D2 VARCHAR(20) =	'2022-04-02 23:59:59'
DECLARE @TSQL VARCHAR(8000)
DECLARE @IP VARCHAR(13) = '[10.251.1.36]'

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: IMPORTA BASE DA CLIENTE DEPOIS DO ETL DA TABELA									*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
DROP TABLE IF EXISTS #BASE
SELECT *
INTO #BASE
FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0',
'Excel 12.0 Xml;HDR=YES;Database=\\polaris\NectarServices\Administrativo\Mailing_AD\Base_Mailing_20230731.xlsx',
'SELECT * FROM [Planilha1$]'); --> nome da sheet do seu excel
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :COLETA AS INFORMAÇÕES DA ULTIMA SAVE POR CONTRATO							    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
SELECT 
 A.CHAVE_CYBER
,A.SALDO_CONTABIL
,A.DT_INFO
INTO #SAVE
FROM (
SELECT 
 CHAVE_CYBER
,SALDO_CONTABIL
,DT_INFO
,ROW_NUMBER () OVER(PARTITION BY CHAVE_CYBER ORDER BY DT_INFO DESC) RW  
FROM REPORTS.DBO.TB_SAVE_RIACHUELO) A 
WHERE RW = 1
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :ANALITICO DE PRODUTIVIDADE SEM ACORDO										    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
IF OBJECT_ID ('tempdb.dbo.##PRO') IS NOT NULL DROP TABLE ##PRO
SELECT  @TSQL = 
'SELECT * INTO ##PRO FROM 
OPENQUERY('+@IP+',
''SELECT
 DTAND_AND
,IDAND_AND
,IMAPS_OCO
,IDCON_CON
,DESCR_OCO
,IDPES_PES
,CONTR_CON
,USUAR_PES
,IDOCO_AND
,CGCPF_DEV
,DTATR_CON
,DESCR_DOC
,IDEMP_CON
,ORIGE_AND
,VLMAC_CON
FROM	   NECTAR.DBO.TB_ANDAMENTO 	WITH(NOLOCK)
INNER JOIN NECTAR.DBO.TB_CONTRATO 	WITH(NOLOCK) ON IDCON_CON = IDCON_AND
INNER JOIN NECTAR.DBO.TB_DEVEDOR	WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
INNER JOIN NECTAR.DBO.TB_OCORRENCIA	WITH(NOLOCK) ON IDOCO_OCO = IDOCO_AND 
INNER JOIN NECTAR.DBO.TB_PESSOAL	WITH(NOLOCK) ON IDPES_AND = IDPES_PES
LEFT JOIN  (SELECT DISTINCT
			 IDCON_TRA
			,IDDOC_TRA
			,TITUL_TRA
			,DTFAT_TRA
			FROM	   [NECTAR].[DBO].TB_TRANSACAO WITH(NOLOCK)
			INNER JOIN [NECTAR].[DBO].TB_CONTRATO  WITH(NOLOCK) ON IDCON_TRA = IDCON_CON AND IDEMP_CON IN (3,5,6)
			UNION ALL
			SELECT DISTINCT
			 IDCON_BAI
			,IDDOC_BAI
			,TITUL_BAI
			,DTFAT_BAI
			FROM	   [NECTAR].[DBO].TB_BAIXA	 WITH(NOLOCK)
			INNER JOIN [NECTAR].[DBO].TB_CONTRATO  WITH(NOLOCK) ON IDCON_BAI = IDCON_CON AND IDEMP_CON IN (3,5,6)) T ON T.IDCON_TRA = IDCON_CON
LEFT JOIN  [NECTAR].[DBO].[TB_DOCUMENTO] WITH(NOLOCK) ON IDDOC_DOC = IDDOC_TRA  
WHERE IDEMP_CON IN (3,5,6) 
AND DTAND_AND BETWEEN '''''+@D1+''''' AND ''''' +@D2+ ''''''')'
EXEC(@TSQL)
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :ETL ANALITICO DE PRODUTIVIDADE SEM ACORDO										*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
IF OBJECT_ID('TEMPDB..#PROD') IS NOT NULL DROP TABLE #PROD
SELECT 
 CONVERT(DATE,DTAND_AND) DTAND_AND
,CONVERT(VARCHAR(8),DTAND_AND,108) HRAND_AND
,IDAND_AND
,IMAPS_OCO
,IDPES_PES
,USUAR_PES
,CONTR_CON
,IDCON_CON
,IDOCO_AND
,CGCPF_DEV
,IDEMP_CON
,DESCR_OCO
,DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTAND_AND)) AGING
,CONVERT(MONEY,MAX(VLMAC_CON)) VLMAC_CON 
,MIN(DESCR_DOC) DESCR_DOC
INTO #PROD
FROM ##PRO
WHERE IMAPS_OCO NOT IN ('PROMESSA','ACORDO')
GROUP BY
 CONVERT(DATE,DTAND_AND)
,CONVERT(VARCHAR(8),DTAND_AND,108)
,IDAND_AND
,IMAPS_OCO
,IDCON_CON
,CGCPF_DEV
,IDEMP_CON
,DESCR_OCO
,IDOCO_AND
,IDPES_PES
,USUAR_PES
,CONTR_CON
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :ANALITICO DE ACORDO																*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
SELECT @TSQL =   
'IF OBJECT_ID(''TEMPDB..##MMM'') IS NOT NULL DROP TABLE ##MMM
SELECT * INTO ##MMM FROM  
OPENQUERY('+@IP+',  
''SELECT   
 DTVEN_PAG  
,DTACO_ACO  
,DTPAG_PAG  
,IDPES_ACO  
,USUAR_PES  
,DTATR_CON  
,VLVEN_PAG  
,VLPAG_PAG  
,VLMAC_CON  
,DESCR_DOC  
,STACO_ACO   
,NOME_PES  
,PLANO_CON      
,IDEMP_EMP   
,CGCPF_DEV  
,CONTR_CON  
,IDCON_CON
,DTCAN_ACO
,DTCAD_ACO
,PAGAM_PAG PARCELA  
FROM       [NECTAR].[DBO].[TB_ACORDO]		WITH(NOLOCK)  
INNER JOIN [NECTAR].[DBO].[TB_ACORDOTIT]	WITH(NOLOCK) ON IDACO_ATI = IDACO_ACO  
INNER JOIN [NECTAR].[DBO].[TB_PARCELA]		WITH(NOLOCK) ON IDPAR_PAR = IDPAR_ACO  
INNER JOIN [NECTAR].[DBO].[TB_CONTRATO]		WITH(NOLOCK) ON IDCON_CON = IDCON_ACO   
INNER JOIN [NECTAR].[DBO].[TB_DEVEDOR]		WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON  
INNER JOIN [NECTAR].[DBO].[TB_PAGAMENTO]	WITH(NOLOCK) ON IDACO_PAG = IDACO_ACO  
INNER JOIN [NECTAR].[DBO].[TB_PESSOAL]		WITH(NOLOCK) ON IDPES_PES = IDPES_ACO  
INNER JOIN [NECTAR].[DBO].[TB_CARTEIRA]		WITH(NOLOCK) ON IDCAR_CAR = IDCAR_CON  
INNER JOIN [NECTAR].[DBO].[TB_EMPRESA]		WITH(NOLOCK) ON IDEMP_EMP = IDEMP_CON  
LEFT JOIN  (SELECT DISTINCT
			 IDCON_TRA
			,IDDOC_TRA
			,TITUL_TRA
			,DTFAT_TRA
			FROM	   [NECTAR].[DBO].TB_TRANSACAO WITH(NOLOCK)
			INNER JOIN [NECTAR].[DBO].TB_CONTRATO  WITH(NOLOCK) ON IDCON_TRA = IDCON_CON AND IDEMP_CON IN (3,5,6)
			UNION ALL
			SELECT DISTINCT
			 IDCON_BAI
			,IDDOC_BAI
			,TITUL_BAI
			,DTFAT_BAI
			FROM	   [NECTAR].[DBO].TB_BAIXA	 WITH(NOLOCK)
			INNER JOIN [NECTAR].[DBO].TB_CONTRATO  WITH(NOLOCK) ON IDCON_BAI = IDCON_CON AND IDEMP_CON IN (3,5,6)) T ON T.IDCON_TRA = IDCON_CON
LEFT JOIN  [NECTAR].[DBO].[TB_DOCUMENTO] WITH(NOLOCK) ON IDDOC_DOC = IDDOC_TRA   
WHERE DTACO_ACO BETWEEN '''''+ @D1 +''''' AND '''''+ @D2 +'''''  
AND IDEMP_CON IN (3,5,6)''
) A'  
EXEC (@TSQL)    
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :ETL E CONSOLIDAÇÃO DO ANALITICO DE ACORDO COM PRODUÇÃO							*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
IF OBJECT_ID('TEMPDB..#MMMM') IS NOT NULL DROP TABLE #MMMM 
SELECT DISTINCT    
 CONVERT(DATE,DTACO_ACO) DTACO_ACO  
,CONVERT(DATE,DTPAG_PAG) DTPAG_PAG  
,IDEMP_EMP  
,IDPES_ACO  
,USUAR_PES  
,DATEDIFF(DAY,CONVERT(DATE,MIN(DTATR_CON)),CONVERT(DATE,DTACO_ACO)) AGING  
,CONVERT(MONEY,MAX(VLMAC_CON)) VLMAC_CON 
,CONVERT(MONEY,VLVEN_PAG) VLVEN_PAG
,CONVERT(MONEY,VLPAG_PAG) VLPAG_PAG
,CGCPF_DEV  
,CONTR_CON  
,IDCON_CON
,MIN(DESCR_DOC) DESCR_DOC
,67 IDOCO_OCO
,CASE WHEN DTPAG_PAG IS NOT NULL THEN 1  ELSE 0 END PAGTO
INTO #FINAL 
FROM ##MMM  
WHERE LEFT(DTCAD_ACO,10) <> (CASE WHEN DTCAN_ACO IS NULL THEN '2019-01-01' ELSE LEFT(DTCAN_ACO,10) END)
GROUP BY    
 CONVERT(DATE,DTACO_ACO)  
,CONVERT(DATE,DTPAG_PAG)  
,IDPES_ACO  
,USUAR_PES  
,CONVERT(MONEY,VLVEN_PAG)
,CONVERT(MONEY,VLPAG_PAG)
,CGCPF_DEV  
,CONTR_CON 
,IDEMP_EMP
,IDCON_CON
,CASE WHEN DTPAG_PAG IS NOT NULL THEN 1  ELSE 0 END

UNION ALL

SELECT 
 CONVERT(DATE,DTAND_AND) DTACO_ACO
,NULL					 DTPAG_PAG
,IDEMP_CON				 IDEMP_EMP 
,IDPES_PES				 IDPES_ACO 
,USUAR_PES				 USUAR_PES 
,AGING					 AGING 
,VLMAC_CON				 VLMAC_CON 
,NULL					 VLVEN_PAG
,NULL					 VLPAG_PAG
,CGCPF_DEV				 CGCPF_DEV
,CONTR_CON				 CONTR_CON
,IDCON_CON				 IDCON_CON
,MIN(DESCR_DOC) DESCR_DOC  
,IDOCO_AND
,0 PAGTO
FROM #PROD
GROUP BY
 CONVERT(DATE,DTAND_AND)
,IDEMP_CON  
,IDPES_PES 
,USUAR_PES
,CGCPF_DEV  
,CONTR_CON  
,IDCON_CON
,AGING
,IDOCO_AND
,VLMAC_CON
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :ANALITICO PRODUÇÃO CRUZANDO COM A BASE DA CAMPANHA								*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
SELECT 
 A.*
,TABULADO ALO
,CPC	  CPC	 
,CPC_P	  CPC_P	 
,ACORDO	  ACORDO	 
,CONTABIL	=	CASE WHEN ACORDO = 1 THEN CONVERT(MONEY,SALDO_CONTABIL) END 
INTO #ANALITICO
FROM #FINAL A
LEFT JOIN Reports..AUX_DEXPARA_ATMA ON IDOCO_OCO = IDOCO_DXP
	INNER JOIN #BASE ON CPF = CGCPF_DEV
		LEFT JOIN #SAVE ON CONTR_CON = CHAVE_CYBER
WHERE SISTEMA = 0 
AND CONVERT(DATE,DTACO_ACO) BETWEEN @D1 AND @D2
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :LAYOUT FINAL ABERTO POR DIA														*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
SELECT 
 DTACO_ACO DATA
,COUNT(CGCPF_DEV) DISCADAS
,COUNT(DISTINCT CGCPF_DEV) PENETRADO
,SUM(ALO) ALO
,SUM(CPC	 ) CPC	 
,SUM(CPC_P	 ) CPC_P	 
,SUM(ACORDO	 ) ACORDO	 
,SUM(CONTABIL) CONTABIL 
FROM #ANALITICO
WHERE CONVERT(DATE,DTACO_ACO) BETWEEN @D1 AND @D2
GROUP BY DTACO_ACO
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :LAYOUT FINAL VISÃO UNIQUE MES													*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
SELECT 
 COUNT(CGCPF_DEV) DISCADAS
,COUNT(DISTINCT CGCPF_DEV) PENETRADO
,COUNT(DISTINCT CASE WHEN ALO = 1 THEN CGCPF_DEV END)	ALO
,COUNT(DISTINCT CASE WHEN CPC		= 1 THEN CGCPF_DEV END)	CPC	 
,COUNT(DISTINCT CASE WHEN CPC_P	= 1 THEN CGCPF_DEV END)	CPC_P	 
,COUNT(DISTINCT CASE WHEN ACORDO	= 1 THEN CGCPF_DEV END)	ACORDO	 
,COUNT(DISTINCT CASE WHEN PAGTO = 1 THEN CGCPF_DEV END) PAGTO
,SUM(DISTINCT CASE WHEN ACORDO = 1 THEN  CONVERT(MONEY,CONTABIL) END) ACO_CONTABIL
,SUM(DISTINCT CASE WHEN PAGTO = 1 THEN   CONVERT(MONEY,CONTABIL) END)  PGT_CONTABIL 
FROM REPORTS..TB_DS_ANALITICO_PROD_CAMPANHA_RCHLO