
DECLARE @D1 VARCHAR(20) = '2022-04-02 00:00:00' --CONCAT((CONVERT(DATE,GETDATE()-1)), ' 00:00:00')
DECLARE @D2 VARCHAR(20) = '2022-04-25 23:59:59'--CONCAT((CONVERT(DATE,GETDATE()-1)), ' 23:59:59')

--DECLARE @D1 VARCHAR(20) =	'2022-04-08 00:00:00'
--DECLARE @D2 VARCHAR(20) =	'2022-04-11 23:59:59'
DECLARE @TSQL VARCHAR(8000)
DECLARE @IP VARCHAR(13) = '[10.251.1.36]'

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	DE PARA DAS FILAS CALLFLEX													    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

IF OBJECT_ID ('TEMPDB..#FILAS') IS NOT NULL DROP TABLE #FILAS
SELECT DISTINCT *
,CASE
WHEN NOME LIKE '%RIACHUELO%'	THEN 'RIACHUELO'
WHEN NOME LIKE '%ORIGINAL%'		THEN 'BANCO ORIGINAL'
WHEN NOME LIKE '%PAY%'			THEN 'BANCO ORIGINAL'
WHEN NOME LIKE '%VERDE%'		THEN 'BANCO ORIGINAL'
WHEN NOME LIKE '%CAEDU%'		THEN 'CAEDU'
WHEN NOME LIKE '%MENU%'			THEN 'MENU'
WHEN NOME LIKE '%RIACHUE%'		THEN 'RIACHUELO' ELSE 'OUTROS' END EMPRESA
INTO #FILAS
FROM OPENQUERY([10.251.2.18],'SELECT * FROM replica_atmspbb1.queues')

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	ANALITITO DE CHAMADAS RIACHUELO												    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

IF OBJECT_ID ('TEMPDB..#CHAMADAS') IS NOT NULL DROP TABLE #CHAMADAS
SELECT 
 DATA
,HORA
,DDD
,ORIGEM
,DOC
,IDCRM
,duracao
,conversado
,classe_order
,AGENTE
,STATUS
,STATUSATENDIMENTO
,STATUSNEGOCIO
,ISDNCAUSE
,VALOR
,TIPO
,A.FILA
,B.NOME NOME_FILA
,B.EMPRESA
,TERMINATOR
INTO #CHAMADAS
FROM DATA_SCIENCE.DBO.TB_DS_CALLFLEX_MES A 
INNER JOIN #FILAS B ON A.FILA = B.FILA
WHERE CALLDATE BETWEEN @D1 AND @D2
AND B.EMPRESA IN ('RIACHUELO')

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	ANALITICO DE PRODUTIVIDADE													    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

/*
DECLARE @D1 VARCHAR(20) = '2022-04-01 00:00:00' --CONCAT((CONVERT(DATE,GETDATE()-1)), ' 00:00:00')
DECLARE @D2 VARCHAR(20) = '2022-04-01 23:59:59'--CONCAT((CONVERT(DATE,GETDATE()-1)), ' 23:59:59')

--DECLARE @D1 VARCHAR(20) =	'2022-04-08 00:00:00'
--DECLARE @D2 VARCHAR(20) =	'2022-04-11 23:59:59'
DECLARE @TSQL VARCHAR(8000)
DECLARE @IP VARCHAR(13) = '[10.251.1.36]'
*/

IF OBJECT_ID ('tempdb.dbo.##PROD1') IS NOT NULL DROP TABLE ##PROD1
SELECT  @TSQL = 
'SELECT * INTO ##PROD1 FROM 
OPENQUERY('+@IP+',
''SELECT
 DTNAS_DEV
,ESTAD_ETD
,DESCR_ETD
,DTAND_AND
,IDAND_AND
,IDCON_AND
,IDOCO_AND
,ORIGE_AND
,CONTR_CON
,DTATR_CON
,IDEMP_CON
,VLMAC_CON
,IMAPS_OCO
,DESCR_OCO
,IDPES_PES
,USUAR_PES
,CGCPF_DEV
FROM	   NECTAR.DBO.TB_ANDAMENTO 	WITH(NOLOCK)
INNER JOIN NECTAR.DBO.TB_CONTRATO 	WITH(NOLOCK) ON IDCON_AND = IDCON_CON  
INNER JOIN NECTAR.DBO.TB_DEVEDOR	WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
INNER JOIN NECTAR.DBO.TB_OCORRENCIA	WITH(NOLOCK) ON IDOCO_AND = IDOCO_OCO  
INNER JOIN NECTAR.DBO.TB_PESSOAL	WITH(NOLOCK) ON IDPES_AND = IDPES_PES
INNER JOIN NECTAR.DBO.TB_ENDERECO   WITH(NOLOCK) ON IDCON_CON = IDORI_END  
INNER JOIN NECTAR.DBO.TB_ESTADO		WITH(NOLOCK) ON IDEST_END = IDEST_ETD  
WHERE IDEMP_CON IN (3,5,6)
AND CANCE_AND = 0
AND DTAND_AND BETWEEN '''''+@D1+''''' AND ''''' +@D2+ ''''''')'
EXEC(@TSQL)

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	ETL ANALITICO DE PROD RETIRANDO OS ACORDOS E OCO NEGOCIAÇÃO COM SUSSECO		    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/


/*
DECLARE @D1 VARCHAR(20) = '2022-04-01 00:00:00' --CONCAT((CONVERT(DATE,GETDATE()-1)), ' 00:00:00')
DECLARE @D2 VARCHAR(20) = '2022-04-01 23:59:59'--CONCAT((CONVERT(DATE,GETDATE()-1)), ' 23:59:59')

--DECLARE @D1 VARCHAR(20) =	'2022-04-08 00:00:00'
--DECLARE @D2 VARCHAR(20) =	'2022-04-11 23:59:59'
DECLARE @TSQL VARCHAR(8000)
DECLARE @IP VARCHAR(13) = '[10.251.1.36]'
*/

IF OBJECT_ID('TEMPDB..#PROD2') IS NOT NULL DROP TABLE #PROD2
SELECT 
CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 '
END [IDADE]
,ESTAD_ETD
,DESCR_ETD
,DTAND_AND	=	CONVERT(DATE,DTAND_AND)
,HRAND_AND	=	CONVERT(VARCHAR(8),DTAND_AND,108) 
,IDAND_AND
,IMAPS_OCO
,IDPES_PES
,USUAR_PES
,CONTR_CON
,IDCON_AND
,IDOCO_AND
,CGCPF_DEV
,IDEMP_CON
,DESCR_OCO
,AGING		=	DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTAND_AND)) 
,VLMAC_CON	=	CONVERT(MONEY,MAX(VLMAC_CON))  
INTO #PROD2
FROM ##PROD1
WHERE IMAPS_OCO NOT IN ('PROMESSA','ACORDO')
AND	IDOCO_AND   NOT IN  (604)
GROUP BY
 CONVERT(DATE,DTAND_AND)
,CONVERT(VARCHAR(8),DTAND_AND,108)
,IDAND_AND
,IMAPS_OCO
,IDCON_AND
,CGCPF_DEV
,IDEMP_CON
,DESCR_OCO
,IDOCO_AND
,IDPES_PES
,USUAR_PES
,CONTR_CON
,ESTAD_ETD
,DESCR_ETD
,CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 '
END


/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	ANALITICO DE ACORDOS 															*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*
DECLARE @D1 VARCHAR(20) = '2022-04-01 00:00:00' --CONCAT((CONVERT(DATE,GETDATE()-1)), ' 00:00:00')
DECLARE @D2 VARCHAR(20) = '2022-04-01 23:59:59'--CONCAT((CONVERT(DATE,GETDATE()-1)), ' 23:59:59')

--DECLARE @D1 VARCHAR(20) =	'2022-04-08 00:00:00'
--DECLARE @D2 VARCHAR(20) =	'2022-04-11 23:59:59'
DECLARE @TSQL VARCHAR(8000)
DECLARE @IP VARCHAR(13) = '[10.251.1.36]'
*/

SELECT @TSQL =   
'IF OBJECT_ID(''TEMPDB..##ACOR1'') IS NOT NULL DROP TABLE ##ACOR1
SELECT * INTO ##ACOR1 FROM  
OPENQUERY('+@IP+',  
''SELECT  
 DTNAS_DEV
,ESTAD_ETD
,DESCR_ETD
,DTVEN_PAG  
,DTPAG_PAG  
,VLVEN_PAG  
,VLPAG_PAG  
,PAGAM_PAG  
,DTACO_ACO  
,DTCAD_ACO
,DTCAN_ACO
,IDPES_ACO
,STACO_ACO   
,IDCON_ACO
,VLMAC_CON  
,DTATR_CON  
,PLANO_CON      
,CONTR_CON  
,IDEMP_CON   
,USUAR_PES  
,NOME_PES  
,CGCPF_DEV 
FROM       [NECTAR].[DBO].[TB_ACORDO]		WITH(NOLOCK)  
INNER JOIN [NECTAR].[DBO].[TB_CONTRATO]		WITH(NOLOCK) ON IDCON_CON = IDCON_ACO   
INNER JOIN [NECTAR].[DBO].[TB_DEVEDOR]		WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON  
INNER JOIN [NECTAR].[DBO].[TB_PAGAMENTO]	WITH(NOLOCK) ON IDACO_PAG = IDACO_ACO  
INNER JOIN [NECTAR].[DBO].[TB_PESSOAL]		WITH(NOLOCK) ON IDPES_PES = IDPES_ACO 
INNER JOIN [NECTAR].[DBO].[TB_ENDERECO]		WITH(NOLOCK) ON IDCON_CON = IDORI_END  
INNER JOIN [NECTAR].[DBO].[TB_ESTADO]		WITH(NOLOCK) ON IDEST_END = IDEST_ETD 
WHERE DTACO_ACO BETWEEN '''''+ @D1 +''''' AND '''''+ @D2 +'''''  
AND IDEMP_CON IN (3,5,6)
AND PAGAM_PAG = 1''
) A'  
EXEC (@TSQL)    

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	ETL ANALITICO DE ACORDOS CONSOLIDANDO COM ANALITICO DE PROD						*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

/*
DECLARE @D1 VARCHAR(20) = '2022-04-01 00:00:00' --CONCAT((CONVERT(DATE,GETDATE()-1)), ' 00:00:00')
DECLARE @D2 VARCHAR(20) = '2022-04-01 23:59:59'--CONCAT((CONVERT(DATE,GETDATE()-1)), ' 23:59:59')

--DECLARE @D1 VARCHAR(20) =	'2022-04-08 00:00:00'
--DECLARE @D2 VARCHAR(20) =	'2022-04-11 23:59:59'
DECLARE @TSQL VARCHAR(8000)
DECLARE @IP VARCHAR(13) = '[10.251.1.36]'
*/


IF OBJECT_ID('TEMPDB..#PROD3') IS NOT NULL DROP TABLE #PROD3
SELECT DISTINCT
CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 '
END [IDADE]
,ESTAD_ETD
,DESCR_ETD
,DTACO_ACO	=	CONVERT(DATE,DTACO_ACO)  
,DTPAG_PAG	=	CONVERT(DATE,DTPAG_PAG) 
,HORA		=	CONVERT(VARCHAR(8),DTCAD_ACO,108) 
,IDEMP_CON  
,IDPES_ACO  
,USUAR_PES  
,AGING		=	DATEDIFF(DAY,CONVERT(DATE,MIN(DTATR_CON)),CONVERT(DATE,DTACO_ACO))   
,VLMAC_CON	=	CONVERT(MONEY,MAX(VLMAC_CON))  
,VLVEN_PAG	=	CONVERT(MONEY,VLVEN_PAG) 
,VLPAG_PAG	=	CONVERT(MONEY,VLPAG_PAG) 
,CGCPF_DEV  
,CONTR_CON  
,IDCON_ACO
,67 IDOCO_OCO
INTO #PROD3
FROM ##ACOR1 
WHERE LEFT(DTCAD_ACO,10) <> (CASE WHEN DTCAN_ACO IS NULL THEN '2019-01-01' ELSE LEFT(DTCAN_ACO,10) END)
GROUP BY    
 CONVERT(DATE,DTACO_ACO)  
,CONVERT(DATE,DTPAG_PAG)  
,CONVERT(VARCHAR(8),DTCAD_ACO,108)
,IDPES_ACO  
,USUAR_PES  
,CONVERT(MONEY,VLVEN_PAG)
,CONVERT(MONEY,VLPAG_PAG)
,CGCPF_DEV  
,CONTR_CON 
,IDEMP_CON  
,IDCON_ACO
,CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 '
END 
,ESTAD_ETD
,DESCR_ETD

UNION ALL

SELECT 
 [IDADE]
,ESTAD_ETD
,DESCR_ETD
,DTACO_ACO	=	CONVERT(DATE,DTAND_AND) 
,NULL					 
,HRAND_AND				 
,IDEMP_CON				 
,IDPES_PES				 
,USUAR_PES				 
,AGING					 
,VLMAC_CON				 
,VLVEN_PAG	=	NULL					 
,VLPAG_PAG	=	NULL					 
,CGCPF_DEV				 
,CONTR_CON				 
,IDCON_AND				 
,IDOCO_AND
FROM #PROD2
GROUP BY
 CONVERT(DATE,DTAND_AND)
,HRAND_AND
,IDEMP_CON  
,IDPES_PES 
,USUAR_PES
,CGCPF_DEV  
,CONTR_CON  
,IDCON_AND
,AGING
,IDOCO_AND
,VLMAC_CON
,IDADE
,ESTAD_ETD
,DESCR_ETD

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	ELEGE A ORDEM DAS TABULAÇÕES POR HORARIO ASC									*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

IF OBJECT_ID('TEMPDB..#TEMP1') IS NOT NULL DROP TABLE #TEMP1
SELECT 
 VALID_PRO	=	ROW_NUMBER () OVER(PARTITION BY DTACO_ACO, IDCON_ACO ORDER BY HORA ASC)   
,A.* 
,DESCR_DXP
,TABULADO
,ALO
,CPC
,CPC_P
,ACORDO
into #TEMP1
/*
INTO tb_idade_estado_15a30
*/
FROM #PROD3 A
LEFT JOIN REPORTS..AUX_DEXPARA_ATMA C ON IDOCO_OCO = IDOCO_DXP
WHERE TABULADO = 1

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	ELEGE A ORDEM DAS CHAMADAS POR HORARIO ASC										*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/


IF OBJECT_ID('TEMPDB..#TEMP2') IS NOT NULL DROP TABLE #TEMP2
SELECT 
 ROW_NUMBER () OVER(PARTITION BY DATA, IDCRM, isdncause ORDER BY HORA ASC) VALID_CHA
,*
,CASE WHEN IDCRM = '' THEN NULL ELSE IDCRM END IDCRM_CHA
INTO #TEMP2
FROM #CHAMADAS

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	CONSOLIDA A PRODUTIVIDADE COM AS CHAMADAS DE ACORDO COM A TABULAÇÃO CORRETA		*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

IF OBJECT_ID('TEMPDB..#FINAL') IS NOT NULL DROP TABLE #FINAL
SELECT
 B.[IDADE]
,B.ESTAD_ETD
,B.DESCR_ETD
,DATA
,A.HORA
,HH	=	LEFT(A.HORA,2) 
,DDD
,ORIGEM
,DOC
,AGENTE
,IDCRM
,IDPES_ACO
,ISDNCAUSE
,DURACAO
,CONVERSADO
,VALOR
,A.TIPO
,FILA
,NOME_FILA
,DESCR_CTR
,EMPRESA
,TERMINATOR
,AGING
,VLMAC_CON
,VLVEN_PAG
,CGCPF_DEV
,CONTR_CON
,IDCON_ACO
,IDOCO_OCO
,DESCR_DXP
,TABULADO
,ALO
,CPC
,CPC_P
,ACORDO
,CASE WHEN ISDNCAUSE = 16 AND TABULADO IS NULL THEN 1 ELSE NULL END [N/TABULADO]
INTO #FINAL
FROM #TEMP2 A
	LEFT JOIN #TEMP1 B ON IDCRM_CHA = IDCON_ACO AND DATA = DTACO_ACO AND ISDNCAUSE = 16 AND VALID_PRO = VALID_CHA
		LEFT JOIN Reports..AUX_CLUSTER ON IDEMP_CTR = IDEMP_CON AND AGING BETWEEN INICI_CTR AND FINAL_CTR
WHERE IDCRM_CHA NOT IN ('TESTE')

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	LAYOUT FINAL																	*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

--SERT INTO tb_ds_daily_funil_ad__e_pa_15a30_FINAL_idade_estado
INSERT INTO tb_ds_daily_funil_ad__e_pa_15a30_FINAL_idade_estado

SELECT

IDADE,
ESTAD_ETD,
DESCR_ETD
 ,DATA
,NOME_FILA
,OP				=	COUNT(DISTINCT CASE WHEN AGENTE NOT IN (0) THEN AGENTE ELSE NULL END)	
,TENTATIVAS		=	COUNT( ORIGEM)															
,PENETRACAO		=	COUNT(DISTINCT IDCRM)													
,ATENDIDAS		=	SUM(CASE WHEN isdncause = 16 THEN 1 ELSE 0 END)						
,TABULADO		=	ISNULL(SUM(TABULADO)		,0)											
,ALO			=	ISNULL(SUM(ALO)			,0)											
,CPC	 		=	ISNULL(SUM(CPC)			,0)											
,CPC_P	 		=	ISNULL(SUM(CPC_P)			,0)											
,ACORDO			=	ISNULL(SUM(ACORDO)			,0)											
,VLACORDO		=	ISNULL(SUM(VLVEN_PAG)		,0)											
,ATENDIDAS_U	=	COUNT(DISTINCT CASE WHEN isdncause = 16 THEN IDCRM END)				
,TABULADO_U		=	COUNT(DISTINCT CASE WHEN TABULADO	= 1 THEN IDCRM END)					
,ALO_U			=	COUNT(DISTINCT CASE WHEN ALO		= 1 THEN IDCRM END)					
,CPC_U			=	COUNT(DISTINCT CASE WHEN CPC		= 1 THEN IDCRM END)					
,CPCP_U	 		=	COUNT(DISTINCT CASE WHEN CPC_P		= 1 THEN IDCRM END)					
,ACORDO_U		=	COUNT(DISTINCT CASE WHEN ACORDO	= 1 THEN IDCRM END)

/*
INTO tb_ds_daily_funil_ad__e_pa_15a30_FINAL_idade_estado
*/
FROM #FINAL

WHERE NOME_FILA in ('RIACHUELO_RUBI_15A30','ADRIACHUELO_16A30')

GROUP BY
 DATA,
IDADE,
ESTAD_ETD,
DESCR_ETD,
NOME_FILA