

use Planning
go


DROP TABLE IF EXISTS #TBL_BASE_ENRIQUECIMENTO
Select *
into #TBL_BASE_ENRIQUECIMENTO
FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0',
'Excel 12.0 Xml;HDR=YES;Database=\\POLARIS\NectarServices\Administrativo\Temporario\Riachuelo\Bases\Base\Enriquecimento\1.Base_para_Enriquecer\Base_RCH.xlsx'
,'SELECT *
FROM [Planilha1$]
');

TRUNCATE TABLE PLANNING..TEMP_CPF_LEMIT
INSERT INTO    PLANNING..TEMP_CPF_LEMIT
SELECT DISTINCT
RIGHT(CONCAT('00000000000',RTRIM(LTRIM(CPFCNPJ))),11) CPFCNPJ
,CARTEIRA
FROM #TBL_BASE_ENRIQUECIMENTO

-----------------------------------STEP1------------------------------------------
DROP TABLE IF EXISTS #BASE_ATIVA
SELECT *
INTO #BASE_ATIVA
FROM OPENQUERY([10.251.1.36],'
SELECT DISTINCT
    CGCPF_DEV
,   DDD_TEL      AS DDD
,   TELEF_TEL    AS TEL
FROM  NECTAR.DBO.TB_DEVEDOR  WITH (NOLOCK) 
JOIN  NECTAR.DBO.TB_CONTRATO WITH (NOLOCK) ON IDDEV_CON = IDDEV_DEV
JOIN  NECTAR.DBO.TB_TELEFONE WITH (NOLOCK) ON IDORI_TEL  = IDCON_CON
WHERE ORIGE_TEL = 0
AND STDEV_CON = ''0''
')

CREATE NONCLUSTERED INDEX SKU_CPF ON #BASE_ATIVA (CGCPF_DEV)


DROP TABLE IF EXISTS #CPF2
SELECT 
	X.CPFCNPJ
,	Y.DDD 
,	Y.TEL
INTO #CPF2
FROM PLANNING.DBO.TEMP_CPF_LEMIT X
JOIN #BASE_ATIVA				 Y ON Y.CGCPF_DEV = X.CPFCNPJ

PRINT 'STEP1 FINALIZADO'
----------------------------------------------------------------------------------
-----------------------------------STEP2------------------------------------------
IF OBJECT_ID('TEMPDB..#TEL') IS NOT NULL DROP TABLE #TEL
SELECT
    CPFCNPJ
,    DDD
,    TEL
,    ROW_NUMBER ( )    OVER ( PARTITION BY  CPFCNPJ ORDER BY TEL  DESC) AS RW
INTO
    #TEL
FROM #CPF2

PRINT 'STEP2 FINALIZADO'
----------------------------------------------------------------------------------
-----------------------------------STEP3------------------------------------------

TRUNCATE TABLE PLANNING.DBO.TB_DS_LAYOUT_LEMIT
INSERT INTO    PLANNING.DBO.TB_DS_LAYOUT_LEMIT

SELECT 
    CPFCNPJ    AS    [CPF]
,    ISNULL(MAX(CASE WHEN RW = 01 THEN DDD END),'') [DDD1],    ISNULL(MAX(CASE WHEN RW = 01 THEN TEL END),'') [TEL1]
,    ISNULL(MAX(CASE WHEN RW = 02 THEN DDD END),'') [DDD2],    ISNULL(MAX(CASE WHEN RW = 02 THEN TEL END),'') [TEL2]
,    ISNULL(MAX(CASE WHEN RW = 03 THEN DDD END),'') [DDD3],    ISNULL(MAX(CASE WHEN RW = 03 THEN TEL END),'') [TEL3]
,    ISNULL(MAX(CASE WHEN RW = 04 THEN DDD END),'') [DDD4],    ISNULL(MAX(CASE WHEN RW = 04 THEN TEL END),'') [TEL4]
,    ISNULL(MAX(CASE WHEN RW = 05 THEN DDD END),'') [DDD5],    ISNULL(MAX(CASE WHEN RW = 05 THEN TEL END),'') [TEL5]
,    ISNULL(MAX(CASE WHEN RW = 06 THEN DDD END),'') [DDD6],    ISNULL(MAX(CASE WHEN RW = 06 THEN TEL END),'') [TEL6]
,    ISNULL(MAX(CASE WHEN RW = 07 THEN DDD END),'') [DDD7],    ISNULL(MAX(CASE WHEN RW = 07 THEN TEL END),'') [TEL7]
,    ISNULL(MAX(CASE WHEN RW = 08 THEN DDD END),'') [DDD8],    ISNULL(MAX(CASE WHEN RW = 08 THEN TEL END),'') [TEL8]
,    ISNULL(MAX(CASE WHEN RW = 09 THEN DDD END),'') [DDD9],    ISNULL(MAX(CASE WHEN RW = 09 THEN TEL END),'') [TEL9]
,    ISNULL(MAX(CASE WHEN RW = 10 THEN DDD END),'') [DDD10],    ISNULL(MAX(CASE WHEN RW = 10 THEN TEL END),'') [TEL10]
,    ISNULL(MAX(CASE WHEN RW = 11 THEN DDD END),'') [DDD11],    ISNULL(MAX(CASE WHEN RW = 11 THEN TEL END),'') [TEL11]
,    ISNULL(MAX(CASE WHEN RW = 12 THEN DDD END),'') [DDD12],    ISNULL(MAX(CASE WHEN RW = 12 THEN TEL END),'') [TEL12]
,    ISNULL(MAX(CASE WHEN RW = 13 THEN DDD END),'') [DDD13],    ISNULL(MAX(CASE WHEN RW = 13 THEN TEL END),'') [TEL13]
,    ISNULL(MAX(CASE WHEN RW = 14 THEN DDD END),'') [DDD14],    ISNULL(MAX(CASE WHEN RW = 14 THEN TEL END),'') [TEL14]
,    ISNULL(MAX(CASE WHEN RW = 15 THEN DDD END),'') [DDD15],    ISNULL(MAX(CASE WHEN RW = 15 THEN TEL END),'') [TEL15]
,    ISNULL(MAX(CASE WHEN RW = 16 THEN DDD END),'') [DDD16],    ISNULL(MAX(CASE WHEN RW = 16 THEN TEL END),'') [TEL16]
,    ISNULL(MAX(CASE WHEN RW = 17 THEN DDD END),'') [DDD17],    ISNULL(MAX(CASE WHEN RW = 17 THEN TEL END),'') [TEL17]
,    ISNULL(MAX(CASE WHEN RW = 18 THEN DDD END),'') [DDD18],    ISNULL(MAX(CASE WHEN RW = 18 THEN TEL END),'') [TEL18]
,    ISNULL(MAX(CASE WHEN RW = 19 THEN DDD END),'') [DDD19],    ISNULL(MAX(CASE WHEN RW = 19 THEN TEL END),'') [TEL19]
,    ISNULL(MAX(CASE WHEN RW = 20 THEN DDD END),'') [DDD20],    ISNULL(MAX(CASE WHEN RW = 20 THEN TEL END),'') [TEL20]
,    ISNULL(MAX(CASE WHEN RW = 21 THEN DDD END),'') [DDD21],    ISNULL(MAX(CASE WHEN RW = 21 THEN TEL END),'') [TEL21]
,    ISNULL(MAX(CASE WHEN RW = 22 THEN DDD END),'') [DDD22],    ISNULL(MAX(CASE WHEN RW = 22 THEN TEL END),'') [TEL22]
,    ISNULL(MAX(CASE WHEN RW = 23 THEN DDD END),'') [DDD23],    ISNULL(MAX(CASE WHEN RW = 23 THEN TEL END),'') [TEL23]
,    ISNULL(MAX(CASE WHEN RW = 24 THEN DDD END),'') [DDD24],    ISNULL(MAX(CASE WHEN RW = 24 THEN TEL END),'') [TEL24]
,    ISNULL(MAX(CASE WHEN RW = 25 THEN DDD END),'') [DDD25],    ISNULL(MAX(CASE WHEN RW = 25 THEN TEL END),'') [TEL25]
,    ISNULL(MAX(CASE WHEN RW = 26 THEN DDD END),'') [DDD26],    ISNULL(MAX(CASE WHEN RW = 26 THEN TEL END),'') [TEL26]
,    ISNULL(MAX(CASE WHEN RW = 27 THEN DDD END),'') [DDD27],    ISNULL(MAX(CASE WHEN RW = 27 THEN TEL END),'') [TEL27]
,    ISNULL(MAX(CASE WHEN RW = 28 THEN DDD END),'') [DDD28],    ISNULL(MAX(CASE WHEN RW = 28 THEN TEL END),'') [TEL28]
,    ISNULL(MAX(CASE WHEN RW = 29 THEN DDD END),'') [DDD29],    ISNULL(MAX(CASE WHEN RW = 29 THEN TEL END),'') [TEL29]
,    ISNULL(MAX(CASE WHEN RW = 30 THEN DDD END),'') [DDD30],    ISNULL(MAX(CASE WHEN RW = 30 THEN TEL END),'') [TEL30]
,    ISNULL(MAX(CASE WHEN RW = 31 THEN DDD END),'') [DDD31],    ISNULL(MAX(CASE WHEN RW = 31 THEN TEL END),'') [TEL31]
,    ISNULL(MAX(CASE WHEN RW = 32 THEN DDD END),'') [DDD32],    ISNULL(MAX(CASE WHEN RW = 32 THEN TEL END),'') [TEL32]
,    ISNULL(MAX(CASE WHEN RW = 33 THEN DDD END),'') [DDD33],    ISNULL(MAX(CASE WHEN RW = 33 THEN TEL END),'') [TEL33]
,    ISNULL(MAX(CASE WHEN RW = 34 THEN DDD END),'') [DDD34],    ISNULL(MAX(CASE WHEN RW = 34 THEN TEL END),'') [TEL34]
,    ISNULL(MAX(CASE WHEN RW = 35 THEN DDD END),'') [DDD35],    ISNULL(MAX(CASE WHEN RW = 35 THEN TEL END),'') [TEL35]
,    ISNULL(MAX(CASE WHEN RW = 36 THEN DDD END),'') [DDD36],    ISNULL(MAX(CASE WHEN RW = 36 THEN TEL END),'') [TEL36]
,    ISNULL(MAX(CASE WHEN RW = 37 THEN DDD END),'') [DDD37],    ISNULL(MAX(CASE WHEN RW = 37 THEN TEL END),'') [TEL37]
,    ISNULL(MAX(CASE WHEN RW = 38 THEN DDD END),'') [DDD38],    ISNULL(MAX(CASE WHEN RW = 38 THEN TEL END),'') [TEL38]
,    ISNULL(MAX(CASE WHEN RW = 39 THEN DDD END),'') [DDD39],    ISNULL(MAX(CASE WHEN RW = 39 THEN TEL END),'') [TEL39]
,    ISNULL(MAX(CASE WHEN RW = 40 THEN DDD END),'') [DDD40],    ISNULL(MAX(CASE WHEN RW = 40 THEN TEL END),'') [TEL40]
FROM #TEL

GROUP BY CPFCNPJ

PRINT 'STEP3 FINALIZADO'

----------------------------------------------------------------------------------
-----------------------------------STEP4------------------------------------------
DECLARE @CARTEIRA VARCHAR(MAX) = (SELECT DISTINCT CARTEIRA FROM  PLANNING..TEMP_CPF_LEMIT WHERE CARTEIRA IS NOT NULL)
DECLARE @COLUMNS VARCHAR(MAX)
DECLARE @COLUMNS2 VARCHAR(MAX)
DECLARE @POS VARCHAR(MAX)  = (SELECT concat('TEL',MAX(RW)) FROM #TEL)
DECLARE @POS1 VARCHAR(MAX) = (SELECT ORDINAL_POSITION
                                                        FROM INFORMATION_SCHEMA.COLUMNS
                                                        WHERE TABLE_NAME = 'TB_DS_LAYOUT_LEMIT'
                                                        AND COLUMN_NAME = @POS)


SELECT @COLUMNS = ISNULL(@COLUMNS + ', ','') + QUOTENAME(COLUMN_NAME)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TB_DS_LAYOUT_LEMIT' AND ORDINAL_POSITION <= @POS1
ORDER BY ORDINAL_POSITION


SELECT @COLUMNS2 = ISNULL(@COLUMNS2 + ', ','') + QUOTENAME(COLUMN_NAME)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TB_DS_LAYOUT_LEMI_CABECALHO' AND ORDINAL_POSITION <= @POS1
ORDER BY ORDINAL_POSITION


IF OBJECT_ID('TEMPDB..##INFO') IS NOT NULL DROP TABLE ##INFO
EXEC ('SELECT 2 AUX,' + @COLUMNS + 'INTO ##INFO FROM TB_DS_LAYOUT_LEMIT' )


IF OBJECT_ID('TEMPDB..##CABE') IS NOT NULL DROP TABLE ##CABE
EXEC ('SELECT 1 AUX,' + @COLUMNS2 + 'INTO ##CABE FROM TB_DS_LAYOUT_LEMI_CABECALHO')


IF OBJECT_ID('TEMPDB..##FINAL') IS NOT NULL DROP TABLE ##FINAL
SELECT
    *
INTO ##FINAL
FROM ##CABE

UNION ALL

SELECT
    *
FROM ##INFO

--TRUNCATE TABLE REPORTS..TEMP_CPF_LEMIT

SELECT * FROM ##FINAL
PRINT 'STEP4 FINALIZADO'
SET LANGUAGE 'BRAZILIAN'

DECLARE @DATA        VARCHAR(10) = (replace (cast(getdate() as date),'-',''))
DECLARE @HORA        VARCHAR (3) = LEFT(CONVERT (TIME,GETDATE()),2)
DECLARE @MINUTOS     VARCHAR (3) = right (left (CONVERT (TIME,GETDATE()),5),2)
--DECLARE @NOMENCLATURA_DISPARO_DIAMANTE_OP VARCHAR(MAX) = 'MAILING_DIAMANTE_OP_'+@DATA+'_'+@HORA+'.csv'


DECLARE @BCP VARCHAR(MAX)

/*************************************    PREVENTIVO    *************************************/

SET @BCP = ' master..xp_cmdshell ''bcp "SELECT * FROM ##FINAL " queryout "\\POLARIS\NectarServices\Administrativo\Temporario\Riachuelo\Bases\Base\Enriquecimento\2.Layout_Lemit"\'+'Base_Enriquecimento_'+@DATA+'_'+@HORA+'_'+@CARTEIRA+'.TXT'+' -c -T -t ";" '''
EXEC(
	 @BCP
	)