

USE Planning
GO

--> TRAZ A CARTEIRA D0
DROP TABLE IF EXISTS #FOTOGRAFIA_D0
SELECT * 
INTO #FOTOGRAFIA_D0
FROM OPENQUERY([WOLVERINE],'
SELECT DISTINCT *
FROM DATA_SCIENCE.DBO.TB_DS_FOTOGRAFIA_RENNER_D0 [A] WITH(NOLOCK)
')


select 
ID_CONTRATO,
CPF_CNPJ,
ATR_CADOC AS CADOC, 
CASE
    WHEN RENEG         = 1                        THEN 'RENEG'
    WHEN ATR_CADOC < 0                            THEN 'A VENCER'
    WHEN ATR_CADOC = 0                           THEN '0000-0000'
    WHEN ATR_CADOC BETWEEN 0001    AND    0090    THEN '0001-0090'
    WHEN ATR_CADOC BETWEEN 0091    AND    0180    THEN '0091-0180'
    WHEN ATR_CADOC BETWEEN 0181    AND    0360       THEN '0181-0360'
    WHEN ATR_CADOC BETWEEN 0361       AND    9999    THEN '0361-9999'
ELSE '''' END AS FAIXA_ATRASO,
[A].PRODUTO,
[A].SALDO,
SEGMENTACAO,
MOMENTO_ATRASO,
PROP_REC

FROM #FOTOGRAFIA_D0 [A]
LEFT JOIN PLANNING..MATRIZ_91A360_062023 [B] WITH(NOLOCK) ON CPF=CPF_CNPJ