
USE DATA_SCIENCE
GO

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*																								*/
/* PROGRAMADOR: FLAVIO ASSIS									                                */
/* VERSAO     : DATA: 27/05/2022																*/
/* DESCRICAO  : RESPONSAVEL POR PEGAR AS PROPRIEDADES DE ACORDO DOS OPERADORES		 		    */
/*																								*/
/*	ALTERACAO                                                                                   */
/*        2. PROGRAMADOR: KAIKE NATAN										 DATA: 31/05/2022	*/		
/*           DESCRICAO  : REMODELAGEM DO LAYOUT COM OPEN QUERY DINÂMICO							*/
/*	ALTERACAO                                                                                   */
/*        3. PROGRAMADOR:													 DATA: __/__/____	*/		
/*           DESCRICAO  :										 								*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	CREATE OR ALTER PROCEDURE PRC_DS_PAG_DIRETOS_INDIRETOS_RENNER AS 
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	VARIÁVEL DE CONTROLE														    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	DECLARE @DATA_INICIAL VARCHAR(MAX)	=	 CONCAT(CAST(GETDATE() - DATEPART(DAY,GETDATE() -1) AS DATE),' 00:00:00.000')
	DECLARE @DATA_FINAL	  VARCHAR(MAX)	=	 CONCAT(EOMONTH(GETDATE()),' 23:59:59.599')
	DECLARE @LAST_MONTH   VARCHAR(MAX)	=	 CONCAT(DATEADD(DD,-DATEPART(DD,GETDATE()),CONVERT(DATE,GETDATE()-10)),' 00:00:00.000')
	DECLARE @IP	VARCHAR(13)				=	'[10.251.1.36]'
	DECLARE @VAZIO VARCHAR(10)			=   ''	
	DECLARE @ID_CARTEIRA VARCHAR(4)		=	'17'
	DECLARE @TSQL NVARCHAR(4000)
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: PAGAMENTOS SOB ACORDO E ESPONTANEOS (PAGAMENTO DIRETO)						    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
DROP TABLE IF EXISTS ##LANCAMENTOS
SET @TSQL = 'SELECT * INTO ##LANCAMENTOS FROM OPENQUERY('+@IP+',''
SELECT DISTINCT 
		 IDEMP_CON
		,CGCPF_DEV
		,IDDEV_DEV
		,IDCON_CON
		,CONTR_CON
		,CONVERT(DATE,MIN(DTFAT_ATI)) AS DTFAT_ATI
		,CONVERT(DATE,DTATR_CON) AS DTATR_CON
		,IDACO_ACO
		,IDPES_ACO
		,NOME_PES
		,ALCAD_PES
		,USUAR_PES
		,CONVERT(DATE,DTCAD_ACO) AS DTCAD_ACO
		,PAGAM_PAG
		,IDPAG_PAG
		,CONVERT(DATE,DTPAG_PAG) AS DTPAG_PAG
		,CONVERT(DATE,DTVEN_PAG) AS DTVEN_PAG
		,CONVERT(MONEY,VLPAG_PAG) AS VLPAG_PAG
		,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END DESCR_BND
FROM NECTAR.DBO.TB_PAGAMENTO WITH(NOLOCK)
INNER JOIN NECTAR.DBO.TB_ACORDO WITH(NOLOCK) ON IDACO_ACO = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_ACORDOTIT WITH(NOLOCK) ON IDACO_ATI = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = IDDOC_ATI
LEFT JOIN NECTAR.DBO.TB_PESSOAL WITH(NOLOCK) ON IDPES_PES = IDPES_ACO
INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_ACO
INNER JOIN NECTAR.DBO.TB_DEVEDOR WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN NECTAR.DBO.TB_BANDEIRA WITH(NOLOCK) ON IDBND_BND = IDBND_CON
WHERE DTPAG_PAG BETWEEN '''''+@DATA_INICIAL+''''' AND ''''' +@DATA_FINAL+ '''''
AND IDEMP_CON = '''''+@ID_CARTEIRA+'''''
GROUP BY  
		 IDEMP_CON
		,CGCPF_DEV
		,IDDEV_DEV
		,IDCON_CON
		,CONTR_CON
		,CONVERT(DATE,DTATR_CON)
		,IDACO_ACO
		,IDPES_ACO
		,NOME_PES
		,ALCAD_PES
		,USUAR_PES
		,CONVERT(DATE,DTCAD_ACO)
		,PAGAM_PAG
		,IDPAG_PAG
		,CONVERT(DATE,DTPAG_PAG)
		,CONVERT(DATE,DTVEN_PAG)
		,CONVERT(MONEY,VLPAG_PAG)
		,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END

UNION ALL

SELECT DISTINCT 
				 IDEMP_CON
				,CGCPF_DEV
				,IDDEV_DEV
				,IDCON_CON
				,CONTR_CON
				,CONVERT(DATE,MIN(DTFAT_PGD)) AS DTFAT_PGD
				,CONVERT(DATE,DTATR_CON) AS DTATR_CON
				,NULL AS IDACO_ACO
				,NULL AS IDPES_ACO
				,NULL AS NOME_PES
				,NULL AS ALCAD_PES
				,NULL AS USUAR_PES
				,CONVERT(DATE,DTPAG_PGD) AS DTPAG_PGD
				,1 AS PAGAM_PGD
				,IDPGD_PGD
				,CONVERT(DATE,DTPAG_PGD) AS DTPAG_PGD
				,CONVERT(DATE,DTPAG_PGD) AS DTVEN_PGD
				,CONVERT(MONEY,VLPAG_PGD) AS VLPAG_PGD
				,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END DESCR_BND
FROM NECTAR.DBO.TB_PAGDIRETO WITH(NOLOCK)
INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_PGD
INNER JOIN NECTAR.DBO.TB_DEVEDOR WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN (
			SELECT DISTINCT IDCON_TRA,IDDOC_TRA FROM NECTAR.DBO.TB_TRANSACAO WITH(NOLOCK) INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_TRA AND IDEMP_CON = '''''+@ID_CARTEIRA+'''''
			UNION ALL
			SELECT DISTINCT IDCON_BAI,IDDOC_BAI FROM NECTAR.DBO.TB_BAIXA WITH(NOLOCK) INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_BAI AND IDEMP_CON = '''''+@ID_CARTEIRA+'''''		
		  )A ON IDCON_TRA = IDCON_PGD
LEFT JOIN NECTAR.DBO.TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = A.IDDOC_TRA
LEFT JOIN NECTAR.DBO.TB_BANDEIRA WITH(NOLOCK) ON IDBND_BND = IDBND_CON
WHERE DTPAG_PGD BETWEEN '''''+@DATA_INICIAL+''''' AND ''''' +@DATA_FINAL+ ''''' 
AND IDEMP_CON = '''''+@ID_CARTEIRA+'''''
GROUP BY  
		 IDEMP_CON
		,CGCPF_DEV
		,IDDEV_DEV
		,IDCON_CON
		,CONTR_CON
		,CONVERT(DATE,DTATR_CON)
		,IDPGD_PGD
		,CONVERT(DATE,DTPAG_PGD)
		,CONVERT(MONEY,VLPAG_PGD)
		,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END '')'
EXEC SP_EXECUTESQL @TSQL
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: TRATAMENTO DE BASE PARA CLUSTERIZAR PRODUTO/ATRASO					   		    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
DROP TABLE IF EXISTS #CLUSTERIZACAO
SELECT
 A.*
,DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO)) AS ATRASO
,CASE 
      WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	-9999  AND 30		THEN '0001 A 0030'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	31	   AND 60		THEN '0031 A 0060'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	61	   AND 90		THEN '0061 A 0090'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	91	   AND 120		THEN '0091 A 0120'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	121	   AND 180		THEN '0121 A 0180'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	181	   AND 240		THEN '0181 A 0240'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	241    AND 360		THEN '0241 A 0360' 
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	361    AND 720		THEN '0361 A 0720' 
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	721    AND 1080		THEN '0721 A 1080'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	1081   AND 1440		THEN '1081 A 1440'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	1441   AND 1800		THEN '1441 A 1800'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	1801   AND 99999    THEN '1801 A 9999' END FAIXA 
,CASE 
	  WHEN IDEMP_CON = '17' AND DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				  THEN 'CBR'
	  WHEN IDEMP_CON = '17' AND DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI') THEN 'CCR'
	  WHEN IDEMP_CON = '17' AND DESCR_BND IN ('REPCFI','EPCFI')									  THEN 'EP'  END PRODUTO
,CASE WHEN IDACO_ACO IS NULL THEN 'ESPONTANEO' ELSE	'ACORDO' END ORIGEM
INTO #CLUSTERIZACAO
FROM ##LANCAMENTOS A 
WHERE DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO)) > 0
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: IDENTIFICAR PROPRIEDADE DE ACORDO (?), DESDE QUE ATÉ 10 DIAS ANTES DO PAGAMENTO	*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
DROP TABLE IF EXISTS ##ACORDOS
SET @TSQL = 'SELECT * INTO ##ACORDOS FROM OPENQUERY('+@IP+',''
SELECT DISTINCT 
		 IDEMP_CON
		,CGCPF_DEV
		,IDDEV_DEV
		,IDCON_CON
		,CONTR_CON
		,CONVERT(DATE,MIN(DTFAT_ATI)) AS DTFAT_ATI
		,CONVERT(DATE,DTATR_CON) AS DTATR_CON
		,IDACO_ACO
		,IDPES_ACO
		,NOME_PES
		,ALCAD_PES
		,USUAR_PES
		,CONVERT(DATE,DTCAD_ACO) AS DTCAD_ACO
		,PAGAM_PAG
		,IDPAG_PAG
		,DTCAN_ACO
		,CONVERT(DATE,DTPAG_PAG) AS DTPAG_PAG
		,CONVERT(DATE,DTVEN_PAG) AS DTVEN_PAG
		,CONVERT(MONEY,VLPAG_PAG) AS VLPAG_PAG
		,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END DESCR_BND
FROM NECTAR.DBO.TB_PAGAMENTO WITH(NOLOCK)
INNER JOIN NECTAR.DBO.TB_ACORDO WITH(NOLOCK) ON IDACO_ACO = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_ACORDOTIT WITH(NOLOCK) ON IDACO_ATI = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = IDDOC_ATI
LEFT JOIN NECTAR.DBO.TB_PESSOAL WITH(NOLOCK) ON IDPES_PES = IDPES_ACO
INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_ACO
INNER JOIN NECTAR.DBO.TB_DEVEDOR WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN NECTAR.DBO.TB_BANDEIRA WITH(NOLOCK) ON IDBND_BND = IDBND_CON
WHERE DTCAD_ACO BETWEEN '''''+@LAST_MONTH+''''' AND ''''' +@DATA_FINAL+ ''''' 
AND IDEMP_CON = '''''+@ID_CARTEIRA+''''' 
AND PAGAM_PAG = 1
GROUP BY  
		 IDEMP_CON
		,CGCPF_DEV
		,IDDEV_DEV
		,IDCON_CON
		,CONTR_CON
		,CONVERT(DATE,DTATR_CON)
		,IDACO_ACO
		,IDPES_ACO
		,NOME_PES
		,ALCAD_PES
		,USUAR_PES
		,CONVERT(DATE,DTCAD_ACO)
		,PAGAM_PAG
		,IDPAG_PAG
		,DTCAN_ACO
		,CONVERT(DATE,DTPAG_PAG)
		,CONVERT(DATE,DTVEN_PAG)
		,CONVERT(MONEY,VLPAG_PAG)
		,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END '')' 
EXEC SP_EXECUTESQL @TSQL
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: ATRIBUI PROPRIEDADE AO ACORDO, DESDE QUE ATÉ 10 DIAS ANTES DO PAGAMENTO			*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
DROP TABLE IF EXISTS ##TABULACAO
SET @TSQL = 'SELECT * INTO ##TABULACAO FROM OPENQUERY('+@IP+',''
SELECT DISTINCT 
	IDPES_AND AS IDPES_PROM
,	IMAPS_OCO
,	DESCR_OCO
,	NOME_PES AS NOME_PROM
,	CONTR_CON AS CONTR_PROM
,	CGCPF_DEV AS CGCPF_PROM 
,	CONVERT(DATE,DTAND_AND) AS DATA_PROM 
FROM NECTAR.DBO.TB_ANDAMENTO
INNER JOIN NECTAR.DBO.TB_CONTRATO ON IDCON_CON = IDCON_AND
INNER JOIN NECTAR.DBO.TB_DEVEDOR ON IDDEV_CON = IDDEV_DEV
INNER JOIN NECTAR.DBO.TB_PESSOAL ON IDPES_AND = IDPES_PES
INNER JOIN NECTAR.DBO.TB_OCORRENCIA ON IDOCO_AND = IDOCO_OCO
WHERE CONVERT(DATE,DTAND_AND) BETWEEN '''''+@LAST_MONTH+''''' AND ''''' +@DATA_FINAL+ ''''' 
AND  IDEMP_CON =  '''''+@ID_CARTEIRA+'''''  
AND  ALCAD_PES != 9 
AND DESCR_OCO = ''''PROPOSTA EXCEÇÃO ENVIADA PARA ANALISE'''' '')'
EXEC SP_EXECUTESQL @TSQL
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: ATRIBUI PROPRIEDADE AO ACORDO, DESDE QUE ATÉ 10 DIAS ANTES DO PAGAMENTO			*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
DROP TABLE IF EXISTS #P1
SELECT
	L.IDEMP_CON
,	L.CGCPF_DEV
,	L.IDDEV_DEV
,	L.IDCON_CON
,	L.CONTR_CON
,	L.DTFAT_ATI
,	L.DTATR_CON
,	L.IDACO_ACO
,	L.IDPES_ACO
,	L.NOME_PES
,	L.ALCAD_PES
,	L.USUAR_PES
,	L.DTCAD_ACO
,	L.PAGAM_PAG
,	L.IDPAG_PAG
,	L.DTPAG_PAG
,	L.DTVEN_PAG
,	L.VLPAG_PAG
,	L.DESCR_BND
,	ATRASO		=	CASE WHEN L.DTATR_CON < L.DTFAT_ATI THEN DATEDIFF(DAY,L.DTATR_CON,L.DTCAD_ACO) ELSE DATEDIFF(DAY,L.DTFAT_ATI,L.DTCAD_ACO) END
INTO #P1
FROM ##LANCAMENTOS L
INNER JOIN (
				SELECT DISTINCT
						A.CGCPF_DEV
					   ,MAX(A.DTCAD_ACO) AS ULTIMO_ACORDO
				FROM ##ACORDOS A 
INNER JOIN
			##LANCAMENTOS L ON L.CGCPF_DEV = A.CGCPF_DEV AND L.DTCAD_ACO = A.DTCAD_ACO	
WHERE
		L.NOME_PES IS NOT NULL
GROUP BY
	  A.CGCPF_DEV
	 ,L.DTCAD_ACO
	 ,L.DTATR_CON
	 ,L.DTFAT_ATI) B ON L.CGCPF_DEV = B.CGCPF_DEV AND L.DTCAD_ACO = B.ULTIMO_ACORDO
WHERE L.NOME_PES IS NOT NULL AND L.PAGAM_PAG < 2
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: LAYOUT FINAL ATRIBUINDO A PROPRIEDADE DO ACORDO COM CALCULO DE HO					*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
TRUNCATE TABLE TBL_DS_PAGAMENTOS_RIACHUELO
INSERT INTO TBL_DS_PAGAMENTOS_RIACHUELO
SELECT
		 IDEMP_CON
		,A.CGCPF_DEV
		,A.IDDEV_DEV
		,A.IDCON_CON
		,A.CONTR_CON
		,A.DTFAT_ATI
		,A.DTATR_CON
		,A.IDACO_ACO
		,A.IDPES_ACO
		,A.NOME_PES
		,A.ALCAD_PES
		,A.USUAR_PES
		,A.DTCAD_ACO
		,A.PAGAM_PAG
		,A.IDPAG_PAG
		,A.DTPAG_PAG
		,A.DTVEN_PAG
		,A.VLPAG_PAG
		,A.DESCR_BND
		,A.ATRASO
,CASE
		WHEN A.ATRASO BETWEEN 0 AND 4 THEN    0.095	WHEN A.ATRASO BETWEEN 5 AND 30 THEN 0.018
		WHEN A.ATRASO BETWEEN 31 AND 60 THEN   0.018  WHEN A.ATRASO BETWEEN 31 AND 60 THEN 0.135
		WHEN A.ATRASO BETWEEN 61 AND 90 THEN   0.065 WHEN A.ATRASO BETWEEN 91 AND 120 THEN 0.095
		WHEN A.ATRASO BETWEEN 121 AND 150 THEN 0.14 WHEN A.ATRASO BETWEEN 151 AND 180 THEN 0.15
		WHEN A.ATRASO BETWEEN 241 AND 270 THEN 0.24 WHEN A.ATRASO BETWEEN 271 AND 300 THEN 0.2640
		WHEN A.ATRASO BETWEEN 301 AND 330 THEN 0.28 WHEN A.ATRASO BETWEEN 331 AND 360 THEN 0.3080
		WHEN A.ATRASO BETWEEN 361 AND 720 THEN 0.3520 WHEN A.ATRASO BETWEEN 361 AND 720 THEN 0.37
		WHEN A.ATRASO BETWEEN 721 AND 1080 THEN 0.40 WHEN A.ATRASO BETWEEN 1081 AND 1440 THEN 0.44
ELSE
		0.45
END AS 'H.O%'
,CASE
	WHEN A.ATRASO BETWEEN -9999 AND 4	 THEN  A.VLPAG_PAG * 0.095  WHEN A.ATRASO BETWEEN 5 AND 30     THEN A.VLPAG_PAG * 0.018
	WHEN A.ATRASO BETWEEN 31    AND 60	 THEN  A.VLPAG_PAG * 0.018  WHEN A.ATRASO BETWEEN 31 AND 60    THEN A.VLPAG_PAG * 0.135
	WHEN A.ATRASO BETWEEN 61    AND 90	 THEN  A.VLPAG_PAG * 0.065  WHEN A.ATRASO BETWEEN 91 AND 120   THEN A.VLPAG_PAG * 0.095
	WHEN A.ATRASO BETWEEN 121   AND 150  THEN  A.VLPAG_PAG * 0.14   WHEN A.ATRASO BETWEEN 151 AND 180  THEN A.VLPAG_PAG * 0.15
	WHEN A.ATRASO BETWEEN 241   AND 270  THEN  A.VLPAG_PAG * 0.24   WHEN A.ATRASO BETWEEN 271 AND 300  THEN A.VLPAG_PAG * 0.2640
	WHEN A.ATRASO BETWEEN 301   AND 330  THEN  A.VLPAG_PAG * 0.28   WHEN A.ATRASO BETWEEN 331 AND 360  THEN A.VLPAG_PAG * 0.3080
	WHEN A.ATRASO BETWEEN 361   AND 720  THEN  A.VLPAG_PAG * 0.3520 WHEN A.ATRASO BETWEEN 721 AND 1080 THEN A.VLPAG_PAG * 0.40
	WHEN A.ATRASO BETWEEN 1081  AND 1440 THEN  A.VLPAG_PAG * 0.44
ELSE A.VLPAG_PAG * 0.45 END AS 'VLR_CALCULADO$'
FROM #P1 A