

DROP TABLE IF EXISTS #PAGAMENTOS
SELECT *
INTO #PAGAMENTOS
FROM OPENQUERY([10.251.1.36],'

Declare @vDiaAnterior DateTime	  = Convert(Date,Getdate()-1)
Declare @vDataInicial Varchar(40) = Concat(Convert(Date, @vDiaAnterior - DatePart(Day, @vDiaAnterior)+1),'' 00:00:00.000'')
Declare @vDataFinal   Varchar(40) = Concat(Convert(Date,Getdate()-1), '' 23:59:59.997'')

SELECT DISTINCT
	IDPAG_PAG
,	DATA_VENC  = CONVERT(DATE,DTVEN_PAG) 
,	DATA_PGTO  = CONVERT(DATE,DTPAG_PAG)     
,	VALOR_PAGO = CONVERT(MONEY,VLPAG_PAG)   
,	CGCPF_DEV  
,	IDCON_CON
,	TITUL_TRA  = ISNULL(T.TITUL_TRA, B.TITUL_BAI) 
,	VLFAT_TRA  = ISNULL(T.VLFAT_TRA, B.VLFAT_BAI) 
,	DTFAT_TRA  = CONVERT(DATE,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI))
,	RATING     = 
				CASE 
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN -9999  AND -1	THEN  ''00.A VENCER''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	0	  AND 14	THEN  ''01.0 A 14''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	15	  AND 30	THEN  ''02.15 A 30''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	31	  AND 64	THEN  ''03.31 A 64''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	65	  AND 90    THEN  ''04.65 A 90''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	91	  AND 120	THEN  ''05.91 A 120''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	121	  AND 180	THEN  ''06.121 A 180''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	181	  AND 360	THEN  ''07.181 A 360''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) > 360					THEN  ''08.> 360''
				    ELSE ''VERIFICAR''
				 END
FROM NECTAR.DBO.TB_CONTRATO		WITH( NOLOCK )
JOIN NECTAR.DBO.TB_ACORDO		WITH( NOLOCK ) ON IDCON_CON = IDCON_ACO
JOIN NECTAR.DBO.TB_PAGAMENTO	WITH( NOLOCK ) ON IDACO_ACO = IDACO_PAG 
JOIN NECTAR.DBO.TB_DEVEDOR		WITH( NOLOCK ) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN NECTAR.DBO.TB_PESSOAL	WITH( NOLOCK ) ON IDPES_ACO = IDPES_PES

OUTER APPLY ( 
			  SELECT IDCON_TRA ,IDDOC_TRA ,TITUL_TRA, DTFAT_TRA, VLFAT_TRA    
              FROM  [NECTAR].[DBO].TB_TRANSACAO WITH( NOLOCK )      
              WHERE IDCON_TRA = IDCON_CON  
			) T 
OUTER APPLY ( 
              SELECT IDCON_BAI,IDDOC_BAI,TITUL_BAI, DTFAT_BAI, VLFAT_BAI      
              FROM  [NECTAR].[DBO].TB_BAIXA     WITH( NOLOCK )      
              WHERE IDCON_CON = IDCON_BAI 
			) B 
WHERE IDEMP_CON = 29
AND DTPAG_PAG BETWEEN @vDataInicial AND @vDataFinal 
')

DROP TABLE IF EXISTS #VENCIMENTOS
SELECT *
INTO #VENCIMENTOS
FROM OPENQUERY([10.251.1.36],'

Declare @vDiaAnterior DateTime	  = Convert(Date,Getdate()-1)
Declare @vDataInicial Varchar(40) = Concat(Convert(Date, @vDiaAnterior - DatePart(Day, @vDiaAnterior)+1),'' 00:00:00.000'')
Declare @vDataFinal   Varchar(40) = Concat(Convert(Date,Getdate()-1), '' 23:59:59.997'')

SELECT DISTINCT
	IDPAG_PAG
,	DATA_VENC  = CONVERT(DATE,DTVEN_PAG) 
,	DATA_PGTO  = CONVERT(DATE,DTPAG_PAG)     
,	VALOR_PAGO = CONVERT(MONEY,VLPAG_PAG)   
,	CGCPF_DEV  
,	IDCON_CON
,	TITUL_TRA  = ISNULL(T.TITUL_TRA, B.TITUL_BAI) 
,	VLFAT_TRA  = ISNULL(T.VLFAT_TRA, B.VLFAT_BAI) 
,	DTFAT_TRA  = CONVERT(DATE,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI))
,	RATING     = 
				CASE 
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN -9999  AND -1	THEN  ''00.A VENCER''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	0	  AND 14	THEN  ''01.0 A 14''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	15	  AND 30	THEN  ''02.15 A 30''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	31	  AND 64	THEN  ''03.31 A 64''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	65	  AND 90    THEN  ''04.65 A 90''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	91	  AND 120	THEN  ''05.91 A 120''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	121	  AND 180	THEN  ''06.121 A 180''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) BETWEEN	181	  AND 360	THEN  ''07.181 A 360''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTCAD_ACO) > 360					THEN  ''08.> 360''
				    ELSE ''VERIFICAR''
				 END
FROM NECTAR.DBO.TB_CONTRATO		WITH( NOLOCK )
JOIN NECTAR.DBO.TB_ACORDO		WITH( NOLOCK ) ON IDCON_CON = IDCON_ACO
JOIN NECTAR.DBO.TB_PAGAMENTO	WITH( NOLOCK ) ON IDACO_ACO = IDACO_PAG 
JOIN NECTAR.DBO.TB_DEVEDOR		WITH( NOLOCK ) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN NECTAR.DBO.TB_PESSOAL	WITH( NOLOCK ) ON IDPES_ACO = IDPES_PES

OUTER APPLY ( 
			  SELECT IDCON_TRA ,IDDOC_TRA ,TITUL_TRA, DTFAT_TRA, VLFAT_TRA    
              FROM  [NECTAR].[DBO].TB_TRANSACAO WITH( NOLOCK )      
              WHERE IDCON_TRA = IDCON_CON  
			) T 
OUTER APPLY ( 
              SELECT IDCON_BAI,IDDOC_BAI,TITUL_BAI, DTFAT_BAI, VLFAT_BAI      
              FROM  [NECTAR].[DBO].TB_BAIXA     WITH( NOLOCK )      
              WHERE IDCON_CON = IDCON_BAI 
			) B 
WHERE IDEMP_CON = 29
AND DTVEN_PAG BETWEEN @vDataInicial AND @vDataFinal 
')

--> TABULAÇÃO
DROP TABLE IF EXISTS #BASE_64DIAS
SELECT *
INTO #BASE_64DIAS
FROM TB_DS_ANALITICO_HORA_HORA_SOUDI
WHERE AGING <= 64
AND ACORDO != 0
AND IDOCO_OCO = 2140

DROP TABLE IF EXISTS #INDIRETO
SELECT *
INTO #INDIRETO
FROM OPENQUERY([10.251.1.36],'

Declare @vDiaAnterior DateTime	  = Convert(Date,Getdate()-1)
Declare @vDataInicial Varchar(40) = Concat(Convert(Date, @vDiaAnterior - DatePart(Day, @vDiaAnterior)+1),'' 00:00:00.000'')
Declare @vDataFinal   Varchar(40) = Concat(Convert(Date,Getdate()-1), '' 23:59:59.997'')

SELECT DISTINCT 
	DTFAT_PGD
,	CGCPF_DEV
,	IDCON_CON
,	CONTR_CON
,	CONVERT(DATE,DTATR_CON) AS DTATR_CON
,	NOME_PES 
,	IDPGD_PGD
,	CONVERT(DATE,DTPAG_PGD)  AS DTPAG_PG
,	CONVERT(MONEY,VLPAG_PGD) AS VLPAG_PGD
,	TITUL_TRA  = ISNULL(T.TITUL_TRA, B.TITUL_BAI) 
,	VLFAT_TRA  = ISNULL(T.VLFAT_TRA, B.VLFAT_BAI) 
,	DTFAT_TRA  = CONVERT(DATE,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI))
,	RATING     = 
				CASE 
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN -9999  AND -1	THEN  ''00.A VENCER''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN	0	  AND 14	THEN  ''01.0 A 14''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN	15	  AND 30	THEN  ''02.15 A 30''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN	31	  AND 64	THEN  ''03.31 A 64''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN	65	  AND 90    THEN  ''04.65 A 90''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN	91	  AND 120	THEN  ''05.91 A 120''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN	121	  AND 180	THEN  ''06.121 A 180''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) BETWEEN	181	  AND 360	THEN  ''07.181 A 360''
					WHEN DATEDIFF(DAY,ISNULL(T.DTFAT_TRA, B.DTFAT_BAI), DTPAG_PGD) > 360					THEN  ''08.> 360''
				    ELSE ''VERIFICAR''
				 END
FROM	   NECTAR.DBO.TB_PAGDIRETO 	WITH( NOLOCK ) 
INNER JOIN NECTAR.DBO.TB_CONTRATO   WITH( NOLOCK ) ON IDCON_CON = IDCON_PGD
INNER JOIN NECTAR.DBO.TB_DEVEDOR    WITH( NOLOCK ) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN  NECTAR.DBO.TB_PESSOAL	WITH( NOLOCK ) ON IDPES_PES = IDPES_PGD
OUTER APPLY ( 
			  SELECT IDCON_TRA ,IDDOC_TRA ,TITUL_TRA, DTFAT_TRA, VLFAT_TRA    
              FROM  [NECTAR].[DBO].TB_TRANSACAO WITH( NOLOCK )      
              WHERE IDCON_TRA = IDCON_CON  
			) T 
OUTER APPLY ( 
              SELECT IDCON_BAI,IDDOC_BAI,TITUL_BAI, DTFAT_BAI, VLFAT_BAI      
              FROM  [NECTAR].[DBO].TB_BAIXA     WITH( NOLOCK )      
              WHERE IDCON_CON = IDCON_BAI 
			) B 
WHERE IDEMP_CON = 29
AND DTPAG_PGD BETWEEN @vDataInicial AND @vDataFinal 
')

DROP TABLE IF EXISTS #FINAL
SELECT 
	IDPGD_PGD
,	DATA_VENC  = ''
,	DATA_PGTO  = DTPAG_PG
,	VLPAG_PGD
,	CGCPF_DEV
,	IDCON_CON
,	TITUL_TRA
,	VLFAT_TRA
,	DTFAT_TRA
,	RATING
INTO #FINAL
FROM #INDIRETO Fato
WHERE EXISTS (
		      SELECT *
			  FROM #BASE_64DIAS Dim
			  WHERE Dim.IDCON_CON = Fato.IDCON_CON
			 )

UNION ALL

SELECT * FROM #PAGAMENTOS

UNION ALL

SELECT * FROM #VENCIMENTOS