

----> pagamentos sob acordo e espontaneos (pagamento direto)
SELECT * INTO #LANCAMENTOS FROM OPENQUERY ([10.251.1.36],
'DECLARE @HOJE DATETIME
SELECT @HOJE = CONVERT(DATETIME,''2022-05-01 00:00:00.000'',121)

SELECT DISTINCT 
 IDEMP_CON
,CGCPF_DEV
,IDDEV_DEV
,IDCON_CON
,CONTR_CON
,CONVERT(DATE,MIN(DTFAT_ATI)) AS DTFAT_ATI
,CONVERT(DATE,DTATR_CON) AS DTATR_CON
,IDACO_ACO
,IDPES_ACO
,NOME_PES
,ALCAD_PES
,USUAR_PES
,CONVERT(DATE,DTCAD_ACO) AS DTCAD_ACO
,PAGAM_PAG
,IDPAG_PAG
,CONVERT(DATE,DTPAG_PAG) AS DTPAG_PAG
,CONVERT(DATE,DTVEN_PAG) AS DTVEN_PAG
,CONVERT(MONEY,VLPAG_PAG) AS VLPAG_PAG
,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END DESCR_BND

FROM NECTAR.DBO.TB_PAGAMENTO WITH(NOLOCK)

INNER JOIN NECTAR.DBO.TB_ACORDO WITH(NOLOCK) ON IDACO_ACO = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_ACORDOTIT WITH(NOLOCK) ON IDACO_ATI = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = IDDOC_ATI
LEFT JOIN NECTAR.DBO.TB_PESSOAL WITH(NOLOCK) ON IDPES_PES = IDPES_ACO
INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_ACO
INNER JOIN NECTAR.DBO.TB_DEVEDOR WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN NECTAR.DBO.TB_BANDEIRA WITH(NOLOCK) ON IDBND_BND = IDBND_CON

WHERE DTPAG_PAG >= @HOJE AND IDEMP_CON IN (''17'')

GROUP BY  
 IDEMP_CON
,CGCPF_DEV
,IDDEV_DEV
,IDCON_CON
,CONTR_CON
,CONVERT(DATE,DTATR_CON)
,IDACO_ACO
,IDPES_ACO
,NOME_PES
,ALCAD_PES
,USUAR_PES
,CONVERT(DATE,DTCAD_ACO)
,PAGAM_PAG
,IDPAG_PAG
,CONVERT(DATE,DTPAG_PAG)
,CONVERT(DATE,DTVEN_PAG)
,CONVERT(MONEY,VLPAG_PAG)
,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END

UNION ALL

SELECT DISTINCT 
 IDEMP_CON
,CGCPF_DEV
,IDDEV_DEV
,IDCON_CON
,CONTR_CON
,CONVERT(DATE,MIN(DTFAT_PGD)) AS DTFAT_PGD
,CONVERT(DATE,DTATR_CON) AS DTATR_CON
,NULL AS IDACO_ACO
,NULL AS IDPES_ACO
,NULL AS NOME_PES
,NULL AS ALCAD_PES
,NULL AS USUAR_PES
,CONVERT(DATE,DTPAG_PGD) AS DTPAG_PGD
,1 AS PAGAM_PGD
,IDPGD_PGD
,CONVERT(DATE,DTPAG_PGD) AS DTPAG_PGD
,CONVERT(DATE,DTPAG_PGD) AS DTVEN_PGD
,CONVERT(MONEY,VLPAG_PGD) AS VLPAG_PGD
,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END DESCR_BND

FROM NECTAR.DBO.TB_PAGDIRETO WITH(NOLOCK)

INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_PGD
INNER JOIN NECTAR.DBO.TB_DEVEDOR WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN (
			SELECT DISTINCT IDCON_TRA,IDDOC_TRA FROM NECTAR.DBO.TB_TRANSACAO WITH(NOLOCK) INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_TRA AND IDEMP_CON IN (''3'',''5'',''6'')
			UNION ALL
			SELECT DISTINCT IDCON_BAI,IDDOC_BAI FROM NECTAR.DBO.TB_BAIXA WITH(NOLOCK) INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_BAI AND IDEMP_CON IN (''3'',''5'',''6'')			
		  )A ON IDCON_TRA = IDCON_PGD
LEFT JOIN NECTAR.DBO.TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = A.IDDOC_TRA
LEFT JOIN NECTAR.DBO.TB_BANDEIRA WITH(NOLOCK) ON IDBND_BND = IDBND_CON

WHERE DTPAG_PGD >= @HOJE AND IDEMP_CON IN (''17'')  

GROUP BY  
 IDEMP_CON
,CGCPF_DEV
,IDDEV_DEV
,IDCON_CON
,CONTR_CON
,CONVERT(DATE,DTATR_CON)
,IDPGD_PGD
,CONVERT(DATE,DTPAG_PGD)
,CONVERT(MONEY,VLPAG_PGD)
,CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END
')



---> tratamento de base para clusterizar produto/atraso
SELECT 
 A.*
,DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO)) AS ATRASO
,CASE 
      WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	1	   AND 30		THEN '0001 A 0030'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	31	   AND 60		THEN '0031 A 0060'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	61	   AND 90		THEN '0061 A 0090'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	91	   AND 120		THEN '0091 A 0120'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	121	   AND 180		THEN '0121 A 0180'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	181	   AND 240		THEN '0181 A 0240'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	241    AND 360		THEN '0241 A 0360' 
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	361    AND 720		THEN '0361 A 0720' 
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	721    AND 1080		THEN '0721 A 1080'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	1081   AND 1440		THEN '1081 A 1440'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	1441   AND 1800		THEN '1441 A 1800'
	  WHEN IDEMP_CON = '17' AND DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO))  BETWEEN	1801   AND 99999    THEN '1801 A 9999' END FAIXA 
,CASE 
	  WHEN IDEMP_CON = '17' AND DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				 THEN 'CBR'
	  WHEN IDEMP_CON = '17' AND DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI') THEN 'CCR'
	  WHEN IDEMP_CON = '17' AND DESCR_BND IN ('REPCFI','EPCFI')									 THEN 'EP'  END PRODUTO
,CASE WHEN IDACO_ACO IS NULL THEN 'ESPONTANEO' ELSE	'ACORDO' END ORIGEM
FROM #LANCAMENTOS A WHERE DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,DTCAD_ACO)) > 0



