


DROP TABLE IF EXISTS #TESTE
SELECT *
,	RW	=	ROW_NUMBER() OVER( PARTITION BY CPF ORDER BY ADMISSAO DESC)
INTO #TESTE
FROM OPERADORES

DELETE FROM #TESTE WHERE RW > 1
ALTER TABLE #TESTE DROP COLUMN RW


TRUNCATE TABLE OPERADORES
INSERT INTO OPERADORES
SELECT * FROM  #TESTE