
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*																								*/
/* PROGRAMADOR: KAIKE NATAN										                                */
/* VERSAO     : DATA: 04/05/2022																*/
/* DESCRICAO  : CONSULTA PARA REPROCESSAR FOTOGRÁFIA DO DIA DAS CARTEIRAS			 		    */
/*																								*/
/*        2. PROGRAMADOR: 													 DATA: __/__/____	*/		
/*           DESCRICAO  :										 								*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	VARIÁVEL DO CÓDIGO															    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
BEGIN TRANSACTION;
DECLARE @CONTADOR_INICIAL INT		=	 1;
DECLARE @ID_CARTEIRA	  INT		=	 20; 
DECLARE @CONTADOR_FINAL	  DATETIME	=	 '2022-07-04 00:00:00:000'--(SELECT CONCAT(MIN(CONVERT(DATE,DTAND_AND)),' 00:00:00:000') FROM [10.251.1.36].NECTAR.DBO.TB_ANDAMENTO WITH(NOLOCK) JOIN [10.251.1.36].NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_AND = IDCON_CON WHERE IDEMP_CON = @ID_CARTEIRA) 
DECLARE @DATA_FIM		  INT		=	 (SELECT DATEDIFF(DAY,CONVERT(DATE,@CONTADOR_FINAL),CONVERT(DATE,GETDATE())));
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: ESTRUTURA DO PADRÃO DA FOROGRAFIA DA CARTEIRA									    */
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
TRUNCATE TABLE #TESTE
WHILE ( @CONTADOR_INICIAL <= @DATA_FIM )
BEGIN
INSERT INTO #TESTE 
SELECT DISTINCT 
	EMPRESA						=			CASE WHEN IDEMP_CON = 20 THEN 'SOLFÁCIL' END 
,	CPF_CNPJ					=			CGCPF_DEV
,	NOME_DEVEDOR				=			NOME_DEV									 
,	ID_CONTRATO					=			IDCON_CON									 
,	CONTRATO					=			CONTR_CON	
,	DESCR_SIT 
,	DESCR_LOJ
,	DT_IMPORTACAO				=			CONVERT(DATE,DTINC_CON)						 
,	DT_DEVOLUCAO				=			CONVERT(DATE,DTDEV_CON)						 
,	DT_ATRASO					=			CONVERT(DATE,DTATR_CON)
,	DIAS_ATRASO					=			DATEDIFF(DAY,DTATR_CON,@CONTADOR_FINAL)		
,	SALDO						=			CONVERT(MONEY,VLSAL_CON)
,	VL_ATUALIZADO				=			CONVERT(MONEY,VLATU_CON)					 
,	RATING						=	
											CASE
												WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,@CONTADOR_FINAL)) BETWEEN -9999   AND -1	 THEN 'A VENCER'
												WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,@CONTADOR_FINAL)) BETWEEN	0	   AND 15	 THEN '0000 A 0015'
												WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,@CONTADOR_FINAL)) BETWEEN	16	   AND 30	 THEN '0016 A 0030'
												WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,@CONTADOR_FINAL)) BETWEEN	31	   AND 45	 THEN '0031 A 0045'
												WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,@CONTADOR_FINAL)) BETWEEN	46	   AND 60	 THEN '0046 A 0060'
												WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,@CONTADOR_FINAL)) BETWEEN	61	   AND 90	 THEN '0061 A 0090'
												WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,@CONTADOR_FINAL)) > 90						 THEN '>90' 
												ELSE 'VERIFICAR'
											END
,	DESCR_DOC AS PRODUTO
,	TB_SEGMENTACAO.DESCR_SEG AS SEGMENTACAO
,	ISNULL(SG.ELEGIVEL,1)    AS ELEGIBILIDADE
,	@CONTADOR_FINAL AS DT_INFO

FROM [10.251.1.36].NECTAR.DBO.TB_CONTRATO A
LEFT JOIN  (
			 SELECT DISTINCT IDCON_TRA,VLFAT_TRA,TITUL_TRA,DTFAT_TRA,IDDOC_TRA,CONTA_TRA 
			 FROM [10.251.1.36].NECTAR.DBO.TB_TRANSACAO WITH (NOLOCK)
			 INNER JOIN [10.251.1.36].NECTAR.DBO.TB_CONTRATO WITH (NOLOCK) ON IDCON_CON = IDCON_TRA AND IDEMP_CON = @ID_CARTEIRA
			 
			 UNION ALL 
			 
			 SELECT DISTINCT IDCON_BAI,VLFAT_BAI,TITUL_BAI,DTFAT_BAI,IDDOC_BAI,CONTA_BAI FROM [10.251.1.36].NECTAR.DBO.TB_BAIXA WITH (NOLOCK)
			 INNER JOIN [10.251.1.36].NECTAR.DBO.TB_CONTRATO WITH (NOLOCK) ON IDCON_CON = IDCON_BAI AND IDEMP_CON = @ID_CARTEIRA
			 WHERE IDCON_BAI NOT IN (
			 						 SELECT DISTINCT 
			 						 IDCON_TRA 
			 						 FROM [10.251.1.36].NECTAR.DBO.TB_TRANSACAO WITH (NOLOCK) 
			 						 INNER JOIN [10.251.1.36].NECTAR.DBO.TB_CONTRATO WITH (NOLOCK) ON IDCON_TRA = IDCON_CON AND IDEMP_CON = @ID_CARTEIRA
			 					    )			
			) B ON IDCON_TRA = IDCON_CON
LEFT JOIN [10.251.1.36].NECTAR.DBO.TB_DOCUMENTO			WITH(NOLOCK) ON IDDOC_DOC	 =	B.IDDOC_TRA
LEFT JOIN [10.251.1.36].NECTAR.DBO.TB_DEVEDOR			WITH(NOLOCK) ON IDDEV_CON    =  IDDEV_DEV
LEFT JOIN [10.251.1.36].NECTAR.DBO.TB_SITUACAO			WITH(NOLOCK) ON IDSIT_SIT	 =  IDSIT_CON
LEFT JOIN [10.251.1.36].NECTAR.DBO.TB_LOJA				WITH(NOLOCK) ON IDLOJ_CON	 =  IDLOJ_LOJ
LEFT JOIN [10.251.1.36].NECTAR.DBO.TB_SEGMENTACAO		WITH(NOLOCK) ON IDSEG_CON    =  IDSEG_SEG
LEFT JOIN [Data_Science].[DBO].[TB_DS_SEGMENTATIONS] SG	WITH(NOLOCK) ON SG.DESCR_SEG =  TB_SEGMENTACAO.DESCR_SEG AND SG.IDEMP = A.IDEMP_CON
WHERE 
	IDEMP_CON  = @ID_CARTEIRA
AND
	CASE WHEN STDEV_CON = 1 AND CONVERT(DATE,DTDEV_CON) >= CONVERT(DATE,@CONTADOR_FINAL) THEN 1 
		 WHEN STDEV_CON = 0 THEN 1 
		 WHEN IDSIT_SIT = 45 AND DTSIT_CON <= @CONTADOR_FINAL THEN 0
	END = 1
AND CONVERT(DATE,DTINC_CON) <= @CONTADOR_FINAL
AND DATEPART(DW,@CONTADOR_FINAL) NOT IN (7,1)

SET @CONTADOR_INICIAL = @CONTADOR_INICIAL + 1
SET @CONTADOR_FINAL   = @CONTADOR_FINAL   + 1

END
COMMIT TRANSACTION;

