

DROP TABLE IF EXISTS #BASE
SELECT *
,	RW	=	ROW_NUMBER() OVER(PARTITION BY CPF ORDER BY ATUALIZAÇÃO DESC)
INTO #BASE
FROM FUNCIONARIOS 

DELETE FROM #BASE WHERE RW > 1 
ALTER TABLE #BASE DROP COLUMN RW

SELECT 
		NOME
,		ADMISSÃO
,		DESLIGAMENTO
,		STATUS
,		CARGO
,		TEMPO_ATMA	 =	 IIF(DESLIGAMENTO IS NULL, DATEDIFF(DAY,ADMISSÃO,GETDATE()), DATEDIFF(DAY,ADMISSÃO,DESLIGAMENTO)) 
,		CUSTO_ETL	 =	
					CASE 
						WHEN CUSTO = 'MANUTENÇÃO PREDIAL'				THEN 'MANUTENÇÃO PREDIAL'
						WHEN CUSTO = 'CONTROL DESK'						THEN 'CONTROL DESK'
						WHEN CUSTO = 'COMUNICACAO'						THEN 'COMUNICACAO'
						WHEN CUSTO = 'REDES E INFRAESTRUTURA'			THEN 'TI'
						WHEN CUSTO = 'ORIGINAL'							THEN 'OPERACAO'
						WHEN CUSTO = 'PREVENTIVO'						THEN 'OPERACAO'
						WHEN CUSTO = 'SISTEMAS'							THEN 'SISTEMAS'
						WHEN CUSTO = 'GERENCIA FINANCEIRA'				THEN 'FINANCEIRO'
						WHEN CUSTO = 'PROJETOS'							THEN 'PROJETOS'
						WHEN CUSTO = 'TEXA'								THEN 'OPERACAO'
						WHEN CUSTO = 'GERENCIA SISTEMAS & PROJETOS'		THEN 'PROJETOS'
						WHEN CUSTO = 'PRA VALER'						THEN 'OPERACAO'
						WHEN CUSTO = 'GERENCIA DE PLANEJAMENTO'			THEN 'NPC'
						WHEN CUSTO = 'CAEDU'							THEN 'OPERACAO'
						WHEN CUSTO = 'QUALIDADE'						THEN 'QUALIDADE'
						WHEN CUSTO = 'RIACHUELO'						THEN 'OPERACAO'
						WHEN CUSTO = 'TREINAMENTO E DESENVOLVIMENTO'	THEN 'TREINAMENTO'
						WHEN CUSTO = 'GERENCIA DE GENTE E GESTÃO'		THEN 'RH'
						WHEN CUSTO = 'DIGITAL'							THEN 'OPERACAO'
						WHEN CUSTO = 'FINANCEIRO'						THEN 'FINANCEIRO'
						WHEN CUSTO = 'MENU'								THEN 'OPERACAO'
						WHEN CUSTO = 'DATA SCIENCE'						THEN 'DATA SCIENCE'
						WHEN CUSTO = 'COMPRAS'							THEN 'COMPRAS'
						WHEN CUSTO = 'VELOE'							THEN 'VELOE'
						WHEN CUSTO = 'PLANNING'							THEN 'NPC'
						WHEN CUSTO = 'RENNER'							THEN 'RENNER'
						ELSE 'ADICIONAR'
					END
FROM #BASE

