
--riachu
[dbo].[TB_DS_CALLFLEX_MES_RIACHUELO_JAN_2023]
[dbo].[TB_DS_CALLFLEX_MES_RIACHUELO_FEV_2023]

-- renner
[dbo].[TB_DS_CALLFLEX_MES_RENNER_JAN_2023]
[dbo].[TB_DS_CALLFLEX_MES_RENNER_FEV_2023]

--picpay
[dbo].[TB_DS_CALLFLEX_MES_PICPAY_JAN_2023]
[dbo].[TB_DS_CALLFLEX_MES_PICPAY_FEV_2023]

--mes
[dbo].[TB_DS_CALLFLEX_MES_JAN_2023]
[dbo].[TB_DS_CALLFLEX_MES_FEV_2023]