USE [Planning]
GO
/****** Object:  StoredProcedure [dbo].[PROC_MAILING_LAYOUT_RIACHUELO]    Script Date: 10/05/2022 10:54:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[PROC_MAILING_LAYOUT_RIACHUELO]

AS BEGIN


--- STEP 1: ULTIMA SAVE --- ATUALIZA 1 VEZ POR SEMANA ATRAVÉS DO JOB X, ETAPA 'TB_SAVE_RIACHUELO_ULTIMA'
IF OBJECT_ID('TEMPDB..#SAVE') IS NOT NULL DROP TABLE #SAVE
SELECT DISTINCT
A.*
INTO #SAVE  
FROM REPORTS.DBO.TB_SAVE_RIACHUELO_ULTIMA A WITH(NOLOCK)



--- STEP 2: ELEGER CARTEIRA ---
IF OBJECT_ID('TEMPDB..#RIACHUELOD0') IS NOT NULL DROP TABLE #RIACHUELOD0
SELECT * INTO #RIACHUELOD0 FROM OPENQUERY ([10.251.1.36],'
SELECT DISTINCT
 B.CGCPF_DEV
,NOME_DEV AS NOME
,B.GENERO_DEV
,DATEDIFF(YEAR,CONVERT(DATE,DTNAS_DEV),CONVERT(DATE,GETDATE())) AS IDADE
,ORGAO_DEV AS UF
,A.IDDEV_CON
,A.IDCON_CON
,IDEMP_CON
,IDCAR_CON
,SCORE_CON AS SCORE
,A.CONTR_CON
,A.VLSAL_CON AS VALOR_CAIXA
,A.VLATU_CON
,C.VLFAT_TRA
,DTATR_CON
,F.DESCR_SEG
,D.DESCR_SIT
,A.DTIMP_CON
,A.DTDEV_CON
,DESCR_BND

FROM NECTAR.DBO.TB_CONTRATO    A WITH (NOLOCK)
INNER JOIN NECTAR.DBO.TB_BANDEIRA    I WITH (NOLOCK) ON A.IDBND_CON = I.IDBND_BND
INNER JOIN NECTAR.DBO.TB_DEVEDOR     B WITH (NOLOCK) ON A.IDDEV_CON = B.IDDEV_DEV
INNER JOIN NECTAR.DBO.TB_TRANSACAO   C WITH (NOLOCK) ON A.IDCON_CON = C.IDCON_TRA AND C.TITUL_TRA <> ''SALDO A VENCER''
INNER JOIN NECTAR.DBO.TB_SITUACAO    D WITH (NOLOCK) ON A.IDSIT_CON = D.IDSIT_SIT
INNER JOIN NECTAR.DBO.TB_SEGMENTACAO F WITH (NOLOCK) ON A.IDSEG_CON = F.IDSEG_SEG

WHERE 
IDEMP_CON IN (''3'',''5'',''6'')
AND STDEV_CON = ''0''
AND IDSIT_CON NOT IN (''40'',''45'')
')





IF OBJECT_ID('TEMPDB..#PRE_CARTEIRA') IS NOT NULL DROP TABLE #PRE_CARTEIRA
SELECT 
 IDEMP_CON AS IDEMP
,CASE WHEN IDEMP_CON IN (3,5,6) THEN 'RIACHUELO'
	  WHEN IDEMP_CON = 4 THEN 'CAEDU'
	  WHEN IDEMP_CON IN (8,9) THEN 'ORIGINAL' 
	  WHEN IDEMP_CON = 13 THEN 'AMBEV' 
	  WHEN IDEMP_CON = 14 THEN 'CLARO' 
	  WHEN IDEMP_CON = 16 THEN 'PRAVALER' ELSE '-' END EMPRESA 
,IDCAR_CON AS IDCAR
,CASE WHEN IDEMP_CON IN (3,5,6) THEN 'RIACHUELO'
	  WHEN IDEMP_CON = 4 THEN 'CAEDU'
	  WHEN IDEMP_CON IN (8,9) THEN 'ORIGINAL' 
	  WHEN IDEMP_CON = 13 THEN 'AMBEV' 
	  WHEN IDEMP_CON = 14 THEN 'CLARO' 
	  WHEN IDEMP_CON = 16 THEN 'PRAVALER' ELSE '-' END CARTEIRA
,IDDEV_CON AS IDDEV
,NOME AS NOME_CLIENTE
,CGCPF_DEV AS CPF
,IDCON_CON AS ID_CONTRATO
,CONTR_CON AS CONTRATO
,DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) AS DIAS_ATRASO
,A.DESCR_SEG AS SEGMENTACAO
,DESCR_SIT AS SITUACAO
,DTIMP_CON AS DATA_DE_INCLUSAO
,DTDEV_CON AS DATA_DE_DEVOLUCAO
,CASE 
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) < 0 THEN 'A VENCER'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) BETWEEN 1 AND 30 THEN 'RUBI'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) BETWEEN 31 AND 90 THEN 'SAFIRA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) BETWEEN 91 AND 180 THEN 'ESMERALDA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) BETWEEN 181 AND 270 THEN 'DIAMANTE'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) BETWEEN 271 AND 360 THEN 'PLATINA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) BETWEEN 361 AND 1080 THEN 'OURO'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) BETWEEN 1081 AND 1800 THEN 'PRATA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),EOMONTH(GETDATE()-28)) > 1800 THEN 'BRONZE' ELSE 'ND' END LIGA_RK
,CASE
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 6 AND 15       THEN 'A'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 16 AND 30      THEN 'B'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 31 AND 60      THEN 'C'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 61 AND 90      THEN 'D'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 91 AND 120     THEN 'E'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 121 AND 150    THEN 'F'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 151 AND 180    THEN 'G'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 181 AND 210    THEN 'H'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 211 AND 240    THEN 'I'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 241 AND 270    THEN 'J'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 271 AND 300    THEN 'K'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 301 AND 330    THEN 'L'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 331 AND 360    THEN 'M'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 361 AND 720    THEN 'N'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 721 AND 1080   THEN 'O'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 1081 AND 1440  THEN 'P'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 1441 AND 1800  THEN 'Q'
      WHEN DATEDIFF(DAY,DTATR_CON,EOMONTH(GETDATE()-28)) BETWEEN 1801 AND 99999 THEN 'R' ELSE 'A VENCER' END RATING_RK
,CASE 
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) < 0 THEN 'A VENCER'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1 AND 30 THEN 'RUBI'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 31 AND 90 THEN 'SAFIRA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 91 AND 180 THEN 'ESMERALDA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 181 AND 270 THEN 'DIAMANTE'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 271 AND 360 THEN 'PLATINA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 361 AND 1080 THEN 'OURO'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1081 AND 1800 THEN 'PRATA'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) > 1800 THEN 'BRONZE' ELSE 'ND' END LIGA
,CASE
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 6 AND 15       THEN 'A'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 16 AND 30      THEN 'B'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 31 AND 60      THEN 'C'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 61 AND 90      THEN 'D'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 91 AND 120     THEN 'E'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 121 AND 150    THEN 'F'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 151 AND 180    THEN 'G'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 181 AND 210    THEN 'H'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 211 AND 240    THEN 'I'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 241 AND 270    THEN 'J'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 271 AND 300    THEN 'K'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 301 AND 330    THEN 'L'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 331 AND 360    THEN 'M'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 361 AND 720    THEN 'N'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 721 AND 1080   THEN 'O'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1081 AND 1440  THEN 'P'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1441 AND 1800  THEN 'Q'
      WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1801 AND 99999 THEN 'R' ELSE 'A VENCER' END RATING
,'' IMAPS -- PENDENTE
,'' [DESCRICAO ANDAMENTO] -- PENDENTE
,CONVERT(NUMERIC,VLATU_CON) VALOR_ATUALIZADO
,CONVERT(NUMERIC,SALDO_CONTABIL) VALOR_CONTABIL
,CONVERT(NUMERIC,VALOR_CAIXA) VALOR_SALDO
,CONVERT(NUMERIC,VLFAT_TRA) VALOR_FATURA
,CASE
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) < 31 THEN 'ALTO' 
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 31 AND 60 AND SCORE BETWEEN 361 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 31 AND 60 AND SCORE BETWEEN 1 AND 285 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 31 AND 60 AND SCORE BETWEEN 286 AND 360 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 61 AND 90 AND SCORE BETWEEN 496 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 61 AND 90 AND SCORE BETWEEN 1 AND 415 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 61 AND 90 AND SCORE BETWEEN 416 AND 495 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 91 AND 120 AND SCORE BETWEEN 791 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 91 AND 120 AND SCORE BETWEEN 1 AND 690 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 91 AND 120 AND SCORE BETWEEN 691 AND 790 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 121 AND 150 AND SCORE BETWEEN 751 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 121 AND 150 AND SCORE BETWEEN 1 AND 660 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 121 AND 150 AND SCORE BETWEEN 661 AND 750 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 151 AND 180 AND SCORE BETWEEN 721 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 151 AND 180 AND SCORE BETWEEN 1 AND 640 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 151 AND 180 AND SCORE BETWEEN 641 AND 720 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 181 AND 210 AND SCORE BETWEEN 691 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 181 AND 210 AND SCORE BETWEEN 1 AND 600 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 181 AND 210 AND SCORE BETWEEN 601 AND 690 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 211 AND 240 AND SCORE BETWEEN 691 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 211 AND 240 AND SCORE BETWEEN 1 AND 600 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 211 AND 240 AND SCORE BETWEEN 601 AND 690 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 241 AND 270 AND SCORE BETWEEN 661 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 241 AND 270 AND SCORE BETWEEN 1 AND 575 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 241 AND 270 AND SCORE BETWEEN 576 AND 660 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 271 AND 300 AND SCORE BETWEEN 661 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 271 AND 300 AND SCORE BETWEEN 1 AND 575 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 271 AND 300 AND SCORE BETWEEN 576 AND 660 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 301 AND 330 AND SCORE BETWEEN 661 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 301 AND 330 AND SCORE BETWEEN 1 AND 575 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 301 AND 330 AND SCORE BETWEEN 576 AND 660 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 331 AND 360 AND SCORE BETWEEN 661 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 331 AND 360 AND SCORE BETWEEN 1 AND 575 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 331 AND 360 AND SCORE BETWEEN 576 AND 660 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 361 AND 720 AND SCORE BETWEEN 631 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 361 AND 720 AND SCORE BETWEEN 1 AND 520 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 361 AND 720 AND SCORE BETWEEN 521 AND 630 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 721 AND 1080 AND SCORE BETWEEN 671 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 721 AND 1080 AND SCORE BETWEEN 1 AND 550 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 721 AND 1080 AND SCORE BETWEEN 551 AND 670 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1081 AND 1440 AND SCORE BETWEEN 601 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1081 AND 1440 AND SCORE BETWEEN 1 AND 450 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1081 AND 1440 AND SCORE BETWEEN 451 AND 600 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1441 AND 1800 AND SCORE BETWEEN 581 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1441 AND 1800 AND SCORE BETWEEN 1 AND 400 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1441 AND 1800 AND SCORE BETWEEN 401 AND 580 THEN 'MEDIO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1801 AND 9999 AND SCORE BETWEEN 521 AND 1000 THEN 'ALTO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1801 AND 9999 AND SCORE BETWEEN 1 AND 360 THEN 'BAIXO'
	  WHEN DATEDIFF(DAY,CONVERT(DATE,DTATR_CON),CONVERT(DATE,GETDATE())) BETWEEN 1801 AND 9999 AND SCORE BETWEEN 361 AND 520 THEN 'MEDIO' ELSE 'SEM SCORE'END [CLUSTER_SCORAGEM]
,SCORE
,CASE WHEN GENERO_DEV = 2 THEN 'FEMININO'
	  WHEN GENERO_DEV = 1 THEN 'MASCULINO' ELSE 'NAO INFORMADO' END SEXO
,IDADE
,UF
,0 AS [ACORDO_EXISTENTE] -- PENDENTE
,0 AS [ACORDOS QUEBRADOS] -- PENDENTE
,0 AS [SMS_D1] -- PENDENTE
,0 AS [EMAIL_D1] -- PENDENTE
,0 AS [SMS_D5] -- PENDENTE
,0 AS [EMAIL_D5] -- PENDENTE
,DESCR_BND AS PRODUTO	
		INTO #PRE_CARTEIRA
	FROM #RIACHUELOD0 A
LEFT JOIN #SAVE ON CHAVE_CYBER = CONTR_CON
LEFT JOIN [DATA_SCIENCE].[DBO].[TB_DS_SEGMENTATIONS] G WITH (NOLOCK) ON A.DESCR_SEG = G.DESCR_SEG AND G.IDEMP = A.IDEMP_CON
	WHERE ISNULL(ELEGIVEL,1) = 1
          



IF OBJECT_ID('TEMPDB..#CARTEIRA') IS NOT NULL DROP TABLE #CARTEIRA
SELECT DISTINCT A.*
,CASE WHEN  A.LIGA_RK = 'BRONZE' THEN NULL
	  WHEN A.DIAS_ATRASO > C.FIM THEN DATEADD(DAY,((C.FIM+1)-A.DIAS_ATRASO),CONVERT(DATE,GETDATE())) ELSE DATEADD(DAY,((C.FIM+1)-A.DIAS_ATRASO),CONVERT(DATE,GETDATE())) END DATA_ROLAGEM
,CASE WHEN  A.LIGA_RK = 'BRONZE' THEN 0
	  WHEN A.DIAS_ATRASO > C.FIM THEN 1 ELSE 0 END [ROLAGEM_RATING]
,CASE WHEN  A.LIGA_RK = 'BRONZE' THEN 0
   	  WHEN A.DIAS_ATRASO > B.ATE THEN 1 ELSE 0 END [ROLAGEM_LIGA] INTO #CARTEIRA
FROM #PRE_CARTEIRA A
LEFT JOIN DATA_SCIENCE..TB_DS_LIGA B ON A.LIGA_RK = B.LIGA 
LEFT JOIN DATA_SCIENCE..TB_DS_RATING C ON  A.RATING_RK = C.RATING 
WHERE A.DIAS_ATRASO > 30
AND CASE WHEN A.LIGA = 'BRONZE' AND A.VALOR_CONTABIL >= 50 THEN 1
	     WHEN A.LIGA = 'DIAMANTE' AND A.VALOR_CONTABIL >= 50 THEN 1
		 WHEN A.LIGA = 'ESMERALDA' AND A.VALOR_CONTABIL >= 100 THEN 1
		 WHEN A.LIGA = 'OURO' AND A.VALOR_CONTABIL >= 50 THEN 1
		 WHEN A.LIGA = 'PLATINA' AND A.VALOR_CONTABIL >= 50 THEN 1
		 WHEN A.LIGA = 'PRATA' AND A.VALOR_CONTABIL >= 50 THEN 1
		 WHEN A.LIGA = 'SAFIRA' AND A.VALOR_CONTABIL >= 50 THEN 1 ELSE 0 END = 1 


--- STEP 3: HISTORICO PARA REGRA DE EXCLUSÃO ---
IF OBJECT_ID('TEMPDB..#EXCLUSAO') IS NOT NULL DROP TABLE #EXCLUSAO
SELECT * INTO #EXCLUSAO FROM OPENQUERY([10.251.1.36],' 

DECLARE @HOJE DATETIME
SELECT @HOJE = CONVERT(DATETIME,CONCAT(CONVERT(DATE,GETDATE()),'' 00:00:00.000''),121)

SELECT DISTINCT
 B.IDCON_CON
FROM NECTAR.DBO.TB_ANDAMENTO A WITH(NOLOCK)
JOIN NECTAR.DBO.TB_CONTRATO B WITH(NOLOCK) ON B.IDCON_CON = A.IDCON_AND
JOIN NECTAR.DBO.TB_OCORRENCIA C WITH(NOLOCK) ON C.IDOCO_OCO = A.IDOCO_AND
	WHERE IDEMP_CON IN (''3'',''5'',''6'')
          AND C.IMAPS_OCO IN (''CPC_N'',''CPC_P'',''ROBÔ CPC'',''ACORDO'',''PROMESSA'') 
		  AND A.DTAND_AND > @HOJE')




-- STEP 4: BUSCA A BASE EM COBRANÇA JÁ EXCLUINDO OS CONTRATOS DA BASE DE EXCLUSÃO--
IF OBJECT_ID ('TEMPDB.DBO.#BASE_COBRANCA') IS NOT NULL DROP TABLE #BASE_COBRANCA
SELECT DISTINCT A.* INTO #BASE_COBRANCA 
FROM #CARTEIRA A
LEFT JOIN #EXCLUSAO B ON B.IDCON_CON = A.ID_CONTRATO
WHERE 
B.IDCON_CON IS NULL



--STEP 5: BUSCA OS TELEFONES DA RIACHUELO --
IF OBJECT_ID ('tempdb.dbo.#TB_TELEFONE_RIACHUELO') IS NOT NULL DROP TABLE #TB_TELEFONE_RIACHUELO
SELECT DISTINCT 
 A.CPF
,A.TPTEL_TEL
,CASE WHEN A.TPTEL_TEL = 0 THEN 'RESIDENCIAL'
	  WHEN A.TPTEL_TEL = 1 THEN 'COMERCIAL' 
	  WHEN A.TPTEL_TEL = 2 THEN 'CELULAR' ELSE 'OUTROS' END DESCR_TEL
,A.TELEFONE
,A.QUALIF
,A.PRIORIDADE
	INTO #TB_TELEFONE_RIACHUELO
		FROM [REPORTS].[DBO].[TB_TELEFONE_ATMA] A
			INNER JOIN #BASE_COBRANCA B ON B.CPF = A.CPF
			WHERE A.TPTEL_TEL IN (0,2) ---> FILTRA OS TIPOS DE TELEFONE ** 0 = RESIDENCIAL , 1 = COMERCIAL , 2 = CELULAR **



--STEP 6: UNE COM A BASE DE COBRANÇA--
IF OBJECT_ID('TEMPDB..#BASE_RIACHUELO') IS NOT NULL DROP TABLE #BASE_RIACHUELO
SELECT DISTINCT A.*, B.TELEFONE, B.QUALIF, B.PRIORIDADE, B.DESCR_TEL
INTO #BASE_RIACHUELO 
FROM #BASE_COBRANCA A      
JOIN #TB_TELEFONE_RIACHUELO B ON A.CPF = B.CPF



----------------------------------------------------------------- PROCESSA MAILING -----------------------------------------------------------------


--> STEP 1:  PRÉ MAILING <--
IF OBJECT_ID('TEMPDB..#PRE_MAILING') IS NOT NULL DROP TABLE #PRE_MAILING
SELECT DISTINCT 
 CONVERT(DATE,GETDATE()) AS DATA_DE_IMPORTACAO_MAILLING
,LEFT(CONVERT(TIME,GETDATE(),108),8) AS HORA_DA_INCLUSAO_MAILING
,'' IDSRV
,IDEMP
,EMPRESA
,IDCAR
,CARTEIRA
,IDDEV
,NOME_CLIENTE
,CPF
,ID_CONTRATO
,CONTRATO
,DIAS_ATRASO
,SEGMENTACAO
,SITUACAO
,DATA_DE_INCLUSAO
,DATA_DE_DEVOLUCAO
,DATA_ROLAGEM AS ENQUADRAMENTO
,LIGA AS CLASSE
,IMAPS AS MERCADORIA
,VALOR_CONTABIL AS VALOR_PRINCIPAL
,VALOR_ATUALIZADO
,[DESCRICAO ANDAMENTO] AS REFERENCIA
,VALOR_SALDO AS BANDEIRA
,VALOR_FATURA AS LOJA_AGENCIA
,ROLAGEM_RATING AS PROFISSAO
,ROLAGEM_LIGA AS TIPO_DE_PESSOA
,CLUSTER_SCORAGEM AS SCORE
,SCORE AS PONTUACAO_SCORE
,SEXO AS SCORE_CREDOR
,IDADE AS COMPORTAMENTO
,UPPER(UF) AS PROBABILIDADE
,CASE WHEN PRIORIDADE = 1 THEN LEFT(TELEFONE,2) END DDD1
,CASE WHEN PRIORIDADE = 1 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE1
,CASE WHEN PRIORIDADE = 1 THEN 1 END STATUS1
,CASE WHEN PRIORIDADE = 1 THEN QUALIF END PREFERENCIAL1
,'' AS DATA_ATUALIZACAO1
,CASE WHEN PRIORIDADE = 1 THEN 1 END QUALIFICACAO1
,'' AS ORIGEM1
,CASE WHEN PRIORIDADE = 1 THEN DESCR_TEL END TIPO1
,CASE WHEN PRIORIDADE = 2 THEN LEFT(TELEFONE,2) END DDD2
,CASE WHEN PRIORIDADE = 2 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE2
,CASE WHEN PRIORIDADE = 2 THEN 1 END STATUS2
,CASE WHEN PRIORIDADE = 2 THEN QUALIF END PREFERENCIAL2
,'' AS DATA_ATUALIZACAO2
,CASE WHEN PRIORIDADE = 2 THEN 2 END QUALIFICACAO2
,'' AS ORIGEM2
,CASE WHEN PRIORIDADE = 2 THEN DESCR_TEL END TIPO2
,CASE WHEN PRIORIDADE = 3 THEN LEFT(TELEFONE,2) END DDD3
,CASE WHEN PRIORIDADE = 3 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE3
,CASE WHEN PRIORIDADE = 3 THEN 1 END STATUS3
,CASE WHEN PRIORIDADE = 3 THEN QUALIF END PREFERENCIAL3
,'' AS DATA_ATUALIZACAO3
,CASE WHEN PRIORIDADE = 3 THEN 2 END QUALIFICACAO3
,'' AS ORIGEM3
,CASE WHEN PRIORIDADE = 3 THEN DESCR_TEL END TIPO3
,CASE WHEN PRIORIDADE = 4 THEN LEFT(TELEFONE,2) END DDD4
,CASE WHEN PRIORIDADE = 4 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE4
,CASE WHEN PRIORIDADE = 4 THEN 1 END STATUS4
,CASE WHEN PRIORIDADE = 4 THEN QUALIF END PREFERENCIAL4
,'' AS DATA_ATUALIZACAO4
,CASE WHEN PRIORIDADE = 4 THEN 2 END QUALIFICACAO4
,'' AS ORIGEM4
,CASE WHEN PRIORIDADE = 4 THEN DESCR_TEL END TIPO4
,CASE WHEN PRIORIDADE = 5 THEN LEFT(TELEFONE,2) END DDD5
,CASE WHEN PRIORIDADE = 5 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE5
,CASE WHEN PRIORIDADE = 5 THEN 1 END STATUS5
,CASE WHEN PRIORIDADE = 5 THEN QUALIF END PREFERENCIAL5
,'' AS DATA_ATUALIZACAO5
,CASE WHEN PRIORIDADE = 5 THEN 2 END QUALIFICACAO5
,'' AS ORIGEM5
,CASE WHEN PRIORIDADE = 5 THEN DESCR_TEL END TIPO5
,CASE WHEN PRIORIDADE = 6 THEN LEFT(TELEFONE,2) END DDD6
,CASE WHEN PRIORIDADE = 6 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE6
,CASE WHEN PRIORIDADE = 6 THEN 1 END STATUS6
,CASE WHEN PRIORIDADE = 6 THEN QUALIF END PREFERENCIAL6
,'' AS DATA_ATUALIZACAO6
,CASE WHEN PRIORIDADE = 6 THEN 2 END QUALIFICACAO6
,'' AS ORIGEM6
,CASE WHEN PRIORIDADE = 6 THEN DESCR_TEL END TIPO6
,CASE WHEN PRIORIDADE = 7 THEN LEFT(TELEFONE,2) END DDD7
,CASE WHEN PRIORIDADE = 7 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE7
,CASE WHEN PRIORIDADE = 7 THEN 1 END STATUS7
,CASE WHEN PRIORIDADE = 7 THEN QUALIF END PREFERENCIAL7
,'' AS DATA_ATUALIZACAO7
,CASE WHEN PRIORIDADE = 7 THEN 2 END QUALIFICACAO7
,'' AS ORIGEM7
,CASE WHEN PRIORIDADE = 7 THEN DESCR_TEL END TIPO7
,CASE WHEN PRIORIDADE = 8 THEN LEFT(TELEFONE,2) END DDD8
,CASE WHEN PRIORIDADE = 8 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE8
,CASE WHEN PRIORIDADE = 8 THEN 1 END STATUS8
,CASE WHEN PRIORIDADE = 8 THEN QUALIF END PREFERENCIAL8
,'' AS DATA_ATUALIZACAO8
,CASE WHEN PRIORIDADE = 8 THEN 2 END QUALIFICACAO8
,'' AS ORIGEM8
,CASE WHEN PRIORIDADE = 8 THEN DESCR_TEL END TIPO8
,CASE WHEN PRIORIDADE = 9 THEN LEFT(TELEFONE,2) END DDD9
,CASE WHEN PRIORIDADE = 9 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE9
,CASE WHEN PRIORIDADE = 9 THEN 1 END STATUS9
,CASE WHEN PRIORIDADE = 9 THEN QUALIF END PREFERENCIAL9
,'' AS DATA_ATUALIZACAO9
,CASE WHEN PRIORIDADE = 9 THEN 2 END QUALIFICACAO9
,'' AS ORIGEM9
,CASE WHEN PRIORIDADE = 9 THEN DESCR_TEL END TIPO9
,CASE WHEN PRIORIDADE = 10 THEN LEFT(TELEFONE,2) END DDD10
,CASE WHEN PRIORIDADE = 10 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE10
,CASE WHEN PRIORIDADE = 10 THEN 1 END STATUS10
,CASE WHEN PRIORIDADE = 10 THEN QUALIF END PREFERENCIAL10
,'' AS DATA_ATUALIZACAO10
,CASE WHEN PRIORIDADE = 10 THEN 2 END QUALIFICACAO10
,'' AS ORIGEM10
,CASE WHEN PRIORIDADE = 10 THEN DESCR_TEL END TIPO10
,CASE WHEN PRIORIDADE = 11 THEN LEFT(TELEFONE,2) END DDD11
,CASE WHEN PRIORIDADE = 11 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE11
,CASE WHEN PRIORIDADE = 11 THEN 1 END STATUS11
,CASE WHEN PRIORIDADE = 11 THEN QUALIF END PREFERENCIAL11
,'' AS DATA_ATUALIZACAO11
,CASE WHEN PRIORIDADE = 11 THEN 2 END QUALIFICACAO11
,'' AS ORIGEM11
,CASE WHEN PRIORIDADE = 11 THEN DESCR_TEL END TIPO11
,CASE WHEN PRIORIDADE = 12 THEN LEFT(TELEFONE,2) END DDD12
,CASE WHEN PRIORIDADE = 12 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE12
,CASE WHEN PRIORIDADE = 12 THEN 1 END STATUS12
,CASE WHEN PRIORIDADE = 12 THEN QUALIF END PREFERENCIAL12
,'' AS DATA_ATUALIZACAO12
,CASE WHEN PRIORIDADE = 12 THEN 2 END QUALIFICACAO12
,'' AS ORIGEM12
,CASE WHEN PRIORIDADE = 12 THEN DESCR_TEL END TIPO12
,CASE WHEN PRIORIDADE = 13 THEN LEFT(TELEFONE,2) END DDD13
,CASE WHEN PRIORIDADE = 13 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE13
,CASE WHEN PRIORIDADE = 13 THEN 1 END STATUS13
,CASE WHEN PRIORIDADE = 13 THEN QUALIF END PREFERENCIAL13
,'' AS DATA_ATUALIZACAO13
,CASE WHEN PRIORIDADE = 13 THEN 2 END QUALIFICACAO13
,'' AS ORIGEM13
,CASE WHEN PRIORIDADE = 13 THEN DESCR_TEL END TIPO13
,CASE WHEN PRIORIDADE = 14 THEN LEFT(TELEFONE,2) END DDD14
,CASE WHEN PRIORIDADE = 14 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE14
,CASE WHEN PRIORIDADE = 14 THEN 1 END STATUS14
,CASE WHEN PRIORIDADE = 14 THEN QUALIF END PREFERENCIAL14
,'' AS DATA_ATUALIZACAO14
,CASE WHEN PRIORIDADE = 14 THEN 2 END QUALIFICACAO14
,'' AS ORIGEM14
,CASE WHEN PRIORIDADE = 14 THEN DESCR_TEL END TIPO14
,CASE WHEN PRIORIDADE = 15 THEN LEFT(TELEFONE,2) END DDD15
,CASE WHEN PRIORIDADE = 15 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE15
,CASE WHEN PRIORIDADE = 15 THEN 1 END STATUS15
,CASE WHEN PRIORIDADE = 15 THEN QUALIF END PREFERENCIAL15
,'' AS DATA_ATUALIZACAO15
,CASE WHEN PRIORIDADE = 15 THEN 2 END QUALIFICACAO15
,'' AS ORIGEM15
,CASE WHEN PRIORIDADE = 15 THEN DESCR_TEL END TIPO15
,CASE WHEN PRIORIDADE = 16 THEN LEFT(TELEFONE,2) END DDD16
,CASE WHEN PRIORIDADE = 16 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE16
,CASE WHEN PRIORIDADE = 16 THEN 1 END STATUS16
,CASE WHEN PRIORIDADE = 16 THEN QUALIF END PREFERENCIAL16
,'' AS DATA_ATUALIZACAO16
,CASE WHEN PRIORIDADE = 16 THEN 2 END QUALIFICACAO16
,'' AS ORIGEM16
,CASE WHEN PRIORIDADE = 16 THEN DESCR_TEL END TIPO16
,CASE WHEN PRIORIDADE = 17 THEN LEFT(TELEFONE,2) END DDD17
,CASE WHEN PRIORIDADE = 17 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE17
,CASE WHEN PRIORIDADE = 17 THEN 1 END STATUS17
,CASE WHEN PRIORIDADE = 17 THEN QUALIF END PREFERENCIAL17
,'' AS DATA_ATUALIZACAO17
,CASE WHEN PRIORIDADE = 17 THEN 2 END QUALIFICACAO17
,'' AS ORIGEM17
,CASE WHEN PRIORIDADE = 17 THEN DESCR_TEL END TIPO17
,CASE WHEN PRIORIDADE = 18 THEN LEFT(TELEFONE,2) END DDD18
,CASE WHEN PRIORIDADE = 18 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE18
,CASE WHEN PRIORIDADE = 18 THEN 1 END STATUS18
,CASE WHEN PRIORIDADE = 18 THEN QUALIF END PREFERENCIAL18
,'' AS DATA_ATUALIZACAO18
,CASE WHEN PRIORIDADE = 18 THEN 2 END QUALIFICACAO18
,'' AS ORIGEM18
,CASE WHEN PRIORIDADE = 18 THEN DESCR_TEL END TIPO18
,CASE WHEN PRIORIDADE = 19 THEN LEFT(TELEFONE,2) END DDD19
,CASE WHEN PRIORIDADE = 19 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE19
,CASE WHEN PRIORIDADE = 19 THEN 1 END STATUS19
,CASE WHEN PRIORIDADE = 19 THEN QUALIF END PREFERENCIAL19
,'' AS DATA_ATUALIZACAO19
,CASE WHEN PRIORIDADE = 19 THEN 2 END QUALIFICACAO19
,'' AS ORIGEM19
,CASE WHEN PRIORIDADE = 19 THEN DESCR_TEL END TIPO19
,CASE WHEN PRIORIDADE = 20 THEN LEFT(TELEFONE,2) END DDD20
,CASE WHEN PRIORIDADE = 20 THEN CONCAT(LEFT(TELEFONE,2),SUBSTRING(TELEFONE,3,100)) END TELEFONE20
,CASE WHEN PRIORIDADE = 20 THEN 1 END STATUS20
,CASE WHEN PRIORIDADE = 20 THEN QUALIF END PREFERENCIAL20
,'' AS DATA_ATUALIZACAO20
,CASE WHEN PRIORIDADE = 20 THEN 2 END QUALIFICACAO20
,'' AS ORIGEM20
,CASE WHEN PRIORIDADE = 20 THEN DESCR_TEL END TIPO20
,ACORDO_EXISTENTE AS COD_BARRAS
,[ACORDOS QUEBRADOS] AS DETALHAMENTO_FATURAS
,SMS_D1 AS PERCENT_DESCONTO
,EMAIL_D1 AS QNTD_PARCELAS
,SMS_D5 AS DETALHAMENTO_DESCONTO
,EMAIL_D5 AS DETALHAMENTO_PARCELAS
,PRODUTO AS CORINGA1
,'' AS CORINGA2
,'' AS CORINGA3
,'' AS CORINGA4
,'' AS CORINGA5
,'' AS CORINGA6
,'' AS CORINGA7
,'' AS CORINGA8
,'' AS CORINGA9
,'' AS CORINGA10
INTO #PRE_MAILING
FROM #BASE_RIACHUELO



--> STEP 2: MAILING <--
IF OBJECT_ID('TEMPDB..##FINAL_LAYOUT') IS NOT NULL DROP TABLE ##FINAL_LAYOUT
SELECT DISTINCT * INTO ##FINAL_LAYOUT FROM(
SELECT DISTINCT  
 CONVERT(VARCHAR,DATA_DE_IMPORTACAO_MAILLING) AS DATA_DE_IMPORTACAO_MAILLING
,CONVERT(VARCHAR,HORA_DA_INCLUSAO_MAILING) AS HORA_DA_INCLUSAO_MAILING
,IDSRV
,CONVERT(VARCHAR,IDEMP) AS IDEMP
,CONVERT(VARCHAR,EMPRESA) AS EMPRESA
,CONVERT(VARCHAR,IDCAR) AS IDCAR
,CONVERT(VARCHAR,CARTEIRA) AS CARTEIRA
,CONVERT(VARCHAR,IDDEV) AS IDDEV
,CONVERT(VARCHAR,NOME_CLIENTE) AS NOME_CLIENTE
,CONVERT(VARCHAR,CPF) AS CPF
,CONVERT(VARCHAR,ID_CONTRATO) AS ID_CONTRATO
,CONVERT(VARCHAR,CONTRATO) AS CONTRATO
,CONVERT(VARCHAR,DIAS_ATRASO) AS DIAS_ATRASO
,CONVERT(VARCHAR,SEGMENTACAO) AS SEGMENTACAO
,REPLACE(REPLACE(REPLACE(SITUACAO,'õ','o'),'ç','c'),'ã','a') as SITUACAO
,CONVERT(VARCHAR,CONVERT(DATE,DATA_DE_INCLUSAO)) AS DATA_DE_INCLUSAO
,CONVERT(VARCHAR,CONVERT(DATE,DATA_DE_DEVOLUCAO)) AS DATA_DE_DEVOLUCAO
,CONVERT(VARCHAR,ENQUADRAMENTO) AS ENQUADRAMENTO
,CONVERT(VARCHAR,CLASSE) AS CLASSE
,CONVERT(VARCHAR,MERCADORIA) AS MERCADORIA
,CONVERT(VARCHAR,VALOR_PRINCIPAL) AS VALOR_PRINCIPAL
,CONVERT(VARCHAR,VALOR_ATUALIZADO) AS VALOR_ATUALIZADO 
,CONVERT(VARCHAR,REFERENCIA) AS REFERENCIA
,CONVERT(VARCHAR,BANDEIRA) AS BANDEIRA
,MAX(CONVERT(VARCHAR,LOJA_AGENCIA)) AS LOJA_AGENCIA 
,CONVERT(VARCHAR,PROFISSAO) AS PROFISSAO
,CONVERT(VARCHAR,TIPO_DE_PESSOA) AS TIPO_DE_PESSOA
,CONVERT(VARCHAR,SCORE) AS SCORE
,CONVERT(VARCHAR,PONTUACAO_SCORE) AS PONTUACAO_SCORE
,CONVERT(VARCHAR,SCORE_CREDOR) AS SCORE_CREDOR
,CONVERT(VARCHAR,COMPORTAMENTO) AS COMPORTAMENTO
,CONVERT(VARCHAR,PROBABILIDADE) AS PROBABILIDADE
,MAX(ISNULL(DDD1,'')) AS DDD1
,MAX(ISNULL(TELEFONE1,'')) AS TELEFONE1
,MAX(ISNULL(CONVERT(VARCHAR,STATUS1),'')) AS STATUS1
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL1),'')) AS PREFERENCIAL1
,MAX(ISNULL(DATA_ATUALIZACAO1,'')) AS DATA_ATUALIZACAO1
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO1),'')) AS QUALIFICACAO1
,MAX(ISNULL(ORIGEM1,'')) AS ORIGEM1
,MAX(ISNULL(TIPO1,'')) AS TIPO1
,MAX(ISNULL(DDD2,'')) AS DDD2
,MAX(ISNULL(TELEFONE2,'')) AS TELEFONE2
,MAX(ISNULL(CONVERT(VARCHAR,STATUS2),'')) AS STATUS2
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL2),'')) AS PREFERENCIAL2
,MAX(ISNULL(DATA_ATUALIZACAO2,'')) AS DATA_ATUALIZACAO2
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO2),'')) AS QUALIFICACAO2
,MAX(ISNULL(ORIGEM2,'')) AS ORIGEM2
,MAX(ISNULL(TIPO2,'')) AS TIPO2
,MAX(ISNULL(DDD3,'')) AS DDD3
,MAX(ISNULL(TELEFONE3,'')) AS TELEFONE3
,MAX(ISNULL(CONVERT(VARCHAR,STATUS3),'')) AS STATUS3
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL3),'')) AS PREFERENCIAL3
,MAX(ISNULL(DATA_ATUALIZACAO3,'')) AS DATA_ATUALIZACAO3
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO3),'')) AS QUALIFICACAO3
,MAX(ISNULL(ORIGEM3,'')) AS ORIGEM3
,MAX(ISNULL(TIPO3,'')) AS TIPO3
,MAX(ISNULL(DDD4,'')) AS DDD4
,MAX(ISNULL(TELEFONE4,'')) AS TELEFONE4
,MAX(ISNULL(CONVERT(VARCHAR,STATUS4),'')) AS STATUS4
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL4),'')) AS PREFERENCIAL4
,MAX(ISNULL(DATA_ATUALIZACAO4,'')) AS DATA_ATUALIZACAO4
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO4),'')) AS QUALIFICACAO4
,MAX(ISNULL(ORIGEM4,'')) AS ORIGEM4
,MAX(ISNULL(TIPO4,'')) AS TIPO4
,MAX(ISNULL(DDD5,'')) AS DDD5
,MAX(ISNULL(TELEFONE5,'')) AS TELEFONE5
,MAX(ISNULL(CONVERT(VARCHAR,STATUS5),'')) AS STATUS5
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL5),'')) AS PREFERENCIAL5
,MAX(ISNULL(DATA_ATUALIZACAO5,'')) AS DATA_ATUALIZACAO5
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO5),'')) AS QUALIFICACAO5
,MAX(ISNULL(ORIGEM5,'')) AS ORIGEM5
,MAX(ISNULL(TIPO5,'')) AS TIPO5
,MAX(ISNULL(DDD6,'')) AS DDD6
,MAX(ISNULL(TELEFONE6,'')) AS TELEFONE6
,MAX(ISNULL(CONVERT(VARCHAR,STATUS6),'')) AS STATUS6
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL6),'')) AS PREFERENCIAL6
,MAX(ISNULL(DATA_ATUALIZACAO6,'')) AS DATA_ATUALIZACAO6
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO6),'')) AS QUALIFICACAO6
,MAX(ISNULL(ORIGEM6,'')) AS ORIGEM6
,MAX(ISNULL(TIPO6,'')) AS TIPO6
,MAX(ISNULL(DDD7,'')) AS DDD7
,MAX(ISNULL(TELEFONE7,'')) AS TELEFONE7
,MAX(ISNULL(CONVERT(VARCHAR,STATUS7),'')) AS STATUS7
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL7),'')) AS PREFERENCIAL7
,MAX(ISNULL(DATA_ATUALIZACAO7,'')) AS DATA_ATUALIZACAO7
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO7),'')) AS QUALIFICACAO7
,MAX(ISNULL(ORIGEM7,'')) AS ORIGEM7
,MAX(ISNULL(TIPO7,'')) AS TIPO7
,MAX(ISNULL(DDD8,'')) AS DDD8
,MAX(ISNULL(TELEFONE8,'')) AS TELEFONE8
,MAX(ISNULL(CONVERT(VARCHAR,STATUS8),'')) AS STATUS8
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL8),'')) AS PREFERENCIAL8
,MAX(ISNULL(DATA_ATUALIZACAO8,'')) AS DATA_ATUALIZACAO8
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO8),'')) AS QUALIFICACAO8
,MAX(ISNULL(ORIGEM8,'')) AS ORIGEM8
,MAX(ISNULL(TIPO8,'')) AS TIPO8
,MAX(ISNULL(DDD9,'')) AS DDD9
,MAX(ISNULL(TELEFONE9,'')) AS TELEFONE9
,MAX(ISNULL(CONVERT(VARCHAR,STATUS9),'')) AS STATUS9
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL9),'')) AS PREFERENCIAL9
,MAX(ISNULL(DATA_ATUALIZACAO9,'')) AS DATA_ATUALIZACAO9
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO9),'')) AS QUALIFICACAO9
,MAX(ISNULL(ORIGEM9,'')) AS ORIGEM9
,MAX(ISNULL(TIPO9,'')) AS TIPO9
,MAX(ISNULL(DDD10,'')) AS DDD10
,MAX(ISNULL(TELEFONE10,'')) AS TELEFONE10
,MAX(ISNULL(CONVERT(VARCHAR,STATUS10),'')) AS STATUS10
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL10),'')) AS PREFERENCIAL10
,MAX(ISNULL(DATA_ATUALIZACAO10,'')) AS DATA_ATUALIZACAO10
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO10),'')) AS QUALIFICACAO10
,MAX(ISNULL(ORIGEM10,'')) AS ORIGEM10
,MAX(ISNULL(TIPO10,'')) AS TIPO10
,MAX(ISNULL(DDD11,'')) AS DDD11
,MAX(ISNULL(TELEFONE11,'')) AS TELEFONE11
,MAX(ISNULL(CONVERT(VARCHAR,STATUS11),'')) AS STATUS11
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL11),'')) AS PREFERENCIAL11
,MAX(ISNULL(DATA_ATUALIZACAO11,'')) AS DATA_ATUALIZACAO11
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO11),'')) AS QUALIFICACAO11
,MAX(ISNULL(ORIGEM11,'')) AS ORIGEM11
,MAX(ISNULL(TIPO11,'')) AS TIPO11
,MAX(ISNULL(DDD12,'')) AS DDD12
,MAX(ISNULL(TELEFONE12,'')) AS TELEFONE12
,MAX(ISNULL(CONVERT(VARCHAR,STATUS12),'')) AS STATUS12
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL12),'')) AS PREFERENCIAL12
,MAX(ISNULL(DATA_ATUALIZACAO12,'')) AS DATA_ATUALIZACAO12
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO12),'')) AS QUALIFICACAO12
,MAX(ISNULL(ORIGEM12,'')) AS ORIGEM12
,MAX(ISNULL(TIPO12,'')) AS TIPO12
,MAX(ISNULL(DDD13,'')) AS DDD13
,MAX(ISNULL(TELEFONE13,'')) AS TELEFONE13
,MAX(ISNULL(CONVERT(VARCHAR,STATUS13),'')) AS STATUS13
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL13),'')) AS PREFERENCIAL13
,MAX(ISNULL(DATA_ATUALIZACAO13,'')) AS DATA_ATUALIZACAO13
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO13),'')) AS QUALIFICACAO13
,MAX(ISNULL(ORIGEM13,'')) AS ORIGEM13
,MAX(ISNULL(TIPO13,'')) AS TIPO13
,MAX(ISNULL(DDD14,'')) AS DDD14
,MAX(ISNULL(TELEFONE14,'')) AS TELEFONE14
,MAX(ISNULL(CONVERT(VARCHAR,STATUS14),'')) AS STATUS14
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL14),'')) AS PREFERENCIAL14
,MAX(ISNULL(DATA_ATUALIZACAO14,'')) AS DATA_ATUALIZACAO14
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO14),'')) AS QUALIFICACAO14
,MAX(ISNULL(ORIGEM14,'')) AS ORIGEM14
,MAX(ISNULL(TIPO14,'')) AS TIPO14
,MAX(ISNULL(DDD15,'')) AS DDD15
,MAX(ISNULL(TELEFONE15,'')) AS TELEFONE15
,MAX(ISNULL(CONVERT(VARCHAR,STATUS15),'')) AS STATUS15
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL15),'')) AS PREFERENCIAL15
,MAX(ISNULL(DATA_ATUALIZACAO15,'')) AS DATA_ATUALIZACAO15
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO15),'')) AS QUALIFICACAO15
,MAX(ISNULL(ORIGEM15,'')) AS ORIGEM15
,MAX(ISNULL(TIPO15,'')) AS TIPO15
,MAX(ISNULL(DDD16,'')) AS DDD16
,MAX(ISNULL(TELEFONE16,'')) AS TELEFONE16
,MAX(ISNULL(CONVERT(VARCHAR,STATUS16),'')) AS STATUS16
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL16),'')) AS PREFERENCIAL16
,MAX(ISNULL(DATA_ATUALIZACAO16,'')) AS DATA_ATUALIZACAO16
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO16),'')) AS QUALIFICACAO16
,MAX(ISNULL(ORIGEM16,'')) AS ORIGEM16
,MAX(ISNULL(TIPO16,'')) AS TIPO16
,MAX(ISNULL(DDD17,'')) AS DDD17
,MAX(ISNULL(TELEFONE17,'')) AS TELEFONE17
,MAX(ISNULL(CONVERT(VARCHAR,STATUS17),'')) AS STATUS17
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL17),'')) AS PREFERENCIAL17
,MAX(ISNULL(DATA_ATUALIZACAO17,'')) AS DATA_ATUALIZACAO17
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO17),'')) AS QUALIFICACAO17
,MAX(ISNULL(ORIGEM17,'')) AS ORIGEM17
,MAX(ISNULL(TIPO17,'')) AS TIPO17
,MAX(ISNULL(DDD18,'')) AS DDD18
,MAX(ISNULL(TELEFONE18,'')) AS TELEFONE18
,MAX(ISNULL(CONVERT(VARCHAR,STATUS18),'')) AS STATUS18
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL18),'')) AS PREFERENCIAL18
,MAX(ISNULL(DATA_ATUALIZACAO18,'')) AS DATA_ATUALIZACAO18
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO18),'')) AS QUALIFICACAO18
,MAX(ISNULL(ORIGEM18,'')) AS ORIGEM18
,MAX(ISNULL(TIPO18,'')) AS TIPO18
,MAX(ISNULL(DDD19,'')) AS DDD19
,MAX(ISNULL(TELEFONE19,'')) AS TELEFONE19
,MAX(ISNULL(CONVERT(VARCHAR,STATUS19),'')) AS STATUS19
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL19),'')) AS PREFERENCIAL19
,MAX(ISNULL(DATA_ATUALIZACAO19,'')) AS DATA_ATUALIZACAO19
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO19),'')) AS QUALIFICACAO19
,MAX(ISNULL(ORIGEM19,'')) AS ORIGEM19
,MAX(ISNULL(TIPO19,'')) AS TIPO19
,MAX(ISNULL(DDD20,'')) AS DDD20
,MAX(ISNULL(TELEFONE20,'')) AS TELEFONE20
,MAX(ISNULL(CONVERT(VARCHAR,STATUS20),'')) AS STATUS20
,MAX(ISNULL(CONVERT(VARCHAR,PREFERENCIAL20),'')) AS PREFERENCIAL20
,MAX(ISNULL(DATA_ATUALIZACAO20,'')) AS DATA_ATUALIZACAO20
,MAX(ISNULL(CONVERT(VARCHAR,QUALIFICACAO20),'')) AS QUALIFICACAO20
,MAX(ISNULL(ORIGEM20,'')) AS ORIGEM20
,MAX(ISNULL(TIPO20,'')) AS TIPO20
,CONVERT(VARCHAR,COD_BARRAS) AS COD_BARRAS
,CONVERT(VARCHAR,DETALHAMENTO_FATURAS) AS DETALHAMENTO_FATURAS
,CONVERT(VARCHAR,PERCENT_DESCONTO) AS PERCENT_DESCONTO
,CONVERT(VARCHAR,QNTD_PARCELAS) AS QNTD_PARCELAS
,CONVERT(VARCHAR,DETALHAMENTO_DESCONTO) AS DETALHAMENTO_DESCONTO
,CONVERT(VARCHAR,DETALHAMENTO_PARCELAS) AS DETALHAMENTO_PARCELAS
,CONVERT(VARCHAR,CORINGA1) AS CORINGA1
,CONVERT(VARCHAR,CORINGA2) AS CORINGA2
,CONVERT(VARCHAR,CORINGA3) AS CORINGA3
,CONVERT(VARCHAR,CORINGA4) AS CORINGA4
,CONVERT(VARCHAR,CORINGA5) AS CORINGA5
,CONVERT(VARCHAR,CORINGA6) AS CORINGA6
,CONVERT(VARCHAR,CORINGA7) AS CORINGA7
,CONVERT(VARCHAR,CORINGA8) AS CORINGA8
,CONVERT(VARCHAR,CORINGA9) AS CORINGA9
,CONVERT(VARCHAR,CORINGA10) AS CORINGA10
	FROM #PRE_MAILING
GROUP BY 
 DATA_DE_IMPORTACAO_MAILLING
,HORA_DA_INCLUSAO_MAILING
,IDSRV
,IDEMP
,EMPRESA
,IDCAR
,CARTEIRA
,IDDEV
,NOME_CLIENTE
,CPF
,ID_CONTRATO
,CONTRATO
,DIAS_ATRASO
,SEGMENTACAO
,REPLACE(REPLACE(REPLACE(SITUACAO,'õ','o'),'ç','c'),'ã','a')
,DATA_DE_INCLUSAO
,DATA_DE_DEVOLUCAO
,ENQUADRAMENTO
,CLASSE
,MERCADORIA
,VALOR_PRINCIPAL
,VALOR_ATUALIZADO
,REFERENCIA
,BANDEIRA
,PROFISSAO
,TIPO_DE_PESSOA
,SCORE
,PONTUACAO_SCORE
,SCORE_CREDOR
,COMPORTAMENTO
,PROBABILIDADE
,COD_BARRAS
,DETALHAMENTO_FATURAS
,PERCENT_DESCONTO
,QNTD_PARCELAS
,DETALHAMENTO_DESCONTO
,DETALHAMENTO_PARCELAS
,CORINGA1
,CORINGA2
,CORINGA3
,CORINGA4
,CORINGA5
,CORINGA6
,CORINGA7
,CORINGA8
,CORINGA9
,CORINGA10

UNION ALL

SELECT 
 'DATA_DE_IMPORTACAO_MAILLING' AS DATA_DE_IMPORTACAO_MAILLING
,'HORA_DA_INCLUSAO_MAILING' AS HORA_DA_INCLUSAO_MAILING
,'IDSRV' AS IDSRV
,'IDEMP' AS IDEMP
,'EMPRESA' AS EMPRESA
,'IDCAR' AS IDCAR
,'CARTEIRA' AS CARTEIRA
,'IDDEV' AS IDDEV
,'NOME_CLIENTE' AS NOME_CLIENTE
,'CPF' AS CPF
,'ID_CONTRATO' AS ID_CONTRATO
,'CONTRATO' AS CONTRATO
,'DIAS_ATRASO' AS DIAS_ATRASO
,'SEGMENTACAO' AS SEGMENTACAO
,'SITUACAO' AS SITUACAO
,'DATA_DE_INCLUSAO' AS DATA_DE_INCLUSAO
,'DATA_DE_DEVOLUCAO' AS DATA_DE_DEVOLUCAO
,'ENQUADRAMENTO' AS ENQUADRAMENTO
,'CLASSE' AS CLASSE
,'MERCADORIA' AS MERCADORIA
,'VALOR_PRINCIPAL' AS VALOR_PRINCIPAL
,'VALOR_ATUALIZADO' AS VALOR_ATUALIZADO
,'REFERENCIA' AS REFERENCIA
,'BANDEIRA' AS BANDEIRA
,'LOJA_AGENCIA' AS LOJA_AGENCIA
,'PROFISSAO' AS PROFISSAO
,'TIPO_DE_PESSOA' AS TIPO_DE_PESSOA
,'SCORE' AS SCORE
,'PONTUACAO_SCORE' AS PONTUACAO_SCORE
,'SCORE_CREDOR' AS SCORE_CREDOR
,'COMPORTAMENTO' AS COMPORTAMENTO
,'PROBABILIDADE' AS PROBABILIDADE
,'DDD1' AS DDD1
,'TELEFONE1' AS TELEFONE1
,'STATUS1' AS STATUS1
,'PREFERENCIAL1' AS PREFERENCIAL1
,'DATA_ATUALIZACAO1' AS DATA_ATUALIZACAO1
,'QUALIFICACAO1' AS QUALIFICACAO1
,'ORIGEM1' AS ORIGEM1
,'TIPO1' AS TIPO1
,'DDD2' AS DDD2
,'TELEFONE2' AS TELEFONE2
,'STATUS2' AS STATUS2
,'PREFERENCIAL2' AS PREFERENCIAL2
,'DATA_ATUALIZACAO2' AS DATA_ATUALIZACAO2
,'QUALIFICACAO2' AS QUALIFICACAO2
,'ORIGEM2' AS ORIGEM2
,'TIPO2' AS TIPO2
,'DDD3' AS DDD3
,'TELEFONE3' AS TELEFONE3
,'STATUS3' AS STATUS3
,'PREFERENCIAL3' AS PREFERENCIAL3
,'DATA_ATUALIZACAO3' AS DATA_ATUALIZACAO3
,'QUALIFICACAO3' AS QUALIFICACAO3
,'ORIGEM3' AS ORIGEM3
,'TIPO3' AS TIPO3
,'DDD4' AS DDD4
,'TELEFONE4' AS TELEFONE4
,'STATUS4' AS STATUS4
,'PREFERENCIAL4' AS PREFERENCIAL4
,'DATA_ATUALIZACAO4' AS DATA_ATUALIZACAO4
,'QUALIFICACAO4' AS QUALIFICACAO4
,'ORIGEM4' AS ORIGEM4
,'TIPO4' AS TIPO4
,'DDD5' AS DDD5
,'TELEFONE5' AS TELEFONE5
,'STATUS5' AS STATUS5
,'PREFERENCIAL5' AS PREFERENCIAL5
,'DATA_ATUALIZACAO5' AS DATA_ATUALIZACAO5
,'QUALIFICACAO5' AS QUALIFICACAO5
,'ORIGEM5' AS ORIGEM5
,'TIPO5' AS TIPO5
,'DDD6' AS DDD6
,'TELEFONE6' AS TELEFONE6
,'STATUS6' AS STATUS6
,'PREFERENCIAL6' AS PREFERENCIAL6
,'DATA_ATUALIZACAO6' AS DATA_ATUALIZACAO6
,'QUALIFICACAO6' AS QUALIFICACAO6
,'ORIGEM6' AS ORIGEM6
,'TIPO6' AS TIPO6
,'DDD7' AS DDD7
,'TELEFONE7' AS TELEFONE7
,'STATUS7' AS STATUS7
,'PREFERENCIAL7' AS PREFERENCIAL7
,'DATA_ATUALIZACAO7' AS DATA_ATUALIZACAO7
,'QUALIFICACAO7' AS QUALIFICACAO7
,'ORIGEM7' AS ORIGEM7
,'TIPO7' AS TIPO7
,'DDD8' AS DDD8
,'TELEFONE8' AS TELEFONE8
,'STATUS8' AS STATUS8
,'PREFERENCIAL8' AS PREFERENCIAL8
,'DATA_ATUALIZACAO8' AS DATA_ATUALIZACAO8
,'QUALIFICACAO8' AS QUALIFICACAO8
,'ORIGEM8' AS ORIGEM8
,'TIPO8' AS TIPO8
,'DDD9' AS DDD9
,'TELEFONE9' AS TELEFONE9
,'STATUS9' AS STATUS9
,'PREFERENCIAL9' AS PREFERENCIAL9
,'DATA_ATUALIZACAO9' AS DATA_ATUALIZACAO9
,'QUALIFICACAO9' AS QUALIFICACAO9
,'ORIGEM9' AS ORIGEM9
,'TIPO9' AS TIPO9
,'DDD10' AS DDD10
,'TELEFONE10' AS TELEFONE10
,'STATUS10' AS STATUS10
,'PREFERENCIAL10' AS PREFERENCIAL10
,'DATA_ATUALIZACAO10' AS DATA_ATUALIZACAO10
,'QUALIFICACAO10' AS QUALIFICACAO10
,'ORIGEM10' AS ORIGEM10
,'TIPO10' AS TIPO10
,'DDD11' AS DDD11
,'TELEFONE11' AS TELEFONE11
,'STATUS11' AS STATUS11
,'PREFERENCIAL11' AS PREFERENCIAL11
,'DATA_ATUALIZACAO11' AS DATA_ATUALIZACAO11
,'QUALIFICACAO11' AS QUALIFICACAO11
,'ORIGEM11' AS ORIGEM11
,'TIPO11' AS TIPO11
,'DDD12' AS DDD12
,'TELEFONE12' AS TELEFONE12
,'STATUS12' AS STATUS12
,'PREFERENCIAL12' AS PREFERENCIAL12
,'DATA_ATUALIZACAO12' AS DATA_ATUALIZACAO12
,'QUALIFICACAO12' AS QUALIFICACAO12
,'ORIGEM12' AS ORIGEM12
,'TIPO12' AS TIPO12
,'DDD13' AS DDD13
,'TELEFONE13' AS TELEFONE13
,'STATUS13' AS STATUS13
,'PREFERENCIAL13' AS PREFERENCIAL13
,'DATA_ATUALIZACAO13' AS DATA_ATUALIZACAO13
,'QUALIFICACAO13' AS QUALIFICACAO13
,'ORIGEM13' AS ORIGEM13
,'TIPO13' AS TIPO13
,'DDD14' AS DDD14
,'TELEFONE14' AS TELEFONE14
,'STATUS14' AS STATUS14
,'PREFERENCIAL14' AS PREFERENCIAL14
,'DATA_ATUALIZACAO14' AS DATA_ATUALIZACAO14
,'QUALIFICACAO14' AS QUALIFICACAO14
,'ORIGEM14' AS ORIGEM14
,'TIPO14' AS TIPO14
,'DDD15' AS DDD15
,'TELEFONE15' AS TELEFONE15
,'STATUS15' AS STATUS15
,'PREFERENCIAL15' AS PREFERENCIAL15
,'DATA_ATUALIZACAO15' AS DATA_ATUALIZACAO15
,'QUALIFICACAO15' AS QUALIFICACAO15
,'ORIGEM15' AS ORIGEM15
,'TIPO15' AS TIPO15
,'DDD16' AS DDD16
,'TELEFONE16' AS TELEFONE16
,'STATUS16' AS STATUS16
,'PREFERENCIAL16' AS PREFERENCIAL16
,'DATA_ATUALIZACAO16' AS DATA_ATUALIZACAO16
,'QUALIFICACAO16' AS QUALIFICACAO16
,'ORIGEM16' AS ORIGEM16
,'TIPO16' AS TIPO16
,'DDD17' AS DDD17
,'TELEFONE17' AS TELEFONE17
,'STATUS17' AS STATUS17
,'PREFERENCIAL17' AS PREFERENCIAL17
,'DATA_ATUALIZACAO17' AS DATA_ATUALIZACAO17
,'QUALIFICACAO17' AS QUALIFICACAO17
,'ORIGEM17' AS ORIGEM17
,'TIPO17' AS TIPO17
,'DDD18' AS DDD18
,'TELEFONE18' AS TELEFONE18
,'STATUS18' AS STATUS18
,'PREFERENCIAL18' AS PREFERENCIAL18
,'DATA_ATUALIZACAO18' AS DATA_ATUALIZACAO18
,'QUALIFICACAO18' AS QUALIFICACAO18
,'ORIGEM18' AS ORIGEM18
,'TIPO18' AS TIPO18
,'DDD19' AS DDD19
,'TELEFONE19' AS TELEFONE19
,'STATUS19' AS STATUS19
,'PREFERENCIAL19' AS PREFERENCIAL19
,'DATA_ATUALIZACAO19' AS DATA_ATUALIZACAO19
,'QUALIFICACAO19' AS QUALIFICACAO19
,'ORIGEM19' AS ORIGEM19
,'TIPO19' AS TIPO19
,'DDD20' AS DDD20
,'TELEFONE20' AS TELEFONE20
,'STATUS20' AS STATUS20
,'PREFERENCIAL20' AS PREFERENCIAL20
,'DATA_ATUALIZACAO20' AS DATA_ATUALIZACAO20
,'QUALIFICACAO20' AS QUALIFICACAO20
,'ORIGEM20' AS ORIGEM20
,'TIPO20' AS TIPO20
,'COD_BARRAS' AS COD_BARRAS
,'DETALHAMENTO_FATURAS' AS DETALHAMENTO_FATURAS
,'PERCENT_DESCONTO' AS PERCENT_DESCONTO
,'QNTD_PARCELAS' AS QNTD_PARCELAS
,'DETALHAMENTO_DESCONTO' AS DETALHAMENTO_DESCONTO
,'DETALHAMENTO_PARCELAS' AS DETALHAMENTO_PARCELAS
,'CORINGA1' AS CORINGA1
,'CORINGA2' AS CORINGA2
,'CORINGA3' AS CORINGA3
,'CORINGA4' AS CORINGA4
,'CORINGA5' AS CORINGA5
,'CORINGA6' AS CORINGA6
,'CORINGA7' AS CORINGA7
,'CORINGA8' AS CORINGA8
,'CORINGA9' AS CORINGA9
,'CORINGA10' AS CORINGA10
)A



----------------------------------------------------------------- EXPORTA BCP PARA A PASTA -----------------------------------------------------------------

SET LANGUAGE 'BRAZILIAN'


DECLARE @DATA VARCHAR(10) = (SELECT REPLACE(CONVERT(VARCHAR(23),GETDATE(),23),'-','')) 
DECLARE @HORA VARCHAR (6) = (SELECT REPLACE(FORMAT(GETDATE(),'hh:mm:ss'),':',''))
DECLARE @DATA2 VARCHAR(4) = (SELECT REPLACE(LEFT (CONVERT(VARCHAR(10),GETDATE(),103),5),'/',''))  
DECLARE @MES VARCHAR(20) = CONCAT(FORMAT(GETDATE(),'MM'),' - ',UPPER(DATENAME(MONTH, GETDATE())))
DECLARE @ANO VARCHAR(8) = YEAR(GETDATE()) 

DECLARE @NOMENCLATURA_DISPARO VARCHAR(MAX) = ''+@DATA+'_'+@HORA+'_39_FULL.csv'
DECLARE @BCP VARCHAR(MAX)
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''OURO'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)

SET @NOMENCLATURA_DISPARO = ''+@DATA+'_'+@HORA+'_40_FULL.csv'
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''ESMERALDA'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)

SET @NOMENCLATURA_DISPARO = ''+@DATA+'_'+@HORA+'_41_FULL.csv'
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''RUBI'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)

SET @NOMENCLATURA_DISPARO = ''+@DATA+'_'+@HORA+'_42_FULL.csv'
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''SAFIRA'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)

SET @NOMENCLATURA_DISPARO = ''+@DATA+'_'+@HORA+'_43_FULL.csv'
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''DIAMANTE'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)

SET @NOMENCLATURA_DISPARO = ''+@DATA+'_'+@HORA+'_44_FULL.csv'
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''PLATINA'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)

SET @NOMENCLATURA_DISPARO = ''+@DATA+'_'+@HORA+'_45_FULL.csv'
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''PRATA'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)

SET @NOMENCLATURA_DISPARO = ''+@DATA+'_'+@HORA+'_46_FULL.csv'
SET @BCP = ' master..xp_cmdshell ''bcp " SELECT DISTINCT * FROM ##FINAL_LAYOUT WHERE CLASSE IN (''''BRONZE'''',''''CLASSE'''') ORDER BY CORINGA2 DESC " queryout "\\polaris\NectarServices\Administrativo\Temporario\Riachuelo"\'+@NOMENCLATURA_DISPARO+' -c -T -t ";" '''
EXEC (@BCP)



-- LAYOUT_OURO --> 39  
-- LAYOUT_ESMERALDA --> 40
-- LAYOUT_RUBI --> 41
-- LAYOUT_SAFIRA --> 42  
-- LAYOUT_DIAMANTE --> 43
-- LAYOUT_PLATINA --> 44
-- LAYOUT_PRATA --> 45 
-- LAYOUT_BRONZE --> 46  


IF OBJECT_ID('TEMPDB..##FINAL_LAYOUT') IS NOT NULL DROP TABLE ##FINAL_LAYOUT


END


