
DECLARE @D1 VARCHAR(20) = CONCAT((CONVERT(DATE,GETDATE()-1)), ' 00:00:00')
DECLARE @D2 VARCHAR(20) = CONCAT((CONVERT(DATE,GETDATE()-1)), ' 23:59:59')

SELECT 
 CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 ' ELSE ''
 END [IDADE],
ESTAD_ETD,
DESCR_ETD,
 DT_INFO
,CLIENTES		= COUNT(CPF_CNPJ)
,CLIENTES_U		= COUNT(DISTINCT CPF_CNPJ)
,SALDO			= SUM(SALDO) 
,CONTABIL		= SUM(CONTABIL_SAVE)

--INTO tb_ds_carteira_daily_pafixa_15A30
FROM Data_Science..ESTOQUE_RCHLO_ANALITICO_MES ESTOQUE
	INNER JOIN	[10.251.1.36].[NECTAR].[dbo].[TB_DEVEDOR] D		WITH(NOLOCK)	ON D.CGCPF_DEV = ESTOQUE.CPF_CNPJ
	INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_CONTRATO B	WITH(NOLOCK) ON B.IDDEV_CON = D.IDDEV_DEV
	INNER JOIN	[10.251.1.36].[NECTAR].[dbo].[TB_ENDERECO]	WITH(NOLOCK) ON B.IDCON_CON = IDORI_END 
	INNER JOIN  [10.251.1.36].[nectar].[dbo].[TB_ESTADO]	WITH(NOLOCK) ON IDEST_END  = IDEST_ETD  

WHERE DIAS_ATRASO BETWEEN 15 AND 30
AND DT_INFO BETWEEN @D1 AND @D2
AND ELEGIBILIDADE = 1

GROUP BY 
 DT_INFO,
 ESTAD_ETD,
DESCR_ETD,
 CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 ' ELSE ''
 END 