
USE [DATA_SCIENCE]
GO

DECLARE @D1 DATETIME	=	 CONCAT('2022-05-01',' 00:00:00.000')   
DECLARE @D2 DATETIME	=	 CONCAT('2022-05-31',' 23:59:59.599')
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: PAGAMENTOS EFETIVIDADE															*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/ 
SELECT
	ATRASO
,	ACORDO#		 =	  SUM(IIF(ATRASO != '', 1, 0))
,	ACORDO$		 =	  SUM(VALOR_ACORDO)
,	PAGOS#		 =	  SUM(IIF(DATA_PGTO IS NOT NULL, 1, 0))
,	PAGOS$		 =	  SUM(IIF(DATA_PGTO IS NOT NULL, VALOR_PAGO, 0))
FROM (
				  SELECT DISTINCT   
				  CGCPF_DEV 
				, CONTR_CON
				, IDCON_CON
				, CASE  
						WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTACO_ACO)) BETWEEN 0    AND 15   THEN '0000 A 0015' -- RUBI 
						WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTACO_ACO)) BETWEEN 16   AND 30   THEN '0016 A 0030' -- RUBI 
						WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTACO_ACO)) BETWEEN 31	 AND 60   THEN '0031 A 0060' -- SAFIRA  
						WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTACO_ACO)) BETWEEN 61	 AND 90   THEN '0061 A 0090' -- SAFIRA  
						WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTACO_ACO)) BETWEEN 91	 AND 120  THEN '0091 A 0120' -- ESMERALDA  
						WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTACO_ACO)) BETWEEN 121	 AND 150  THEN '0121 A 0150' -- ESMERALDA  
						WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTACO_ACO)) BETWEEN 151  AND 180  THEN '0151 A 0180' -- ESMERALDA  
						ELSE '' 
				  END ATRASO    
				, CONVERT(MONEY, VLPAG_PAG) AS VALOR_PAGO 
				, CONVERT(MONEY,VLVEN_PAG)  AS VALOR_ACORDO
				, CONVERT (DATE,DTPAG_PAG) AS DATA_PGTO
				, CONVERT(DATE,DTVEN_PAG)  AS DATA_VENC
				, CAST(NULL AS NUMERIC) AS TESTE
				FROM	  [10.251.1.36].NECTAR.DBO.TB_CONTRATO     WITH(NOLOCK)   
				JOIN	  [10.251.1.36].NECTAR.DBO.TB_ACORDO       WITH(NOLOCK) ON IDCON_CON = IDCON_ACO  
				JOIN	  [10.251.1.36].NECTAR.DBO.TB_PAGAMENTO    WITH(NOLOCK) ON IDACO_ACO = IDACO_PAG  
				JOIN	  [10.251.1.36].NECTAR.DBO.TB_DEVEDOR      WITH(NOLOCK) ON IDDEV_CON = IDDEV_DEV  
				LEFT JOIN [10.251.1.36].NECTAR.DBO.TB_PESSOAL	   WITH(NOLOCK) ON IDPES_ACO = IDPES_PES  
				LEFT JOIN DATA_SCIENCE..OPERADORES								ON IDPES_ACO = IDPES  
				WHERE IDEMP_CON IN (3,5,6,19)  
				AND DTVEN_PAG BETWEEN @D1 AND @D2
				AND PAGAM_PAG = 1  
				GROUP BY   
				CGCPF_DEV  
				, IDCON_CON  
				, SCORE_CON   
				, CONVERT(DATE,  DTPAG_PAG)  
				, CONVERT(MONEY, VLPAG_PAG)  
				, CONVERT(MONEY,VLVEN_PAG)
				, CONVERT(DATE,  DTACO_ACO)
				, CONVERT(DATE,  DTVEN_PAG)
				, CONTR_CON
	 ) X  
WHERE ATRASO <> '' 
GROUP BY ATRASO
ORDER BY ATRASO ASC
/******************************************************************************************************/	
UPDATE #PRE_PAGAMENTO
SET TESTE	=	Y.SALDO_CONTABIL

FROM #PRE_PAGAMENTO X JOIN REPORTS.DBO.TB_SAVE_RIACHUELO_ULTIMA Y ON Y.CHAVE_CYBER = X.CONTR_CON
WHERE X.ATRASO != ''
AND X.DATA_PGTO IS NOT NULL
/******************************************************************************************************/
DROP TABLE IF EXISTS #SALDO_ATUALIZADO
SELECT 
		*
,		VALIDA	=	IIF(VALOR_PAGO < CONVERT(MONEY,TESTE), CONVERT(MONEY,TESTE), VALOR_PAGO)
INTO #SALDO_ATUALIZADO
FROM #PRE_PAGAMENTO

