
DROP TABLE IF EXISTS #LANCAMENTOS
SELECT * INTO #LANCAMENTOS FROM OPENQUERY ([10.251.1.36],

'
DECLARE @DT_INI AS DATE = ''2022-07-01''
DECLARE @DT_FIM AS DATE = ''2022-07-31''

SELECT DISTINCT 
				IDEMP_CON
,				CGCPF_DEV
,				IDDEV_DEV
,				IDCON_CON
,				CONTR_CON
,				CONVERT(DATE,MIN(DTFAT_ATI)) AS DTFAT_ATI
,				CONVERT(DATE,DTATR_CON) AS DTATR_CON
,				IDACO_ACO
,				IDPES_ACO
,				NOME_PES
,				ALCAD_PES
,				USUAR_PES
,				CONVERT(DATE,DTCAD_ACO) AS DTCAD_ACO
,				PAGAM_PAG
,				IDPAG_PAG
,				CONVERT(DATE,DTPAG_PAG) AS DTPAG_PAG
,				CONVERT(DATE,DTVEN_PAG) AS DTVEN_PAG
,				CONVERT(MONEY,VLPAG_PAG) AS VLPAG_PAG
,				CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END DESCR_BND
,				FLAG	=	 ''DIRETO''
FROM NECTAR.DBO.TB_PAGAMENTO WITH(NOLOCK)

INNER JOIN NECTAR.DBO.TB_ACORDO WITH(NOLOCK) ON IDACO_ACO = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_ACORDOTIT WITH(NOLOCK) ON IDACO_ATI = IDACO_PAG
LEFT JOIN NECTAR.DBO.TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = IDDOC_ATI
LEFT JOIN NECTAR.DBO.TB_PESSOAL WITH(NOLOCK) ON IDPES_PES = IDPES_ACO
INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_ACO
INNER JOIN NECTAR.DBO.TB_DEVEDOR WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN NECTAR.DBO.TB_BANDEIRA WITH(NOLOCK) ON IDBND_BND = IDBND_CON

WHERE DTPAG_PAG between @DT_INI and @DT_FIM
		AND IDEMP_CON IN (''17'')

GROUP BY  
			IDEMP_CON
,			CGCPF_DEV
,			IDDEV_DEV
,			IDCON_CON
,			CONTR_CON
,			CONVERT(DATE,DTATR_CON)
,			IDACO_ACO
,			IDPES_ACO
,			NOME_PES
,			ALCAD_PES
,			USUAR_PES
,			CONVERT(DATE,DTCAD_ACO)
,			PAGAM_PAG
,			IDPAG_PAG
,			CONVERT(DATE,DTPAG_PAG)
,			CONVERT(DATE,DTVEN_PAG)
,			CONVERT(MONEY,VLPAG_PAG)
,			CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END

UNION ALL

SELECT DISTINCT 
			IDEMP_CON
,			CGCPF_DEV
,			IDDEV_DEV
,			IDCON_CON
,			CONTR_CON
,			CONVERT(DATE,MIN(DTFAT_PGD)) AS DTFAT_PGD
,			CONVERT(DATE,DTATR_CON) AS DTATR_CON
,			NULL AS IDACO_ACO
,			NULL AS IDPES_ACO
,			NULL AS NOME_PES
,			NULL AS ALCAD_PES
,			NULL AS USUAR_PES
,			CONVERT(DATE,DTPAG_PGD) AS DTPAG_PGD
,			1 AS PAGAM_PGD
,			IDPGD_PGD
,			CONVERT(DATE,DTPAG_PGD) AS DTPAG_PGD
,			CONVERT(DATE,DTPAG_PGD) AS DTVEN_PGD
,			CONVERT(MONEY,VLPAG_PGD) AS VLPAG_PGD
,			CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END DESCR_BND
,			FLAG	=	 ''INDIRETO''
FROM
		NECTAR.DBO.TB_PAGDIRETO WITH(NOLOCK)

INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_PGD
INNER JOIN NECTAR.DBO.TB_DEVEDOR WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON
LEFT JOIN (
			SELECT DISTINCT IDCON_TRA,IDDOC_TRA FROM NECTAR.DBO.TB_TRANSACAO WITH(NOLOCK) INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_TRA AND IDEMP_CON IN (''17'')
			UNION ALL
			SELECT DISTINCT IDCON_BAI,IDDOC_BAI FROM NECTAR.DBO.TB_BAIXA WITH(NOLOCK) INNER JOIN NECTAR.DBO.TB_CONTRATO WITH(NOLOCK) ON IDCON_CON = IDCON_BAI AND IDEMP_CON IN (''17'')		
		  )A ON IDCON_TRA = IDCON_PGD
LEFT JOIN NECTAR.DBO.TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = A.IDDOC_TRA
LEFT JOIN NECTAR.DBO.TB_BANDEIRA WITH(NOLOCK) ON IDBND_BND = IDBND_CON

WHERE DTPAG_PGD >= @DT_INI AND IDEMP_CON IN (''17'')  

GROUP BY  
			IDEMP_CON
,			IDDEV_DEV
,			CGCPF_DEV
,			IDCON_CON
,			CONTR_CON
,			CONVERT(DATE,DTATR_CON)
,			IDPGD_PGD
,			CONVERT(DATE,DTPAG_PGD)
,			CONVERT(MONEY,VLPAG_PGD)
,			CASE WHEN DESCR_BND IS NULL THEN DESCR_DOC ELSE DESCR_BND END
')

select distinct 

 CONTRATO
,max(DT_INFO) DT_INFO
,max(DIAS_ATRASO) DIAS_ATRASO 

into #BASE

from Data_Science..TB_DS_FOTOGRAFIA_RENNER with(nolock) 

where DT_INFO between '2022-07-01' and '2022-07-31' 

group by CONTRATO

select distinct 



--------------------------Calculo do H.O.
,case 
	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 91 and 120 then CONVERT(MONEY, VLPAG_PAG)*0.05 
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 91 and 120 then CONVERT(MONEY, VLPAG_PAG)*0.05 
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 91 and 120 then CONVERT(MONEY, VLPAG_PAG)*0.05 

	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 121 and 180 then CONVERT(MONEY, VLPAG_PAG)*0.10
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 121 and 180 then CONVERT(MONEY, VLPAG_PAG)*0.13
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 121 and 180 then CONVERT(MONEY, VLPAG_PAG)*0.10 

	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 181 and 240 then CONVERT(MONEY, VLPAG_PAG)*0.13
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 181 and 240 then CONVERT(MONEY, VLPAG_PAG)*0.15
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 181 and 240 then CONVERT(MONEY, VLPAG_PAG)*0.13

	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 241 and 360 then CONVERT(MONEY, VLPAG_PAG)*0.15
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 241 and 360 then CONVERT(MONEY, VLPAG_PAG)*0.17
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 241 and 360 then CONVERT(MONEY, VLPAG_PAG)*0.15

	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 361 and 720 then CONVERT(MONEY, VLPAG_PAG)*0.18
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 361 and 720 then CONVERT(MONEY, VLPAG_PAG)*0.22
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 361 and 720 then CONVERT(MONEY, VLPAG_PAG)*0.18

	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 721 and 1080 then CONVERT(MONEY, VLPAG_PAG)*0.23
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 721 and 1080 then CONVERT(MONEY, VLPAG_PAG)*0.25
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 721 and 1080 then CONVERT(MONEY, VLPAG_PAG)*0.23

	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 1081 and 1440 then CONVERT(MONEY, VLPAG_PAG)*0.25
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 1081 and 1440 then CONVERT(MONEY, VLPAG_PAG)*0.30
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 1081 and 1440 then CONVERT(MONEY, VLPAG_PAG)*0.25

	when DESCR_BND IN ('PLFATURA','CCRCFI','RCCRCFI','FACRELI','RFACRELI')	and dias_atraso between 1441 and 1800 then CONVERT(MONEY, VLPAG_PAG)*0.30
	when DESCR_BND IN ('REPCFI','EPCFI')									and dias_atraso between 1441 and 1800 then CONVERT(MONEY, VLPAG_PAG)*0.40
	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso between 1441 and 1800 then CONVERT(MONEY, VLPAG_PAG)*0.30

	when DESCR_BND IN ('CBRCARNE','CBRCREL','MASTER','VISA')				and dias_atraso > 1800 then CONVERT(MONEY, VLPAG_PAG)*0.40

	else 0

 end HO

from #LANCAMENTOS a
join #BASE b on CONTRATO = contr_con



