USE DATA_SCIENCE
GO


DROP TABLE #FUSAO
SELECT 
			DTADMIT
,			DEMISSAO
,			ENTRADAM
,			SAIDAT
,			ATIVO
,			NOME					=	UPPER(NOME)
,			TIPO_CONTRATO			=	UPPER(IIF(CONTRATO IN ('MENSALISTA','CLT'), 'CLT', 'ESTAGIARIO'))
,			SETOR					=	UPPER(IIF(CUSTO IN ('AMBEV','ORIGINAL','CAEDU','RIACHUELO','PREVENTIVO','DIGITAL','PRA VALER','PRAVALER','MENU'), 'OPERACAO', CAST(CUSTO AS VARCHAR)))
,			JORNADA_DIA				=	UPPER(CONCAT(DATEDIFF(HOUR,ENTRADAM,SAIDAT), ' ', 'HORAS'))
,			MEDIA_EMPRESA			=	AVG(DATEDIFF(DAY,DTADMIT,DEMISSAO))
INTO #FUSAO
FROM SUPERSOFT
WHERE CUSTO NOT IN ('AMBEV','ORIGINAL','CAEDU','RIACHUELO','PREVENTIVO','DIGITAL','PRA VALER','PRAVALER','MENU')
GROUP BY
	DTADMIT
,	DEMISSAO
,	ENTRADAM
,	SAIDAT
,	ATIVO
,	UPPER(NOME)
,	UPPER(IIF(CONTRATO IN ('MENSALISTA','CLT'), 'CLT', 'ESTAGIARIO'))
,	UPPER(IIF(CUSTO IN ('AMBEV','ORIGINAL','CAEDU','RIACHUELO','PREVENTIVO','DIGITAL','PRA VALER','PRAVALER','MENU'), 'OPERACAO', CAST(CUSTO AS VARCHAR)))
,	UPPER(CONCAT(DATEDIFF(HOUR,ENTRADAM,SAIDAT), ' ', 'HORAS'))

UNION ALL

SELECT 
			DTADMIT
,			DEMISSAO
,			ENTRADAM
,			SAIDAT
,			ATIVO
,			NOME					=	UPPER(NOME)
,			TIPO_CONTRATO			=	UPPER(IIF(CONTRATO IN ('MENSALISTA','CLT'), 'CLT', 'ESTAGIARIO'))
,			SETOR					=	UPPER(IIF(CUSTO IN ('AMBEV','ORIGINAL','CAEDU','RIACHUELO','PREVENTIVO','DIGITAL','PRA VALER','PRAVALER','MENU'), 'OPERACAO', CAST(CUSTO AS VARCHAR)))
,			JORNADA_DIA				=	UPPER(CONCAT(DATEDIFF(HOUR,ENTRADAM,SAIDAT), ' ', 'HORAS'))
,			MEDIA_OPERACAO_EMPRESA  =	AVG(DATEDIFF(DAY,DTADMIT,DEMISSAO))
--INTO #OPERACAO
FROM SUPERSOFT
WHERE CUSTO IN ('AMBEV','ORIGINAL','CAEDU','RIACHUELO','PREVENTIVO','DIGITAL','PRA VALER','PRAVALER','MENU')
GROUP BY
	DTADMIT
,	DEMISSAO
,	ENTRADAM
,	SAIDAT
,	ATIVO
,	UPPER(NOME)
,	UPPER(IIF(CONTRATO IN ('MENSALISTA','CLT'), 'CLT', 'ESTAGIARIO'))
,	UPPER(IIF(CUSTO IN ('AMBEV','ORIGINAL','CAEDU','RIACHUELO','PREVENTIVO','DIGITAL','PRA VALER','PRAVALER','MENU'), 'OPERACAO', CAST(CUSTO AS VARCHAR)))
,	UPPER(CONCAT(DATEDIFF(HOUR,ENTRADAM,SAIDAT), ' ', 'HORAS'))

DROP TABLE #TEMP
SELECT 
		*
,		STATUS			=	IIF(ATIVO = 'N', 0, 1)
,		AVG_EMPRESA		=	ISNULL(IIF(MEDIA_EMPRESA IS NOT NULL, CONCAT(CAST(MEDIA_EMPRESA AS VARCHAR),' ', 'DIAS'), CAST(MEDIA_EMPRESA AS VARCHAR)),'ATIVO')
INTO #TEMP
FROM #FUSAO


ALTER TABLE #TEMP
DROP COLUMN ATIVO, MEDIA_EMPRESA


SELECT 
		CONT_CONTRATO	=  COUNT(TIPO_CONTRATO)
,		CONT_SETOR		=  COUNT(SETOR)
,		NOME
FROM #TEMP

