

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: NESSA TABELA CONSEGUE A IDADE DO CLIENTE E A REGIÃO								*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*
SELECT TOP 10
IDDEV_DEV
, CGCPF_DEV
,NOME_DEV
,CONVERT(DATE,DTNAS_DEV)
,DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) AS IDADE
FROM [10.251.1.36].[NECTAR].[dbo].TB_DEVEDOR  WITH(NOLOCK)

*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: VARIÁVEIS DO CÓDIGO																*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/  
  
DECLARE @D1 DATE = '2022-04-01'         
DECLARE @D2 DATE = '2022-04-25'           
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: ANALITICO DE DISPAROS																*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/   
IF OBJECT_ID ('tempdb.dbo.#DISPAROS') IS NOT NULL DROP TABLE #DISPAROS  
SELECT  

 CASE WHEN NOME_PES LIKE '%Ad Riach%' THEN 'AD' ELSE 'OPERAÇÃO' END [AD_OP],
CGCPF_DEV,
--,CONVERT(DATE,DTNAS_DEV)
CONVERT(DATE,DTAND_AND)[DTAND_AND]  
,IMAPS_OCO

,CASE   
 WHEN IMAPS_OCO = 'SMS' THEN 'SMS'  
 WHEN IMAPS_OCO = 'URA' THEN 'URA'     
 WHEN IMAPS_OCO IN ('EMAIL','MALA') THEN 'EMAIL'  
 WHEN (CASE WHEN USUAR_PES IN ('wilsonr','Whatsr')  THEN 'DIGITAL' END) = 'DIGITAL'  THEN 'DIGITAL'     
 WHEN (CASE WHEN SETOR = 'DIGITAL' THEN 'WHATSAPP' END) = 'WHATSAPP' THEN 'WHATSAPP'  ELSE ''  
END [PESO]

, IDAND_AND  
, IDCON_AND  
-- CGCPF_DEV,

,CASE  
 --WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTAND_AND)) < 0      THEN 'A VENCER'   
 WHEN DATEDIFF(DAY,MIN(CONVERT(DATE,DTATR_CON)),CONVERT(DATE,DTAND_AND)) BETWEEN 15 AND 30  THEN 'RUBI'   
END [LIGA]

 INTO   
 #DISPAROS
 
FROM    
   [10.251.1.36].[NECTAR].[dbo].TB_ANDAMENTO A WITH(NOLOCK)  
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_CONTRATO B WITH(NOLOCK) ON B.IDCON_CON = IDCON_AND  
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_DEVEDOR  WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON  
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_OCORRENCIA WITH(NOLOCK) ON IDOCO_OCO = IDOCO_AND   
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_TRANSACAO WITH(NOLOCK) ON IDCON_TRA = IDCON_CON  
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_DOCUMENTO WITH(NOLOCK) ON IDDOC_DOC = IDDOC_TRA
INNER JOIN	[10.251.1.36].[NECTAR].[dbo].[TB_ENDERECO] WITH(NOLOCK)  ON B.IDCON_CON = IDORI_END 
INNER JOIN  [10.251.1.36].[nectar].[dbo].[TB_ESTADO] WITH(NOLOCK) ON IDEST_END  = IDEST_ETD  
LEFT JOIN   [10.251.1.36].[NECTAR].[dbo].TB_PESSOAL WITH(NOLOCK) ON IDPES_PES = IDPES_AND    
LEFT JOIN   DATA_SCIENCE.DBO.OPERADORES WITH(NOLOCK) ON IDPES = IDPES_AND AND SETOR = 'DIGITAL'

WHERE   
 IDEMP_CON IN (3,5,6)   
AND   
 CONVERT(DATE,DTAND_AND) BETWEEN @D1 AND @D2  
AND   
 CASE WHEN IMAPS_OCO = 'SMS' THEN 1 WHEN IMAPS_OCO = 'URA' THEN 1 WHEN IMAPS_OCO IN ('EMAIL','MALA') THEN 1 WHEN USUAR_PES IN ('wilsonr','Whatsr') THEN 1 WHEN SETOR = 'DIGITAL' THEN 1 ELSE 0 END = 1  

GROUP BY   
CONVERT(DATE,DTAND_AND),IMAPS_OCO,IDAND_AND,IDCON_AND,CGCPF_DEV,NOME_PES

 

,CASE   
 WHEN IMAPS_OCO = 'SMS' THEN 'SMS'  
 WHEN IMAPS_OCO = 'URA' THEN 'URA'     
 WHEN IMAPS_OCO IN ('EMAIL','MALA') THEN 'EMAIL'  
 WHEN (CASE WHEN USUAR_PES IN ('wilsonr','Whatsr')  THEN 'DIGITAL' END) = 'DIGITAL'  THEN 'DIGITAL'     
 WHEN (CASE WHEN SETOR = 'DIGITAL' THEN 'WHATSAPP' END) = 'WHATSAPP' THEN 'WHATSAPP'  ELSE ''  
END   



IF OBJECT_ID ('tempdb.dbo.#DISPAROSRUBI') IS NOT NULL DROP TABLE #DISPAROSRUBI

SELECT 
*
INTO #DISPAROSRUBI
FROM #DISPAROS WHERE LIGA = 'RUBI'


IF OBJECT_ID ('tempdb.dbo.#disparorubifinal') IS NOT NULL DROP TABLE #disparorubifinal

SELECT 
DISPAR.AD_OP,
DISPAR.CGCPF_DEV, 
DISPAR.DTAND_AND,
DISPAR.IMAPS_OCO,
DISPAR.PESO,
DISPAR.IDAND_AND,
DISPAR.IDCON_AND,

LIGA,


 CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 ' ELSE ''
 END [IDADE],
ESTAD_ETD,
DESCR_ETD

into #disparorubifinal
FROM #DISPAROSRUBI DISPAR
	INNER JOIN	[10.251.1.36].[NECTAR].[dbo].[TB_DEVEDOR] D		WITH(NOLOCK)	ON D.CGCPF_DEV = DISPAR.CGCPF_DEV


	--INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_CONTRATO B		WITH(NOLOCK)	ON B.IDCON_CON = IDCON_AND   
	--INNER JOIN	[10.251.1.36].[NECTAR].[dbo].[TB_ENDERECO]		WITH(NOLOCK)	ON B.IDCON_CON = IDORI_END 
	--INNER JOIN  [10.251.1.36].[nectar].[dbo].[TB_ESTADO]		WITH(NOLOCK)	ON IDEST_END  = IDEST_ETD 
	
	INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_CONTRATO B	WITH(NOLOCK) ON B.IDDEV_CON = D.IDDEV_DEV
	--INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_DEVEDOR		WITH(NOLOCK) ON IDDEV_DEV = IDDEV_CON  

	INNER JOIN	[10.251.1.36].[NECTAR].[dbo].[TB_ENDERECO]	WITH(NOLOCK) ON B.IDCON_CON = IDORI_END 
	INNER JOIN  [10.251.1.36].[nectar].[dbo].[TB_ESTADO]	WITH(NOLOCK) ON IDEST_END  = IDEST_ETD  
   

WHERE LIGA = 'RUBI'






/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: RETORNO DAS AÇÕES																	*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/  

--DECLARE @D1 DATE = '2022-04-01'         
--DECLARE @D2 DATE = '2022-04-01'  
/*
DECLARE @D1 DATE = '2022-04-01'         
DECLARE @D2 DATE = '2022-04-22'
*/
IF OBJECT_ID ('tempdb.dbo.#RETORNO') IS NOT NULL DROP TABLE #RETORNO  
  
SELECT DISTINCT 

 CASE WHEN NOME_PES LIKE '%Ad Riach%' THEN 'AD' ELSE 'OPERAÇÃO' END [AD_OP],

 CASE WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 0 AND 20 THEN '000 A 020'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 21 AND 40 THEN '021 A 040'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) BETWEEN 41 AND 60 THEN '041 A 060'
	  WHEN  DATEDIFF(YEAR,DTNAS_DEV,GETDATE()) >= 61  THEN '>= 061 '
	  END [IDADE],

 DTAND_AND AS DATA, 
 IDCON_AND AS IDCON,  
 CGCPF_DEV AS CGCPF,  
 CASE WHEN IMAPS_OCO IN ('ALO','CPC_N','CPC_P') THEN 1 ELSE 0 END [ALO],  
 CASE WHEN IMAPS_OCO IN ('CPC_N','CPC_P') THEN 1 ELSE 0 END [CPC],  
 CASE WHEN IMAPS_OCO IN ('CPC_P') THEN 1 ELSE 0 END [CPC_P],  
 CASE WHEN IDOCO_AND IN ('67') THEN  1 ELSE 0 END [ACORDO],
 ESTAD_ETD,
 DESCR_ETD 


INTO #RETORNO  

/* ANALISE DE IDPES_AND

[10.251.1.36].[NECTAR].[dbo].TB_PESSOAL WHERE NOME_PES LIKE '%Ad Riach%'

*/

FROM    
 [10.251.1.36].[NECTAR].[dbo].TB_ANDAMENTO   
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_CONTRATO ON IDCON_CON = IDCON_AND   
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_OCORRENCIA ON IDOCO_OCO = IDOCO_AND   
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].TB_DEVEDOR ON IDDEV_DEV = IDDEV_CON  
INNER JOIN	[10.251.1.36].[NECTAR].[dbo].TB_PESSOAL ON IDPES_PES = IDPES_AND 
INNER JOIN	[10.251.1.36].[NECTAR].[dbo].[TB_ENDERECO]	 ON IDCON_CON = IDORI_END 
INNER JOIN  [10.251.1.36].[NECTAR].[dbo].[TB_ESTADO]	 ON IDEST_END  = IDEST_ETD  
   

WHERE   
 CASE WHEN IMAPS_OCO IN ('ALO','CPC_N','CPC_P') THEN 1 WHEN IDOCO_AND = '67' THEN 1 ELSE 0 END  = 1  
AND   
 IDEMP_CON IN (3,5,6)   
AND   
 ORIGE_AND = 1   
AND   
 CONVERT(DATE,DTAND_AND) BETWEEN @D1 AND @D2 

 --SELECT * FROM #RETORNO
 /*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO: FUNIL SOBRE RETORNO DAS AÇÕES														*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/  
  
IF OBJECT_ID ('tempdb.dbo.#ACIONAMENTO') IS NOT NULL DROP TABLE #ACIONAMENTO  
  
SELECT DISTINCT   
 A.*,  
 ISNULL(ALO,0) AS ALO,  
 ISNULL(CPC,0) AS CPC,  
 ISNULL(CPC_P,0) AS CPC_P,  
 ISNULL(ACORDO,0) AS ACORDO
INTO    
 #ACIONAMENTO  
FROM   
 #disparorubifinal A     
LEFT JOIN (SELECT DISTINCT DATA,CGCPF,ALO,CPC,CPC_P,ACORDO,PESO FROM #RETORNO A  
INNER JOIN (SELECT DISTINCT DTAND_AND,CGCPF_DEV,MAX(PESO) AS PESO FROM #DISPAROS   
GROUP BY DTAND_AND,CGCPF_DEV) B ON B.DTAND_AND = CONVERT(DATE,A.DATA) AND B.CGCPF_DEV = A.CGCPF  
)B ON CONVERT(DATE,B.DATA) = A.DTAND_AND AND B.CGCPF = A.CGCPF_DEV AND B.PESO = A.PESO  
  

 -- select * from #ACIONAMENTO
---> FUNIL  
  IF OBJECT_ID ('tempdb.dbo.#FINAL') IS NOT NULL DROP TABLE #FINAL

SELECT DISTINCT
 B.AD_OP,
 B.ESTAD_ETD,
 B.DESCR_ETD,
 B.IDADE, --OK
 B.LIGA,  --OK
 B.PESO AS AÇÃO, --OK   
 SUM(B.DISPAROS) AS REALIZADOS,  
 SUM(B.CPC) CPC,  
 SUM(B.ACORDO) AS ACORDO  
INTO  
 #FINAL  
FROM   
 (SELECT DISTINCT 
LIGA, --OK
AD_OP, --OK
ESTAD_ETD, --OK
DESCR_ETD, --OK
IDADE, --OK
CGCPF_DEV,   
PESO, --OK 
COUNT(DISTINCT IDAND_AND) AS DISPAROS,  
CASE WHEN SUM(ALO) > 0 THEN 1 ELSE 0 END [ALO],  
CASE WHEN SUM(CPC) > 0 THEN 1 ELSE 0 END [CPC],  
CASE WHEN SUM(CPC_P) > 0 THEN 1 ELSE 0 END [CPCP],  
CASE WHEN SUM(ACORDO) > 0 THEN 1 ELSE 0 END [ACORDO]       
FROM   
 #ACIONAMENTO A   
WHERE   
 A.LIGA IN ('RUBI')  
GROUP BY   
 CGCPF_DEV,LIGA,PESO,IDADE, AD_OP, ESTAD_ETD, DESCR_ETD)B   
GROUP BY  
 B.LIGA,B.PESO,B.IDADE, B.AD_OP, B.ESTAD_ETD, B.DESCR_ETD

  
 insert into retorno_acao_15a30
SELECT * 
--into retorno_acao_15a30
 FROM #FINAL   
  
 --elect * from tb_ds_daily_funil__ad_e_pa_15a30_FINAL


 --RUNCATE TABLE retorno_acao_15a30