

DECLARE @CONTADOR_INICIAL INT
DECLARE @CONTADOR_FINAL INT

	SET @CONTADOR_INICIAL = 1
	SET @CONTADOR_FINAL	  = 10

WHILE(@CONTADOR_INICIAL <= @CONTADOR_FINAL)
BEGIN
	INSERT INTO TESTE (ID,PRODUTO,TIPO) VALUES (1,'BICICLETA', 'A')
	SET @CONTADOR_INICIAL = @CONTADOR_INICIAL + 1
END

INSERT INTO TESTE (ID,PRODUTO,TIPO) VALUES (1,'BICICLETA', 'A')
GO 10

SELECT * FROM TESTE