



DECLARE @TABELA VARCHAR(MAX)	=	'SUPERSOFT'
DECLARE @TSQL   VARCHAR(MAX)

IF(SELECT MAX(DTADMIT) FROM SUPERSOFT) = '2022-05-23'
	BEGIN
		SET @TABELA = 'FUNCIONARIOS'
	END

SET @TSQL ='
SELECT *
FROM '+@TABELA+'
'
EXEC (@TSQL)