
DECLARE @STARTDATE   AS DATETIME	=  '2022-05-01'
DECLARE @ENDDATE     AS DATETIME	=	GETDATE()
DECLARE @CURRENTDATE AS DATETIME	=	@STARTDATE

WHILE ( @CURRENTDATE <= @ENDDATE )
BEGIN

    SET @CURRENTDATE = @CURRENTDATE + 1
END

