
INSERT INTO [THESYS_HOMOLOGACAO]..[Beneficio_Fiscal]
SELECT [empresa]
      ,[cod_beneficiofiscal]
      ,[codigo_beneficio]
      ,[descricao]
      ,[cod_estado]
      ,[dt_inicial]
      ,[dt_final]
      ,[dt_change]
      ,[dt_inclusao]
      ,[dt_atualizacao]
      ,[ativo]
      ,[motivo_bloqueio]
      ,[dt_bloqueio]
      ,[obs]
  FROM [THESYS_DEV].[dbo].[Beneficio_Fiscal]
