USE [THESYS_DEV]
GO

INSERT INTO THESYS_PRODUCAO..[CFOP]
           ([cfop]
           ,[descricao_operacao]
           ,[descricao_detalhada]
           ,[entrada_saida]
           ,[origem_destino]
           ,[classif_cfop]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device])
select 
			[cfop]
           ,[descricao_operacao]
           ,[descricao_detalhada]
           ,[entrada_saida]
           ,[origem_destino]
           ,[classif_cfop]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
from [CFOP]