USE [THESYS_DEV]
GO

INSERT INTO [THESYS_HOMOLOGACAO]..[Feriados]
           ([data_feriado]
           ,[descricao]
           ,[feriado_nacional]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device])
select 
 [data_feriado]
,[descricao]
,[feriado_nacional]
,[incl_data]
,[incl_user]
,[incl_device]
,[modi_data]
,[modi_user]
,[modi_device]
,[excl_data]
,[excl_user]
,[excl_device]
from feriados