USE [THESYS_DEV]
GO

INSERT INTO [THESYS_HOMOLOGACAO]..[Historico_Cxbanco]
           ([cod_historcxbanco]
           ,[descricao]
           ,[mensagem]
           ,[ativo]
           ,[tipo]
           ,[gerar_lanc_aut]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
           ,[id_centro_custo]
           ,[id_plano])
select 
[cod_historcxbanco]
           ,[descricao]
           ,[mensagem]
           ,[ativo]
           ,[tipo]
           ,[gerar_lanc_aut]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
           ,[id_centro_custo]
           ,[id_plano]
from [Historico_Cxbanco]