

INSERT INTO THESYS_PRODUCAO..[Moedas]
           ([cod_moeda]
           ,[descricao]
           ,[cod_pais]
           ,[dt_change]
           ,[sigla_ptax]
           ,[id_pais]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
           ,[descricao_pais])
select 
			[cod_moeda]
           ,[descricao]
           ,[cod_pais]
           ,[dt_change]
           ,[sigla_ptax]
           ,[id_pais]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
           ,[descricao_pais]
from Moedas
where cod_moeda != '%'