
TRUNCATE TABLE pagamentos_elet_codigos_retornos
INSERT INTO    pagamentos_elet_codigos_retornos (cod_retorno, descricao, cod_banco)
--Pagina 1
VALUES 
('00', 'Crédito ou Débito Efetivado', '033'),
('01', 'Insuficiência de Fundos - Débito Não Efetuado', '033'),
('02', 'Crédito ou Débito Cancelado pelo Pagador/Credor', '033'),
('03', 'Débito Autorizado pela Agência - Efetuado', '033'),
('AA', 'Controle Inválido', '033'),
('AB', 'Tipo de Operação Inválido', '033'),
('AC', 'Tipo de Serviço Inválido', '033'),
('AD', 'Forma de Lançamento Inválida', '033'),
('AE', 'Tipo/Número de Inscrição Inválido (gerado na crítica ou para informar rejeição)*', '033'),
('AF', 'Código de Convênio Inválido', '033'),
('AG', 'Agência/Conta Corrente/DV Inválido', '033'),
('AH', 'Número Sequencial do Registro no Lote Inválido', '033'),
('AI', 'Código do Segmento de Detalhe Inválido', '033'),
('AJ', 'Tipo de Movimento Inválido', '033'),
('AK', 'Código da Câmara de Compensação do Banco do Favorecido/Depositário Inválido', '033'),
('AL', 'Código do Banco do Favorecido, Instituição de Pagamento ou Depositário Inválido', '033'),
('AM', 'Agência Mantenedora da Conta Corrente do Favorecido Inválida', '033'),
('AN', 'Conta Corrente/DV/Conta de Pagamento do Favorecido Inválido', '033'),
('AO', 'Nome do Favorecido não Informado', '033'),
('AP', 'Data Lançamento Inválida/Vencimento Inválido/Data de Pagamento não permitida.', '033'),
('AQ', 'Tipo/Quantidade da Moeda Inválida', '033'),
('AR', 'Valor do Lançamento Inválido/Divergente/Zerado', '033'),
('AS', 'Aviso ao Favorecido - Identificação Inválida', '033'),
('AT', 'Tipo/Número de Inscrição do Favorecido/Contribuinte Inválido', '033'),
('AU', 'Logradouro do Favorecido não Informado', '033'),
('AV', 'Número do Local do Favorecido não Informado', '033'),
('AW', 'Cidade do Favorecido não Informada', '033'),
('AX', 'CEP/Complemento do Favorecido Inválido', '033'),
('AY', 'Sigla do Estado do Favorecido Inválida', '033'),
('AZ', 'Código/Nome do Banco Depositário Inválido', '033'),
('A1', 'Código/Nome da Agência Depositária Inválido', '033'),
('A2', 'Finalidade Do Doc/Ted Inválida', '033'),
('A3', 'Banco/Tipo Registro/Cod Rem-Ret Inválido', '033'),
('A4', 'Registro Do Arquivo Remessa Não Identificado', '033'),
('A5', 'Registro Header Não Encontrado', '033'),
('A6', 'Registro Trailler Não Encontrado', '033'),
('A7', 'Remessa Sem Registros Detalhe', '033'),
('A8', 'Arquivo Com Mais De Um Registro Header', '033'),
('A9', 'Arquivo Com Mais De Um Registro Trailler', '033'),
('B1', 'Número do Documento Inválido(Seu Número)', '033'),
('B2', 'Nosso Número Inválido', '033'),
('BC', 'Nosso Número Inválido', '033'),
('BE', 'Alteração Efetuada com Sucesso', '033'),
('BF', 'Exclusão Efetuada com Sucesso', '033'),
('BG', 'Agência/Conta Impedida Legalmente', '033'),
('B1', 'Bloqueado pelo cliente', '033'),
('B3', 'Bloqueado pela cliente', '033'),
('B4', 'Bloqueado pela quitação de título da cobrança', '033'),
('B8', 'Bloqueado pela Validação de Tributos', '033'),
('CA', 'Código de barras - Código do Banco Inválido', '033');

--> Pagina 2
INSERT INTO pagamentos_elet_codigos_retornos (cod_retorno, descricao, cod_banco)
VALUES
('CB', 'Código de barras - Código da Moeda Inválido', '033'),
('CC', 'Código de barras - Dígito Verificador Geral Inválido', '033'),
('CD', 'Código de barras - Valor do Título Inválido', '033'),
('CE', 'Código de barras - Campo Livre Inválido', '033'),
('CF', 'Valor do Documento/Principal/menor que o mínimo Inválido', '033'),
('CH', 'Valor de Desconto Inválido', '033'),
('CI', 'Valor da Mora Inválido', '033'),
('CJ', 'Valor da Multa Inválido', '033'),
('CK', 'Valor do IR Inválido', '033'),
('CL', 'Valor do ISS Inválido', '033'),
('CM', 'Valor do Abatimento Inválido', '033'),
('CN', 'Valor do IOF Inválido', '033'),
('CO', 'Valor de Outras Deduções Inválido', '033'),
('CP', 'Valor de Outros Acréscimos Inválido', '033'),
('HA', 'Lote Não Aceito', '033'),
('HB', 'Inscrição da Empresa Inválida para o Contrato', '033'),
('HC', 'Convênio com a Empresa Inexistente/Inválido para o Contrato', '033'),
('HD', 'Agência/Conta Corrente da Empresa Inexistente/Inválida para o Contrato', '033'),
('HE', 'Tipo de Serviço Inválido para o Contrato', '033'),
('HF', 'Conta Corrente da Empresa com Saldo Insuficiente', '033'),
('HG', 'Lote de Serviço fora de Sequência', '033'),
('HH', 'Lote de Serviço Inválido', '033'),
('HI', 'Arquivo não aceito', '033'),
('HJ', 'Tipo de Registro Inválido', '033'),
('HL', 'Versão de Layout Inválida', '033'),
('HU', 'Data / hora de Envio Inválida', '033'),
('IA', 'Pagamento exclusive em Cartório.', '033'),
('IJ', 'Competência ou Período de Referência ou Número da Parcela invalido', '033'),
('IL', 'Código Pagamento / Receita não numérico ou com zeros', '033'),
('IM', 'Município Inválido', '033'),
('IN', 'Número Declaração inválido', '033'),
('IO', 'Número Etiqueta inválido', '033'),
('IP', 'Número Notificação inválido', '033'),
('IQ', 'Inscrição Estadual inválida', '033'),
('IS', 'Valor Honorários ou Outros Acréscimos invalido', '033'),
('IT', 'Período Apuração inválido', '033'),
('IU', 'Valor ou Percentual da Receita inválido', '033'),
('IV', 'Número referência inválida', '033'),
('PA', 'Pix não efetivado', '033'),
('PB', 'Transação interrompida devido a erro no PSP do Recebedor', '033'),
('PC', 'Número da conta transacional encerrada no PSP do Recebedor', '033'),
('PD', 'Tipo incorreto para a conta transacional especificada', '033'),
('PE', 'Tipo de transação não é suportado/autorizado na conta transacional especificada', '033'),
('PF', 'CPF/CNPJ do usuário recebedor não é consistente com o titular da conta transacional especificada', '033'),
('PG', 'CPF/CNPJ do usuário recebedor incorreto', '033'),
('PH', 'Ordem rejeitada pelo PSP do Recebedor', '033'),
('PI', 'ISPB do PSP do Pagador inválido ou inexistente', '033'),
('PJ', 'Chave não cadastrada no DICT', '033'),
('PK', 'Qr Code Inválido/Vencido', '033'),
('PL', 'Forma De Iniciação Inválida', '033'),
('PM', 'Chave inválida ou inválida para o Favorecido', '033'),
('PN', 'Chave De Pagamento Não Informada', '033'),
('TA', 'Lote não Aceito - Totais do Lote com Diferença', '033'),
('TB', 'Sequencial De Arq. Diverge Do Esperado', '033'),
('WC', 'Divergência na titularidade', '033'),
('XA', 'Seqüência De Seqüencial De Arquivo', '033'),
('XB', 'Número de Inscrição do Contribuinte Inválido', '033');

--> Pagina 3
INSERT INTO pagamentos_elet_codigos_retornos (cod_retorno, descricao, cod_banco)
VALUES
('XC', 'Código do Pagamento ou Competência ou Número de Inscrição Inválido', '033'),
('XF', 'Código do Pagamento, Competência não Numérico ou igual a zeros', '033'),
('YA', 'Título não Encontrado', '033'),
('YB', 'Identificação Registro Opcional Inválido', '033'),
('YC', 'Código Padrão Inválido', '033'),
('YD', 'Código de Ocorrência Inválido', '033'),
('YE', 'Complemento de Ocorrência Inválido', '033'),
('YF', 'Alegação já Informada', '033'),
('ZA', 'Transferência Devolvida', '033'),
('ZB', 'Transferência mesma titularidade não permitida', '033'),
('ZC', 'Código pagamento Tributo inválido', '033'),
('ZD', 'Competência Inválida', '033'),
('ZE', 'Título Bloqueado na base', '033'),
('ZF', 'Sistema em Contingência – Título com valor maior que referência', '033'),
('ZG', 'Sistema em Contingência – Título vencido (pagamento de cobrança)', '033'),
('ZH', 'Banco destino não Recebe DOC/Pix (pagamentos/transferências)', '033'),
('ZI', 'Sistema em contingência - Título indexado', '033'),
('ZJ', 'Beneficiário divergente', '033'),
('ZK', 'Limite de pagamentos parciais excedido', '033'),
('ZL', 'Título já liquidado', '033'),
('ZT', 'Valor “outras entidades” inválido', '033'),
('ZU', 'Sistema Origem Inválido', '033'),
('ZW', 'Banco Destino não recebe DOC', '033'),
('ZX', 'Banco Destino inoperante para DOC', '033'),
('ZY', 'Código do Histórico de Crédito Inválido', '033'),
('ZV', 'Autorização iniciada no Internet Banking', '033'),
('Z0', 'Conta com bloqueio*', '033'),
('Z1', 'Conta fechada. É necessário ativar a conta*', '033'),
('Z2', 'Conta com movimento controlado*', '033'),
('Z3', 'Conta cancelada*', '033'),
('Z4', 'Registro inconsistente (Título)*', '033'),
('Z5', 'Apresentação indevida (Título)*', '033'),
('Z6', 'Dados do destinatário inválidos*', '033'),
('Z7', 'Agência ou conta destinatária do crédito inválida*', '033'),
('Z8', 'Divergência na titularidade*', '033'),
('Z9', 'Conta destinatária do crédito encerrada*', '033'),
('99', 'Bloqueado Outros Motivos', '033');
