USE	DB_REPORT
GO

DECLARE   @DT_REFERENCIA	AS DATE
		, @DT_MES			AS INT
		, @DT_ANO			AS INT

SET		@DT_REFERENCIA		=	'2021-04-01'
SET		@DT_MES				=	DATEPART(MM, @DT_REFERENCIA)
SET		@DT_ANO				=	DATEPART(YYYY, @DT_REFERENCIA)




---SELECIONA BASE FA1P
DROP TABLE #TB_BASE_FA1P
SELECT 
DISTINCT  
		  ID_CLIENTE
		, CE	=	NULL
		, CPC	=	NULL
		, AF	=	NULL
		, PG	=	NULL
		, DIVIDA	
INTO	#TB_BASE_FA1P
FROM	DB_REPORT.DBO.TB_REL_SAFRA_AVON_REMESSA_ANALITICO	WITH(NOLOCK)
WHERE
		FILA_SEGMENTADA				= 'FA1P'
	AND DATEPART(MM, DT_ENTRADA)	=	@DT_MES

---SELECIONA PRODUCAO
DROP	TABLE	#TB_PRODUCAO
SELECT 
		  ID_CLIENTE
		, CE	=	MAX(CE)
		, CPC	=	MAX(CPC)
		, AF	=	MAX(AF)
INTO	#TB_PRODUCAO
FROM	DB_REPORT.DBO.TB_REL_HORA_HORA_TABULACAO_ANALITICO_BACKUP
WHERE	
			ID_CEDENTE			=	1
		AND DATA	BETWEEN '2021-04-01' AND '2021-04-30'
GROUP	BY
		ID_CLIENTE


UPDATE	#TB_BASE_FA1P
SET		  CE	=	P.CE
		, CPC	=	P.CPC
		, AF	=	P.AF
FROM	#TB_BASE_FA1P		F
		INNER JOIN
		#TB_PRODUCAO		P	
ON		F.ID_CLIENTE	=	P.ID_CLIENTE


UPDATE	#TB_BASE_FA1P
SET		PG	=	1
FROM	#TB_BASE_FA1P		F
		INNER JOIN
		DB_REPORT.DBO.TB_REL_HORA_HORA_ACORDO_ANALITICO_BACKUP	P	
ON		F.ID_CLIENTE	=	P.ID_CLIENTE
WHERE	
		P.DT_PAGAMENTO	BETWEEN '2021-04-01' AND '2021-04-30'
	AND P.ID_CEDENTE	=	1
	



------------ PEGA TABELA DE TENTATIVAS DE DISCAGEM DO MÊS DE ABRIL ------------

DROP TABLE 	#TB_DISCAGEM

SELECT TD.ID_CLIENTE,
		TERMINATOR_STATUS
INTO #TB_DISCAGEM 
FROM DB_DAILY..TB_AVON_PRINCIPAL_DISCAGEM_BACKUP TD WITH(NOLOCK)
WHERE TD.DT_REF BETWEEN '2021-04-01' AND '2021-04-30' 	

------------ PEGA SÓ AS RAs FA1P QUE TIVERAM TENTATIVAS  ------------
DROP TABLE 	#DISCAGEM

SELECT	TD.ID_CLIENTE,
		TERMINATOR_STATUS
INTO #DISCAGEM
FROM #TB_BASE_FA1P F
INNER JOIN  #TB_DISCAGEM TD WITH(NOLOCK)
ON F.ID_CLIENTE = TD.ID_CLIENTE
	


------------ PEGA INFORMAÇÕES DA OPERAÇÃO SOBRE AS RAs FA1P ------------
SELECT 
		  VALOR  = SUM (DIVIDA)	
		, MAILING_CPF	=	COUNT(DISTINCT ID_CLIENTE)
		, ALO	=	SUM(CE)
		, CPC	=	SUM(CPC)
FROM	#TB_BASE_FA1P	


------------ PEGA SÓ AS RAs FA1P QUE TIVERAM TENTATIVAS  ------------

SELECT COUNT(distinct ID_CLIENTE) AS TOTAL_DISCADOS 
FROM #DISCAGEM


------------ PEGA CLIENTES QUE NÃO CONFIRMARAM DADOS ------------

SELECT COUNT(1) AS TOTAL_NAO_CONFIRMA
FROM #DISCAGEM
WHERE TERMINATOR_STATUS IN (272,289)
