
IF OBJECT_ID('TEMPDB.DBO.#SCC','U')IS NOT NULL
DROP TABLE #SCC

SELECT       ID_CLIENTE,
             NM_CLIENTE_CEDENTE,
             NU_CPF_CNPJ,
             NM_NOME,
             ATRASO,
             QTD_CONTRATOS,
             SALDO_DEVEDOR,
             REGIAO
INTO #SCC
FROM SCC_WEDOO WITH(NOLOCK)
WHERE ID_CEDENTE = 1
AND DT_ULT_ACORDO_ATIVO IS NULL


IF OBJECT_ID('TEMPDB.DBO.#TELEFONE','U')IS NOT NULL
DROP TABLE #TELEFONE

SELECT  
      SC.ID_CLIENTE,
      UF = dbo.FNC_MIS_LOCALIZA_UF (MAX(TE.NU_DDD))

			          
INTO #TELEFONE 
FROM #SCC SC
INNER JOIN [172.20.1.63].[easycollector].[DBO].[TB_CLIENTE_TELEFONE] TE WITH(NOLOCK)
ON SC.ID_CLIENTE = TE.ID_CLIENTE
GROUP BY     SC.ID_CLIENTE
         

SELECT DISTINCT TOP 500*
FROM #SCC SC
INNER JOIN
     #TELEFONE TEL
ON TEL.ID_CLIENTE = SC.ID_CLIENTE 
WHERE UF LIKE '%SP%'
AND ATRASO BETWEEN 31 AND 60
ORDER BY SALDO_DEVEDOR DESC



SELECT UF,COUNT(*) AS TOTAL
FROM #TESTE
WHERE DT_PAGAMENTO IS NOT NULL
GROUP BY UF
ORDER BY COUNT (*) DESC