USE [THESYS_DEV]
GO

INSERT INTO [THESYS_HOMOLOGACAO]..[Tabela_Padrao]
           ([cod_tabelapadrao]
           ,[codigo]
           ,[descricao]
           ,[obs]
           ,[ativo]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device])

SELECT 
			[cod_tabelapadrao]
           ,[codigo]
           ,[descricao]
           ,[obs]
           ,[ativo]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
FROM [Tabela_Padrao]