USE [THESYS_DEV]
GO

INSERT INTO THESYS_PRODUCAO..[Tipos_Produtos]
           ([descricao]
           ,[codigo]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device])
select 
			[descricao]
           ,[codigo]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
from [Tipos_Produtos]