USE [THESYS_DEV]
GO

INSERT INTO THESYS_PRODUCAO..[UFS]
           ([CODIGO]
           ,[DESCRICAO]
           ,[UF]
           ,[cod_ibge]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device])
select 
			[CODIGO]
           ,[DESCRICAO]
           ,[UF]
           ,[cod_ibge]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
from [UFS]