
Use Thesys_Dev
Go

Drop Table If Exists #BasePedVendaItem 
Select 
	Empresa = 'Rubberon'
,	*
,	Pk = Trim(Cod_Empresa) + Trim(Cod_PedidoVenda)
Into #BasePedVendaItem
From OpenQuery([Mbm_Rubberon],'
Select 
  cod_pedidovenda, 
  cod_empresa, 
  cod_etapa, 
  cod_taxasucesso, 
  cod_prioridade, 
  cod_motcancelamento, 
  os_empresa, 
  os_ordemservico, 
  sequencia, 
  cod_pedidocompra, 
  os_sequencia, 
  cod_tabelapreco, 
  seq_pedcompra, 
  cod_serie, 
  cod_natoperacao, 
  cod_item, 
  qtd_pedida, 
  qtd_atendida, 
  preco_vendatabela, 
  qtd_liberada, 
  preco_venda, 
  aliq_icms, 
  preco_reposicao, 
  aliq_ipi, 
  custo_reposicao, 
  custo_medio, 
  custo_standard, 
  valor_descto, 
  perc_base_icms, 
  perc_descto, 
  aliq_iss, 
  situacao_item, 
  dt_inclusao, 
  dt_cancelado, 
  base_icms, 
  usuario_cancelou, 
  base_icms_sub, 
  motivo_cancelou, 
  valor_total, 
  dt_solicitada, 
  valor_icms, 
  dt_suspenso, 
  valor_icms_sub, 
  dt_atendida, 
  valor_ipi, 
  usuario_suspendeu, 
  valor_iss, 
  motivo_suspendeu, 
  usar_flag_fat, 
  cast(obs as character varying(1000)) as obs, 
  item_descricao, 
  periodo_consumo, 
  referencia, 
  desenho, 
  amostra, 
  dt_prazoentcot, 
  desenv_codigo, 
  desenv_descricao, 
  desenv_unidade, 
  desenv_periodo, 
  lote_minimo, 
  diametro_coluna, 
  valor_bcalc_repasseicms, 
  perc_repasseicms, 
  valor_repasseicms, 
  valor_bcalc_zonafranca, 
  desc_zonafranca, 
  valor_zonafranca, 
  valor_bcalc_iss, 
  iss_perc_reducao, 
  aprec_custoreposicao, 
  valor_ferramental, 
  valor_bcalc_pis, 
  valor_bcalc_cofins, 
  valor_pis, 
  valor_cofins, 
  aliq_pis, 
  aliq_cofins, 
  pis_codtributacao, 
  cofins_codtributacao, 
  cod_usuario, 
  dt_alteracao, 
  item_geramanga, 
  percentual_manga, 
  cod_unidadevenda, 
  fator_conversao, 
  qtd_venda, 
  preco_unitvenda, 
  opcional, 
  preco_vdacomimpostoipi, 
  preco_vdatabelacomipi, 
  preco_unitvdacomipi, 
  tipo_descto, 
  taxa_tabelaprazo, 
  seq_relnecessidade, 
  set_relnecessidade, 
  dt_change, 
  perc_confnat1, 
  perc_confnat2, 
  auxiliar_string1, 
  auxiliar_string2, 
  cast(obs_itemnf as character varying(1000)) as obs_itemnf , 
  cliente_retirou, 
  auxiliar_float1, 
  auxiliar_float2, 
  nro_pedidovendaint, 
  preco_vendatabela2, 
  pvi_tipoprecosugerir, 
  cod_ambiente, 
  cod_sugestao, 
  descricao_sugestao, 
  ambiente_apelido, 
  qtd_projeto, 
  percentual_perda, 
  tipo_percentualperda, 
  tipo_sugestaoambiente, 
  comprimento, 
  largura, 
  cod_tipopedvenda, 
  seq_pedcompra_item, 
  perc_base_icms_subst, 
  cod_tribdifal, 
  difal, 
  bc_icmsufdest, 
  aliq_icmsfcp, 
  aliq_icmsufdest, 
  aliq_icmsufint, 
  aliq_icmsufpart, 
  valor_icmsfcp, 
  valor_icmsufdest, 
  valor_icmsufremet, 
  cod_moeda, 
  cod_tributacao, 
  sittributaria, 
  csosn, 
  aliq_icmsst, 
  perc_icmsst, 
  perc_basefcpicms, 
  aliq_fcpicms, 
  valor_basefcpicms, 
  valor_fcpicms, 
  perc_basefcpicmsst, 
  aliq_fcpicmsst, 
  valor_basefcpicmsst, 
  valor_fcpicmsst, 
  cod_tributacaofcpicms, 
  cod_tributacaofcpicmsst, 
  esporc_codempresa, 
  esporc_coddeposito, 
  nro_pedcliente, 
  cod_concorrente, 
  cod_itemconcorrente, 
  perc_icmsoppresumido_subst, 
  valor_icmsoppresumido_subst, 
  bcst_addalqfcp, 
  cod_maqequip, 
  acomp_nroreferenciaterc, 
  acomp_nroimportacao, 
  acomp_observacao, 
  acomp_dtembarque, 
  acomp_dtchegada, 
  acomp_dtnacionalizacao, 
  acomp_dtrecebimento, 
  acomp_localestoque, 
  acomp_qtdesolicitada, 
  valor_pautapmc, 
  modbc_icmsst, 
  possui_comissaoespecial, 
  perc_comissaoespecial, 
  valor_fretenaodestacado, 
  sequencia_exibicao, 
  valor_fcpdiferido, 
  valor_fcpefetivo, 
  cod_tributacaofcpdif, 
  perc_basefcpdif, 
  aliq_fcpdif, 
  preco_medio, 
  valor_basefcpdif, 
  triangular_vendafutura, 
  ipi_perc_reducaoaliq 
From pedvenda_item
')

Union All

Select 
	Empresa = 'Poliresinas'
,	*
,	Pk = Trim(Cod_Empresa) + Trim(Cod_PedidoVenda)
From OpenQuery([Mbm_Poliresinas],'
Select 
  cod_pedidovenda, 
  cod_empresa, 
  cod_etapa, 
  cod_taxasucesso, 
  cod_prioridade, 
  cod_motcancelamento, 
  os_empresa, 
  os_ordemservico, 
  sequencia, 
  cod_pedidocompra, 
  os_sequencia, 
  cod_tabelapreco, 
  seq_pedcompra, 
  cod_serie, 
  cod_natoperacao, 
  cod_item, 
  qtd_pedida, 
  qtd_atendida, 
  preco_vendatabela, 
  qtd_liberada, 
  preco_venda, 
  aliq_icms, 
  preco_reposicao, 
  aliq_ipi, 
  custo_reposicao, 
  custo_medio, 
  custo_standard, 
  valor_descto, 
  perc_base_icms, 
  perc_descto, 
  aliq_iss, 
  situacao_item, 
  dt_inclusao, 
  dt_cancelado, 
  base_icms, 
  usuario_cancelou, 
  base_icms_sub, 
  motivo_cancelou, 
  valor_total, 
  dt_solicitada, 
  valor_icms, 
  dt_suspenso, 
  valor_icms_sub, 
  dt_atendida, 
  valor_ipi, 
  usuario_suspendeu, 
  valor_iss, 
  motivo_suspendeu, 
  usar_flag_fat, 
  cast(obs as character varying(1000)) as obs, 
  item_descricao, 
  periodo_consumo, 
  referencia, 
  desenho, 
  amostra, 
  dt_prazoentcot, 
  desenv_codigo, 
  desenv_descricao, 
  desenv_unidade, 
  desenv_periodo, 
  lote_minimo, 
  diametro_coluna, 
  valor_bcalc_repasseicms, 
  perc_repasseicms, 
  valor_repasseicms, 
  valor_bcalc_zonafranca, 
  desc_zonafranca, 
  valor_zonafranca, 
  valor_bcalc_iss, 
  iss_perc_reducao, 
  aprec_custoreposicao, 
  valor_ferramental, 
  valor_bcalc_pis, 
  valor_bcalc_cofins, 
  valor_pis, 
  valor_cofins, 
  aliq_pis, 
  aliq_cofins, 
  pis_codtributacao, 
  cofins_codtributacao, 
  cod_usuario, 
  dt_alteracao, 
  item_geramanga, 
  percentual_manga, 
  cod_unidadevenda, 
  fator_conversao, 
  qtd_venda, 
  preco_unitvenda, 
  opcional, 
  preco_vdacomimpostoipi, 
  preco_vdatabelacomipi, 
  preco_unitvdacomipi, 
  tipo_descto, 
  taxa_tabelaprazo, 
  seq_relnecessidade, 
  set_relnecessidade, 
  dt_change, 
  perc_confnat1, 
  perc_confnat2, 
  auxiliar_string1, 
  auxiliar_string2, 
  cast(obs_itemnf as character varying(1000)) as obs_itemnf , 
  cliente_retirou, 
  auxiliar_float1, 
  auxiliar_float2, 
  nro_pedidovendaint, 
  preco_vendatabela2, 
  pvi_tipoprecosugerir, 
  cod_ambiente, 
  cod_sugestao, 
  descricao_sugestao, 
  ambiente_apelido, 
  qtd_projeto, 
  percentual_perda, 
  tipo_percentualperda, 
  tipo_sugestaoambiente, 
  comprimento, 
  largura, 
  cod_tipopedvenda, 
  seq_pedcompra_item, 
  perc_base_icms_subst, 
  cod_tribdifal, 
  difal, 
  bc_icmsufdest, 
  aliq_icmsfcp, 
  aliq_icmsufdest, 
  aliq_icmsufint, 
  aliq_icmsufpart, 
  valor_icmsfcp, 
  valor_icmsufdest, 
  valor_icmsufremet, 
  cod_moeda, 
  cod_tributacao, 
  sittributaria, 
  csosn, 
  aliq_icmsst, 
  perc_icmsst, 
  perc_basefcpicms, 
  aliq_fcpicms, 
  valor_basefcpicms, 
  valor_fcpicms, 
  perc_basefcpicmsst, 
  aliq_fcpicmsst, 
  valor_basefcpicmsst, 
  valor_fcpicmsst, 
  cod_tributacaofcpicms, 
  cod_tributacaofcpicmsst, 
  esporc_codempresa, 
  esporc_coddeposito, 
  nro_pedcliente, 
  cod_concorrente, 
  cod_itemconcorrente, 
  perc_icmsoppresumido_subst, 
  valor_icmsoppresumido_subst, 
  bcst_addalqfcp, 
  cod_maqequip, 
  acomp_nroreferenciaterc, 
  acomp_nroimportacao, 
  acomp_observacao, 
  acomp_dtembarque, 
  acomp_dtchegada, 
  acomp_dtnacionalizacao, 
  acomp_dtrecebimento, 
  acomp_localestoque, 
  acomp_qtdesolicitada, 
  valor_pautapmc, 
  modbc_icmsst, 
  possui_comissaoespecial, 
  perc_comissaoespecial, 
  valor_fretenaodestacado, 
  sequencia_exibicao, 
  valor_fcpdiferido, 
  valor_fcpefetivo, 
  cod_tributacaofcpdif, 
  perc_basefcpdif, 
  aliq_fcpdif, 
  preco_medio, 
  valor_basefcpdif, 
  triangular_vendafutura, 
  ipi_perc_reducaoaliq 
From pedvenda_item
')

Union All

Select 
	Empresa = 'Nortebag'
,	*
,	Pk = Trim(Cod_Empresa) + Trim(Cod_PedidoVenda)
From OpenQuery([Mbm_Nortebag],'
Select 
  cod_pedidovenda, 
  cod_empresa, 
  cod_etapa, 
  cod_taxasucesso, 
  cod_prioridade, 
  cod_motcancelamento, 
  os_empresa, 
  os_ordemservico, 
  sequencia, 
  cod_pedidocompra, 
  os_sequencia, 
  cod_tabelapreco, 
  seq_pedcompra, 
  cod_serie, 
  cod_natoperacao, 
  cod_item, 
  qtd_pedida, 
  qtd_atendida, 
  preco_vendatabela, 
  qtd_liberada, 
  preco_venda, 
  aliq_icms, 
  preco_reposicao, 
  aliq_ipi, 
  custo_reposicao, 
  custo_medio, 
  custo_standard, 
  valor_descto, 
  perc_base_icms, 
  perc_descto, 
  aliq_iss, 
  situacao_item, 
  dt_inclusao, 
  dt_cancelado, 
  base_icms, 
  usuario_cancelou, 
  base_icms_sub, 
  motivo_cancelou, 
  valor_total, 
  dt_solicitada, 
  valor_icms, 
  dt_suspenso, 
  valor_icms_sub, 
  dt_atendida, 
  valor_ipi, 
  usuario_suspendeu, 
  valor_iss, 
  motivo_suspendeu, 
  usar_flag_fat, 
  cast(obs as character varying(1000)) as obs, 
  item_descricao, 
  periodo_consumo, 
  referencia, 
  desenho, 
  amostra, 
  dt_prazoentcot, 
  desenv_codigo, 
  desenv_descricao, 
  desenv_unidade, 
  desenv_periodo, 
  lote_minimo, 
  diametro_coluna, 
  valor_bcalc_repasseicms, 
  perc_repasseicms, 
  valor_repasseicms, 
  valor_bcalc_zonafranca, 
  desc_zonafranca, 
  valor_zonafranca, 
  valor_bcalc_iss, 
  iss_perc_reducao, 
  aprec_custoreposicao, 
  valor_ferramental, 
  valor_bcalc_pis, 
  valor_bcalc_cofins, 
  valor_pis, 
  valor_cofins, 
  aliq_pis, 
  aliq_cofins, 
  pis_codtributacao, 
  cofins_codtributacao, 
  cod_usuario, 
  dt_alteracao, 
  item_geramanga, 
  percentual_manga, 
  cod_unidadevenda, 
  fator_conversao, 
  qtd_venda, 
  preco_unitvenda, 
  opcional, 
  preco_vdacomimpostoipi, 
  preco_vdatabelacomipi, 
  preco_unitvdacomipi, 
  tipo_descto, 
  taxa_tabelaprazo, 
  seq_relnecessidade, 
  set_relnecessidade, 
  dt_change, 
  perc_confnat1, 
  perc_confnat2, 
  auxiliar_string1, 
  auxiliar_string2, 
  cast(obs_itemnf as character varying(1000)) as obs_itemnf , 
  cliente_retirou, 
  auxiliar_float1, 
  auxiliar_float2, 
  nro_pedidovendaint, 
  preco_vendatabela2, 
  pvi_tipoprecosugerir, 
  cod_ambiente, 
  cod_sugestao, 
  descricao_sugestao, 
  ambiente_apelido, 
  qtd_projeto, 
  percentual_perda, 
  tipo_percentualperda, 
  tipo_sugestaoambiente, 
  comprimento, 
  largura, 
  cod_tipopedvenda, 
  seq_pedcompra_item, 
  perc_base_icms_subst, 
  cod_tribdifal, 
  difal, 
  bc_icmsufdest, 
  aliq_icmsfcp, 
  aliq_icmsufdest, 
  aliq_icmsufint, 
  aliq_icmsufpart, 
  valor_icmsfcp, 
  valor_icmsufdest, 
  valor_icmsufremet, 
  cod_moeda, 
  cod_tributacao, 
  sittributaria, 
  csosn, 
  aliq_icmsst, 
  perc_icmsst, 
  perc_basefcpicms, 
  aliq_fcpicms, 
  valor_basefcpicms, 
  valor_fcpicms, 
  perc_basefcpicmsst, 
  aliq_fcpicmsst, 
  valor_basefcpicmsst, 
  valor_fcpicmsst, 
  cod_tributacaofcpicms, 
  cod_tributacaofcpicmsst, 
  esporc_codempresa, 
  esporc_coddeposito, 
  nro_pedcliente, 
  cod_concorrente, 
  cod_itemconcorrente, 
  perc_icmsoppresumido_subst, 
  valor_icmsoppresumido_subst, 
  bcst_addalqfcp, 
  cod_maqequip, 
  acomp_nroreferenciaterc, 
  acomp_nroimportacao, 
  acomp_observacao, 
  acomp_dtembarque, 
  acomp_dtchegada, 
  acomp_dtnacionalizacao, 
  acomp_dtrecebimento, 
  acomp_localestoque, 
  acomp_qtdesolicitada, 
  valor_pautapmc, 
  modbc_icmsst, 
  possui_comissaoespecial, 
  perc_comissaoespecial, 
  valor_fretenaodestacado, 
  sequencia_exibicao, 
  valor_fcpdiferido, 
  valor_fcpefetivo, 
  cod_tributacaofcpdif, 
  perc_basefcpdif, 
  aliq_fcpdif, 
  preco_medio, 
  valor_basefcpdif, 
  triangular_vendafutura, 
  ipi_perc_reducaoaliq 
From pedvenda_item
')

Union All

Select 
	Empresa = 'Mg_Polimeros'
,	*
,	Pk = Trim(Cod_Empresa) + Trim(Cod_PedidoVenda)
From OpenQuery([Mbm_Mg_Polimeros],'
Select 
  cod_pedidovenda, 
  cod_empresa, 
  cod_etapa, 
  cod_taxasucesso, 
  cod_prioridade, 
  cod_motcancelamento, 
  os_empresa, 
  os_ordemservico, 
  sequencia, 
  cod_pedidocompra, 
  os_sequencia, 
  cod_tabelapreco, 
  seq_pedcompra, 
  cod_serie, 
  cod_natoperacao, 
  cod_item, 
  qtd_pedida, 
  qtd_atendida, 
  preco_vendatabela, 
  qtd_liberada, 
  preco_venda, 
  aliq_icms, 
  preco_reposicao, 
  aliq_ipi, 
  custo_reposicao, 
  custo_medio, 
  custo_standard, 
  valor_descto, 
  perc_base_icms, 
  perc_descto, 
  aliq_iss, 
  situacao_item, 
  dt_inclusao, 
  dt_cancelado, 
  base_icms, 
  usuario_cancelou, 
  base_icms_sub, 
  motivo_cancelou, 
  valor_total, 
  dt_solicitada, 
  valor_icms, 
  dt_suspenso, 
  valor_icms_sub, 
  dt_atendida, 
  valor_ipi, 
  usuario_suspendeu, 
  valor_iss, 
  motivo_suspendeu, 
  usar_flag_fat, 
  cast(obs as character varying(1000)) as obs, 
  item_descricao, 
  periodo_consumo, 
  referencia, 
  desenho, 
  amostra, 
  dt_prazoentcot, 
  desenv_codigo, 
  desenv_descricao, 
  desenv_unidade, 
  desenv_periodo, 
  lote_minimo, 
  diametro_coluna, 
  valor_bcalc_repasseicms, 
  perc_repasseicms, 
  valor_repasseicms, 
  valor_bcalc_zonafranca, 
  desc_zonafranca, 
  valor_zonafranca, 
  valor_bcalc_iss, 
  iss_perc_reducao, 
  aprec_custoreposicao, 
  valor_ferramental, 
  valor_bcalc_pis, 
  valor_bcalc_cofins, 
  valor_pis, 
  valor_cofins, 
  aliq_pis, 
  aliq_cofins, 
  pis_codtributacao, 
  cofins_codtributacao, 
  cod_usuario, 
  dt_alteracao, 
  item_geramanga, 
  percentual_manga, 
  cod_unidadevenda, 
  fator_conversao, 
  qtd_venda, 
  preco_unitvenda, 
  opcional, 
  preco_vdacomimpostoipi, 
  preco_vdatabelacomipi, 
  preco_unitvdacomipi, 
  tipo_descto, 
  taxa_tabelaprazo, 
  seq_relnecessidade, 
  set_relnecessidade, 
  dt_change, 
  perc_confnat1, 
  perc_confnat2, 
  auxiliar_string1, 
  auxiliar_string2, 
  cast(obs_itemnf as character varying(1000)) as obs_itemnf , 
  cliente_retirou, 
  auxiliar_float1, 
  auxiliar_float2, 
  nro_pedidovendaint, 
  preco_vendatabela2, 
  pvi_tipoprecosugerir, 
  cod_ambiente, 
  cod_sugestao, 
  descricao_sugestao, 
  ambiente_apelido, 
  qtd_projeto, 
  percentual_perda, 
  tipo_percentualperda, 
  tipo_sugestaoambiente, 
  comprimento, 
  largura, 
  cod_tipopedvenda, 
  seq_pedcompra_item, 
  perc_base_icms_subst, 
  cod_tribdifal, 
  difal, 
  bc_icmsufdest, 
  aliq_icmsfcp, 
  aliq_icmsufdest, 
  aliq_icmsufint, 
  aliq_icmsufpart, 
  valor_icmsfcp, 
  valor_icmsufdest, 
  valor_icmsufremet, 
  cod_moeda, 
  cod_tributacao, 
  sittributaria, 
  csosn, 
  aliq_icmsst, 
  perc_icmsst, 
  perc_basefcpicms, 
  aliq_fcpicms, 
  valor_basefcpicms, 
  valor_fcpicms, 
  perc_basefcpicmsst, 
  aliq_fcpicmsst, 
  valor_basefcpicmsst, 
  valor_fcpicmsst, 
  cod_tributacaofcpicms, 
  cod_tributacaofcpicmsst, 
  esporc_codempresa, 
  esporc_coddeposito, 
  nro_pedcliente, 
  cod_concorrente, 
  cod_itemconcorrente, 
  perc_icmsoppresumido_subst, 
  valor_icmsoppresumido_subst, 
  bcst_addalqfcp, 
  cod_maqequip, 
  acomp_nroreferenciaterc, 
  acomp_nroimportacao, 
  acomp_observacao, 
  acomp_dtembarque, 
  acomp_dtchegada, 
  acomp_dtnacionalizacao, 
  acomp_dtrecebimento, 
  acomp_localestoque, 
  acomp_qtdesolicitada, 
  valor_pautapmc, 
  modbc_icmsst, 
  possui_comissaoespecial, 
  perc_comissaoespecial, 
  valor_fretenaodestacado, 
  sequencia_exibicao, 
  valor_fcpdiferido, 
  valor_fcpefetivo, 
  cod_tributacaofcpdif, 
  perc_basefcpdif, 
  aliq_fcpdif, 
  preco_medio, 
  valor_basefcpdif, 
  triangular_vendafutura, 
  ipi_perc_reducaoaliq 
From pedvenda_item
Where Cod_Empresa != ''300''
')

Union All

Select 
	Empresa = 'Polirex'
,	*
,	Pk = Trim(Cod_Empresa) + Trim(Cod_PedidoVenda)
From OpenQuery([Mbm_Polirex],'
Select 
  cod_pedidovenda, 
  cod_empresa, 
  cod_etapa, 
  cod_taxasucesso, 
  cod_prioridade, 
  cod_motcancelamento, 
  os_empresa, 
  os_ordemservico, 
  sequencia, 
  cod_pedidocompra, 
  os_sequencia, 
  cod_tabelapreco, 
  seq_pedcompra, 
  cod_serie, 
  cod_natoperacao, 
  cod_item, 
  qtd_pedida, 
  qtd_atendida, 
  preco_vendatabela, 
  qtd_liberada, 
  preco_venda, 
  aliq_icms, 
  preco_reposicao, 
  aliq_ipi, 
  custo_reposicao, 
  custo_medio, 
  custo_standard, 
  valor_descto, 
  perc_base_icms, 
  perc_descto, 
  aliq_iss, 
  situacao_item, 
  dt_inclusao, 
  dt_cancelado, 
  base_icms, 
  usuario_cancelou, 
  base_icms_sub, 
  motivo_cancelou, 
  valor_total, 
  dt_solicitada, 
  valor_icms, 
  dt_suspenso, 
  valor_icms_sub, 
  dt_atendida, 
  valor_ipi, 
  usuario_suspendeu, 
  valor_iss, 
  motivo_suspendeu, 
  usar_flag_fat, 
  cast(obs as character varying(1000)) as obs, 
  item_descricao, 
  periodo_consumo, 
  referencia, 
  desenho, 
  amostra, 
  dt_prazoentcot, 
  desenv_codigo, 
  desenv_descricao, 
  desenv_unidade, 
  desenv_periodo, 
  lote_minimo, 
  diametro_coluna, 
  valor_bcalc_repasseicms, 
  perc_repasseicms, 
  valor_repasseicms, 
  valor_bcalc_zonafranca, 
  desc_zonafranca, 
  valor_zonafranca, 
  valor_bcalc_iss, 
  iss_perc_reducao, 
  aprec_custoreposicao, 
  valor_ferramental, 
  valor_bcalc_pis, 
  valor_bcalc_cofins, 
  valor_pis, 
  valor_cofins, 
  aliq_pis, 
  aliq_cofins, 
  pis_codtributacao, 
  cofins_codtributacao, 
  cod_usuario, 
  dt_alteracao, 
  item_geramanga, 
  percentual_manga, 
  cod_unidadevenda, 
  fator_conversao, 
  qtd_venda, 
  preco_unitvenda, 
  opcional, 
  preco_vdacomimpostoipi, 
  preco_vdatabelacomipi, 
  preco_unitvdacomipi, 
  tipo_descto, 
  taxa_tabelaprazo, 
  seq_relnecessidade, 
  set_relnecessidade, 
  dt_change, 
  perc_confnat1, 
  perc_confnat2, 
  auxiliar_string1, 
  auxiliar_string2, 
  cast(obs_itemnf as character varying(1000)) as obs_itemnf , 
  cliente_retirou, 
  auxiliar_float1, 
  auxiliar_float2, 
  nro_pedidovendaint, 
  preco_vendatabela2, 
  pvi_tipoprecosugerir, 
  cod_ambiente, 
  cod_sugestao, 
  descricao_sugestao, 
  ambiente_apelido, 
  qtd_projeto, 
  percentual_perda, 
  tipo_percentualperda, 
  tipo_sugestaoambiente, 
  comprimento, 
  largura, 
  cod_tipopedvenda, 
  seq_pedcompra_item, 
  perc_base_icms_subst, 
  cod_tribdifal, 
  difal, 
  bc_icmsufdest, 
  aliq_icmsfcp, 
  aliq_icmsufdest, 
  aliq_icmsufint, 
  aliq_icmsufpart, 
  valor_icmsfcp, 
  valor_icmsufdest, 
  valor_icmsufremet, 
  cod_moeda, 
  cod_tributacao, 
  sittributaria, 
  csosn, 
  aliq_icmsst, 
  perc_icmsst, 
  perc_basefcpicms, 
  aliq_fcpicms, 
  valor_basefcpicms, 
  valor_fcpicms, 
  perc_basefcpicmsst, 
  aliq_fcpicmsst, 
  valor_basefcpicmsst, 
  valor_fcpicmsst, 
  cod_tributacaofcpicms, 
  cod_tributacaofcpicmsst, 
  esporc_codempresa, 
  esporc_coddeposito, 
  nro_pedcliente, 
  cod_concorrente, 
  cod_itemconcorrente, 
  perc_icmsoppresumido_subst, 
  valor_icmsoppresumido_subst, 
  bcst_addalqfcp, 
  cod_maqequip, 
  acomp_nroreferenciaterc, 
  acomp_nroimportacao, 
  acomp_observacao, 
  acomp_dtembarque, 
  acomp_dtchegada, 
  acomp_dtnacionalizacao, 
  acomp_dtrecebimento, 
  acomp_localestoque, 
  acomp_qtdesolicitada, 
  valor_pautapmc, 
  modbc_icmsst, 
  possui_comissaoespecial, 
  perc_comissaoespecial, 
  valor_fretenaodestacado, 
  sequencia_exibicao, 
  valor_fcpdiferido, 
  valor_fcpefetivo, 
  cod_tributacaofcpdif, 
  perc_basefcpdif, 
  aliq_fcpdif, 
  preco_medio, 
  valor_basefcpdif, 
  triangular_vendafutura, 
  ipi_perc_reducaoaliq 
From pedvenda_item
')

 --> 12.202
Drop Table If Exists #Itens_Company
Select 
	Itens_Empresas.*
,	Itens.descricao
Into #Itens_Company
From Itens_Empresas
Left Join Itens On Itens.id_item = Itens_Empresas.id_item

Select 
	[id_pedido]				= Vendas_Pedidos.id_pedido
,	[sequencia]
,	[pedido_cliente]
,	[dt_solicitada]
,	[dt_entrega]
,	[id_natureza_operacao]  = Natureza_Operacao.id_NaturezaOperacao
,	[id_item]				= #Itens_Company.id_item
,	[qtd_un_padrao]			= qtd_pedida		
,	[qtd_atendida]			
,	[descricao]				= #Itens_Company.descricao
,	[preco_venda]
,	[valor_produtos]		= valor_total -- Validar
,	fato.[aliq_icms]
,	fato.[aliq_ipi]
,	fato.[aliq_pis]
,	fato.[aliq_cofins]
,	fato.[aliq_iss]
,	[custo_standard]
,	[perc_base_icms]
,	[base_icms]
,	[valor_icms]
,	[valor_bcalc_pis]
,	[valor_cofins]
,	[situacao_item]
,	[valor_total]
,	[valor_ipi]
,	[lote_minimo]
,	[valor_bcalc_zonafranca]
,	[desc_zonafranca]
,	[valor_zonafranca]
,	[valor_bcalc_cofins]
,	[valor_pis]
,	[pis_codtributacao]
,	[cofins_codtributacao]
,	[id_unidade]
,	[id_unidade_venda]
,	[cod_unidadevenda]
,	[fator_conversao]
,	[qtd_venda]
,	[preco_unitvenda]
,	[id_moeda]
,	[id_tributacao]
,	[CST]
,	[desc_nfiscal]
,	[obs_itemnf]
,	[obs_complemento_nf]
,	[obs]
,	[id_item_logistica]
,	[incl_data]
,	[incl_user]
,	[incl_device]
,	[modi_data]
,	[modi_user]
,	[modi_device]
,	[excl_data]
,	[excl_user]
,	[excl_device]
,	[id_origem_merc]
From #BasePedVendaItem Fato --> 46.243
Inner Join Empresas			 On  Empresas.Codigo_Antigo			    = Fato.Cod_Empresa			Collate latin1_general_ci_ai 
Left  Join Vendas_Pedidos    On  Vendas_Pedidos.Pk				    = Fato.Pk					Collate latin1_general_ci_ai 
Left  Join Natureza_Operacao On  Natureza_Operacao.cod_natoperacao  = Fato.cod_natoperacao		Collate latin1_general_ci_ai 
							 And Natureza_Operacao.id_empresa_grupo = Empresas.Id_Empresa_Grupo
Left  Join #Itens_Company    On  #Itens_Company.cod_reduzido_antigo = Fato.cod_item				Collate latin1_general_ci_ai 
							 And #Itens_Company.id_empresa_grupo    = Empresas.Id_Empresa_Grupo
	




SELECT COUNT(DISTINCT COD_PEDIDOVENDA), COD_EMPRESA, SEQUENCIA --> Chave Unica
FROM #BasePedVendaItem
GROUP BY COD_EMPRESA, SEQUENCIA

select *
from clifor
where razao like '%o pro%'

Insert Into [dbo].[Vendas_Pedidos_Itens]
           ([id_pedido]
           ,[sequencia]
           ,[pedido_cliente]
           ,[dt_solicitada]
           ,[dt_entrega]
           ,[id_natureza_operacao]
           ,[id_item]
           ,[qtd_un_padrao]
           ,[qtd_atendida]
           ,[descricao]
           ,[preco_venda]
           ,[valor_produtos]
           ,[aliq_icms]
           ,[aliq_ipi]
           ,[aliq_pis]
           ,[aliq_cofins]
           ,[aliq_iss]
           ,[custo_standard]
           ,[perc_base_icms]
           ,[base_icms]
           ,[valor_icms]
           ,[valor_bcalc_pis]
           ,[valor_cofins]
           ,[situacao_item]
           ,[valor_total]
           ,[valor_ipi]
           ,[lote_minimo]
           ,[valor_bcalc_zonafranca]
           ,[desc_zonafranca]
           ,[valor_zonafranca]
           ,[valor_bcalc_cofins]
           ,[valor_pis]
           ,[pis_codtributacao]
           ,[cofins_codtributacao]
           ,[id_unidade]
           ,[id_unidade_venda]
           ,[cod_unidadevenda]
           ,[fator_conversao]
           ,[qtd_venda]
           ,[preco_unitvenda]
           ,[id_moeda]
           ,[id_tributacao]
           ,[CST]
           ,[desc_nfiscal]
           ,[obs_itemnf]
           ,[obs_complemento_nf]
           ,[obs]
           ,[id_item_logistica]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
           ,[id_origem_merc])