USE [THESYS_DEV]
GO

INSERT INTO THESYS_PRODUCAO..[Vendas_Tipos_Pedido]
           ([cod_tipovenda]
           ,[descricao]
           ,[ativo]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device])
select 
[cod_tipovenda]
           ,[descricao]
           ,[ativo]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
from [Vendas_Tipos_Pedido]