

SELECT DISTINCT ST.[NAME]
	,STP.ROWS
	,STP.ROWS_SAMPLED
	,' UPDATE STATISTICS ' + '[' + SS.NAME + ']' + '.[' + OBJECT_NAME(ST.OBJECT_ID) + ']' + ' ' + '[' + ST.NAME + ']' + ' WITH FULLSCAN'
FROM SYS.STATS AS ST
CROSS APPLY SYS.DM_DB_STATS_PROPERTIES(ST.OBJECT_ID, ST.STATS_ID) AS STP
JOIN SYS.TABLES STA ON ST.[OBJECT_ID] = STA.OBJECT_ID
JOIN SYS.SCHEMAS SS ON SS.SCHEMA_ID   = STA.SCHEMA_ID
WHERE STA.NAME IN ('TB_DS_CALLFLEX_MES_PICPAY')
ORDER BY [ROWS] DESC