
DROP TABLE IF EXISTS #CONTROLE_CONSULTA 
SELECT
	KILL_ID		=  'KILL' + ' ' + CONVERT(VARCHAR,SPID)
,	STATUS		=	IIF(STATUS = 'SLEEPING', 'MIMINDO', 'ATIVA')
,	USUARIO		=	LOGINAME
,	DURACAO		=	CONVERT(TIME,CONVERT(DATETIME,(DATEDIFF(SECOND,CONVERT(TIME,LOGIN_TIME), CONVERT(TIME,GETDATE()))/60.0/1440.0)))                     
,	CPU
,	LOGIN_TIME
,	COMPUTADOR  =	HOSTNAME
,	APLICATIVO  =	PROGRAM_NAME
INTO #CONTROLE_CONSULTA
FROM MASTER.DBO.SYSPROCESSES
WHERE LOGINAME	!=	  'ATMATEC\POWERBI'
AND CPU			!=	  '0'

SELECT *
,		KILL_CONSUL_ATIVA = IIF(LEFT(DURACAO,2) >= 1 AND STATUS = 'ATIVA',   KILL_ID, '')
,		KILL_CONSUL_SLEP  = IIF(LEFT(DURACAO,2) >= 1 AND STATUS = 'MIMINDO', KILL_ID, '')
FROM #CONTROLE_CONSULTA
WHERE STATUS != 'ATIVA'
