
USE THESYS_DEV 
GO

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/*																								*/
/* PROGRAMADOR: KAIKE NATAN									                                    */
/* VERSAO     : DATA: 27/06/2024																*/
/* DESCRICAO  : SCRIP DE LIMPAR LOG DOS DATABASES									  		    */
/*																								*/
/*	ALTERACAO                                                                                   */
/*        2. PROGRAMADOR:													 DATA: __/__/____	*/		
/*           DESCRICAO  :										 								*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	PARA OBTER O NOME DO ARQUIVO DE DADOS E DE LOG DO BANCO DE DADOS ESPECÍFICO		*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	SELECT * 
	FROM SYSFILES  
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	MUDA O BACKUP DO BANCO PARA SIMPLES												*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	ALTER DATABASE JACSYSDB_MGPOLIMG
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_PLASTER
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_PLASTER_MACBOOK
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_POLIRESINAS
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_POLIREXMG
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_POLIREXSP
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_RBAM
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_RBRJDIST
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_RBRJINDU
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_RBSC
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE JACSYSDB_RBSP
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE TESTEMIGRACAO
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE THESYS_DEV
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE THESYS_HOMOLOGACAO
	SET RECOVERY SIMPLE
	GO
	ALTER DATABASE THESYS_PRODUCAO
	SET RECOVERY SIMPLE
	GO
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	TRUNCA OS ARQUIVOS DE LOG DA INSTANCIA											*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	DBCC SHRINKFILE ('JACSYSDB101_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB_PLASTER_MACBOOK_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB3_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB702_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB703_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB5_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB4_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB3_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('JACSYSDB2_Log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('THESYS_log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('THESYS_log', 1,TRUNCATEONLY);				
	GO
	DBCC SHRINKFILE ('THESYS_log', 1,TRUNCATEONLY);	--> Homologacao			
	GO
	DBCC SHRINKFILE ('THESYS_log', 1,TRUNCATEONLY);	--> Producao			
	GO
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	MUDA O BACKUP DO BANCO PARA FULL NOVAMENTE										*/
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	ALTER DATABASE JACSYSDB_MGPOLIMG
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_PLASTER
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_PLASTER_MACBOOK
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_POLIRESINAS
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_POLIREXMG
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_POLIREXSP
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_RBAM
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_RBRJDIST
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_RBRJINDU
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_RBSC
	SET RECOVERY FULL
	GO
	ALTER DATABASE JACSYSDB_RBSP
	SET RECOVERY FULL
	GO
	ALTER DATABASE TESTEMIGRACAO
	SET RECOVERY FULL
	GO
	ALTER DATABASE THESYS_DEV
	SET RECOVERY FULL
	GO
	ALTER DATABASE THESYS_HOMOLOGACAO
	SET RECOVERY FULL
	GO
	ALTER DATABASE THESYS_PRODUCAO
	SET RECOVERY FULL
	GO