


/************ FORMA 1 ****************/

DECLARE @QUERY VARCHAR(MAX) = ''
SELECT
    @QUERY = COALESCE(@QUERY, ',') + 'KILL ' + CONVERT(VARCHAR, SPID) + '; '
FROM
    MASTER..SYSPROCESSES
WHERE
    DBID = DB_ID('TESTES')  -- NOME DO DATABASE
    AND DBID > 4			-- NÃO ELIMINAR SESSÕES EM DATABASES DE SISTEMA
    AND SPID != @@SPID		-- NÃO ELIMINAR A SUA PRÓPRIA SESSÃO


IF (LEN(@QUERY) > 0)
    EXEC(@QUERY)

/************ FORMA 2 ****************/

ALTER DATABASE Testes SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO