
IF OBJECT_ID('TEMPDB.DBO.#ARQUIVO','U') IS NOT NULL
DROP TABLE #ARQUIVO
CREATE TABLE #ARQUIVO (
						ID_ARQUIVO INT NOT NULL IDENTITY PRIMARY KEY,
						NOME_ARQUIVO VARCHAR(MAX) NULL,
					   )


INSERT INTO #ARQUIVO (NOME_ARQUIVO) 
SELECT NAME
FROM CALLTABLES.SYS.TABLES 
WHERE
--------------------- DIGITAL ------------------

   NAME    =   'CT_ANA_ARBITRAL'
OR NAME    =   'CT_ANA_AVON_PREVENTIVO'
OR NAME    =   'CT_ANA_BIGDATA_AUTO_CARREFOUR_G3'
OR NAME    =   'CT_ANA_BIGDATA_CARREFOUR_G3'
OR NAME    =   'CT_ANA_BIGDATA_SMS_CARREFOUR_ATG1'
OR NAME    =   'CT_ANA_BIGDATA_SMS_CARREFOUR_ATG2'
OR NAME    =   'CT_ANA_BIGDATA_SMS_CARREFOUR_G0'
OR NAME    =   'CT_ANA_BIGDATA_SMS_CARREFOUR_G1'
OR NAME    =   'CT_ANA_BIGDATA_SMS_CARREFOUR_G3'
OR NAME    =   'CT_ANA_BIGDATA_SMS_OFFLINE'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_ATACADAO'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_AVON'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_CARREFOUR'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_CB3_RENNER'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_RENNER_ATIVO_PURO_'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_G2_ATACADAO'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_G3_CARREFOUR'
OR NAME    =   'CT_URA_NOVOS_NEGOCIOS_YAMAHA_TELECOBRANCA'
OR NAME    =   'CT_ANA_NOVOS_NEGOCIOS_YAMAHA'

--------------------- HUMANO ---------------------

OR NAME    =   'CT_ATACADAO'
OR NAME    =   'CT_ATACADAO_G1_MANUTENCAO'
OR NAME    =   'CT_ATIVOS_G1'
OR NAME    =   'CT_ATIVOS_G2'
OR NAME    =   'CT_ATIVOS_G2_EXITO'
OR NAME    =   'CT_AVON'
OR NAME    =   'CT_ESTRELA_AVON'
OR NAME    =   'CT_CARREFOUR_MANUTENCAO'
OR NAME    =   'CT_G1_ATACADAO'
OR NAME    =   'CT_G1_CARREFOUR'
OR NAME    =   'CT_G2_CARREFOUR_PERDA'
OR NAME    =   'CT_G3_CARREFOUR_FASE20_'
OR NAME    =   'CT_G3_CARREFOUR_REATIVADA'
OR NAME    =   'CT_MANUTENCAO_ATACADAO'
OR NAME    =   'CT_MANUTENCAO_AVON'
OR NAME    =   'CT_MANUTENCAO_G1'
OR NAME    =   'CT_MANUTENCAO_G3'
OR NAME    =   'CT_PREVENTIVO_AVON'
OR NAME    =   'CT_RENNER_ATIVO'
OR NAME    =   'CT_RENNER_CBR'
OR NAME    =   'CT_RENNER_CCR'
OR NAME    =   'CT_RENNER_MANUTENCAO'
OR NAME    =   'CT_RENNER_PREVENTIVO'
OR NAME    =   'CT_YAMAHA_B'
OR NAME    =   'CT_YAMAHA_TELECOBRANCA'
OR NAME    =   'CT_G0_CARREFOUR'


DECLARE     
             @CONTADOR        AS INT
            , @CONTADOR_FINAL AS INT
			, @NOME           AS VARCHAR(MAX)

            
SET         @CONTADOR					  =     1
SET         @CONTADOR_FINAL         =     (SELECT MAX(ID_ARQUIVO) FROM #ARQUIVO)            
            

WHILE (@CONTADOR  <=    @CONTADOR_FINAL)        
BEGIN 

SET @NOME =(SELECT  NOME_ARQUIVO FROM #ARQUIVO  WHERE ID_ARQUIVO = @CONTADOR ) 

         
EXEC('
DELETE FROM '+@NOME+'
')

SET  @CONTADOR = @CONTADOR + 1

END;


