
IF OBJECT_ID('TEMPDB.DBO.#TB_ARQUIVO', 'U') IS NOT NULL
DROP TABLE #TB_ARQUIVO

CREATE TABLE #TB_ARQUIVO (
							NM_ARQUIVO VARCHAR(MAX)
						)

INSERT INTO  #TB_ARQUIVO
EXEC MASTER..XP_CMDSHELL
			'DIR /B "C:\Avon\URA'


DELETE FROM #TB_ARQUIVO
WHERE (NM_ARQUIVO NOT LIKE '%.txt%'
		OR NM_ARQUIVO IS NULL)



IF OBJECT_ID ('TEMPDB.DBO.#TB_ARQUIVO_DIRETORIO', 'U') IS NOT NULL
DROP	TABLE	#TB_ARQUIVO_DIRETORIO
CREATE	TABLE	#TB_ARQUIVO_DIRETORIO	(	  ID_ARQUIVO	INT	IDENTITY
											, NM_ARQUIVO	VARCHAR(MAX)
										)

INSERT	INTO	#TB_ARQUIVO_DIRETORIO
SELECT
		  NM_ARQUIVO  
FROM	#TB_ARQUIVO	


IF OBJECT_ID ('TEMPDB.DBO.#TB_ARQUIVO_QP', 'U') IS NOT NULL
DROP	TABLE	#TB_ARQUIVO_QP
CREATE	TABLE	#TB_ARQUIVO_QP (
									CPF VARCHAR(MAX),
									CODIGO VARCHAR(MAX),
									TELEFONE VARCHAR(MAX)
							)



DECLARE	  @CONTADOR					INT
		, @CONTADOR_FINAL			INT
		, @ORDEM					BIGINT
		, @NM_ARQUIVO_DIRETORIO		VARCHAR(MAX)

--INICIA A CONTAGEM DOS ARQUIVOS
SET		@CONTADOR					=	1
SET		@CONTADOR_FINAL				=	(SELECT ISNULL(MAX(ID_ARQUIVO),0)	FROM #TB_ARQUIVO_DIRETORIO)


WHILE	(@CONTADOR	<= @CONTADOR_FINAL)			 
BEGIN

SET		@NM_ARQUIVO_DIRETORIO		=	'C:\Avon\URA\' + (SELECT NM_ARQUIVO FROM #TB_ARQUIVO_DIRETORIO WHERE ID_ARQUIVO = @CONTADOR)


IF OBJECT_ID ('TEMPDB.DBO.#TB_TXT', 'U') IS NOT NULL
DROP	TABLE	#TB_TXT
CREATE	TABLE	#TB_TXT	(
									CPF VARCHAR(MAX),
									CODIGO VARCHAR(MAX),
									TELEFONE VARCHAR(MAX)
)
DECLARE @BULK_CMD VARCHAR(1000)
SET 
 @BULK_CMD='
BULK	INSERT		#TB_TXT
FROM	"' + @NM_ARQUIVO_DIRETORIO + '"
WITH (	CODEPAGE=''RAW'',
		FIRSTROW=2,
		FIELDTERMINATOR = '';'',
		ROWTERMINATOR = '''+CHAR(10)+''')'

EXEC (@BULK_CMD);


INSERT	INTO #TB_ARQUIVO_QP
SELECT *
FROM	#TB_TXT
SET		@CONTADOR = @CONTADOR + 1 
END 


DELETE FROM   [172.20.1.66].[DB_DAILY].[DBO].[TB_AVON_REMESSA_TELEFONES] 
