USE BD_MIS
GO

SELECT ID_CLIENTE
       ,NU_CPF_CNPJ
	    ,NM_NOME
		 ,ATRASO
		  ,SALDO_DEVEDOR
		   ,DT_ULT_ACAO
		    ,DT_ULT_ACORDO_ATIVO
			 ,DT_PROX_PARCELA
			  ,VL_ACORDO
			   ,VL_PARCELA
			    ,VL_PAGO
				 ,VL_RESTANTE_ACORDO
				  ,DATEDIFF(DD,CONVERT(DATE ,DT_PROX_PARCELA,103),CAST(GETDATE() AS date)) AS DIAS_PARA_VENCIMENTO
				   ,DATEDIFF(DD,CONVERT(DATE ,DT_ULT_ACAO,103)
					,CAST(GETDATE() AS date) ) AS DIAS_SEM_ACIONAMENTO
FROM SCC_WEDOO WITH(NOLOCK)
WHERE DATEDIFF(DD,CONVERT(DATE ,DT_PROX_PARCELA,103),CAST(GETDATE() AS date)) BETWEEN -3 AND 2
AND (DATEDIFF(DD,CONVERT(DATE ,DT_ULT_ACAO,103) ,CAST(GETDATE() AS date)) > 5  
OR DT_ULT_ACAO IS NULL)
AND ID_CEDENTE = 1