

USE DB_REPORT
GO


SELECT 
		NM_CEDENTE
,		EC				=	TB1.ID_CLIENTE
,		CPF_OU_CNPJ		=   TB2.NU_CPF_CNPJ
,		TB1.DATA
,		HORA
,		NM_ACAO
,		CPCA
FROM TB_REL_HORA_HORA_TABULACAO_ANALITICO TB1 WITH(NOLOCK)
LEFT JOIN
	[172.20.1.65].[EASYCOLLECTOR].[DBO].[TB_CLIENTE] TB2
ON (TB1.ID_CLIENTE	=	TB2.ID_CLIENTE)
WHERE TB1.ID_CEDENTE = 47
AND HORA BETWEEN 8 AND 14
AND CPCA = 1
AND NM_ACAO <> 'Acordo Formalizado'
AND GRUPO1 IN ('CEF L2', 'CEF L2')
ORDER BY HORA DESC



--- EC, DATA E HORA E CPC