USE	DB_DAILY
GO


SELECT 
		  DATA
		, MAILING = (
					SELECT 
							MAX(MAILING)
					FROM	[DB_DAILY].[DBO].[TB_AVON_DAILY_SINTETIZADO_PRINCIPAL]	DS	WITH(NOLOCK)
					WHERE
							TA.DATA = DS.DT_REF
					)
							
		, ALO		=	SUM(CE)
		, CPC		=	SUM(CPCA)
		, PROMESSA	=	SUM(AF)
		, PA_CONTRATADA = 23
FROM	[DB_REPORT].[DBO].[TB_REL_HORA_HORA_TABULACAO_ANALITICO_BACKUP] TA
WHERE
		DATA	BETWEEN '2020-11-01' AND '2020-11-30'
	AND ID_CEDENTE		=	1
GROUP	BY
		DATA
ORDER	BY
		DATA
