SELECT 	 DATE_FORMAT(DATA,'%Y-%m') AS DATA
			,OD.DOSSIE
			,OD.CAMPANHA
			,RTRIM(LTRIM(VXS.STATUS))
FROM		 TEMP_ODOO OD
INNER
JOIN		 ft_telefones FT
ON			 LEFT(OD.TEL_CONTATO,2)*1
=			 FT.DDD
AND		 RIGHT(OD.TEL_CONTATO,LENGTH(OD.TEL_CONTATO)-2)*1
=			 FT.TELEFONE
INNER
JOIN		 vx_ft_discagens VXD
ON			 VXD.ID_TELEFONE
=			 FT.ID
INNER
JOIN		 vx_dm_status VXS
ON			 VXD.ID_STATUS 
=			 VXS.ID
WHERE		 DATE_FORMAT(DATA,'%Y-%m-%d')
>=	 		 '2021-03-01'
AND		 OD.`GROUP`
=			 'ITAÚ' 
AND OD.DOSSIE = '070200759366.3'