
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* PROGRAMADOR: KAIKE NATAN E THALES                                                                                  */
/* VERSAO     : 1.0      																									DATA: 08/11/2021   */
/* DESCRICAO  : RESPONSAVEL POR FAZER A CONSULTA DE TABULAÇÃO 																	 		 */	   																										   						
/* ALTERACAO                                                                                                          */
/*        2. PROGRAMADOR: 																									DATA: __/__/____	 */
/*           DESCRICAO  : 								 																							 */                                                                                                                                         
/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	FAZ A TEMPÓRARIA ATRAVÉS DA PRE_CALL					    			*/
/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
DROP TABLE IF EXISTS TEMP_ANALITICO_PRE_CALL; 
CREATE TEMPORARY TABLE TEMP_ANALITICO_PRE_CALL AS

SELECT 
			CAL.*
,			ACI.name AS Tabulacao		
FROM 
		mmp_pre_call CAL
LEFT JOIN 	
		mmp_pre_acionamento ACI

ON		CAL.acionamento_id	 = 	ACI.id
WHERE 
		CAST(CAL.create_date AS DATE) >= CURRENT_DATE - 30 

/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
/* DESCRICAO  :	MODELAGEM DOS DADOS ATRAVÉS DA REGRA DE NEGÓCIO		   			*/
/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/

SELECT 
 ID 								AS ID
,CAST(CREATE_DATE AS DATE) AS "DATA"
,QUEUE_ID						AS GRUPO
,TABULACAO
,						
CASE WHEN tabulacao = '(Planos) Caso já habilitado no site' THEN '0'
WHEN tabulacao = '(Planos) Sem Interesse - Forma de Pagamento' THEN '1'
WHEN tabulacao = '(Planos) Sem Interesse - Valor Baixo' THEN '1'
WHEN tabulacao = '(Reperformance) Contraproposta Inviável - Definitivo' THEN '1'
WHEN tabulacao = '(Reperformance) Não quer fazer acordo - Definitivo' THEN '1'
WHEN tabulacao = 'AÇÃO JURÍDICA' THEN '0'
WHEN tabulacao = 'Acordo Fechado - Dentro da Alçada' THEN '1'
WHEN tabulacao = 'Acordo Fechado - Fora da Alçada' THEN '1'
WHEN tabulacao = 'Acordo Realizado em Outro Escritório' THEN '1'
WHEN tabulacao = 'Adv sem Contato com o Cliente' THEN '1'
WHEN tabulacao = 'Advogado informa conta nova ou saldo divergente' THEN '1'
WHEN tabulacao = 'Aguardando documentação' THEN '1'
WHEN tabulacao = 'AGUARDANDO RETORNO' THEN '1'
WHEN tabulacao = 'ALEGA PAGTO. AGENDA ' THEN '1'
WHEN tabulacao = 'ALEGA PAGTO. BOLETO' THEN '1'
WHEN tabulacao = 'ALEGA PAGTO. C/C' THEN '1'
WHEN tabulacao = 'ATIVAS - OPERAÇÃO LIQUIDADA' THEN '0'
WHEN tabulacao = 'Ativas - Sem Condições de Pagamento' THEN '1'
WHEN tabulacao = 'Ativas - Verificar Condição Processual' THEN '1'
WHEN tabulacao = 'CLIENTE DESLIGOU / LIGAÇÃO PERDIDA' THEN '1'
WHEN tabulacao = 'CLIENTE ENVIARÁ MINUTA ASSINADA' THEN '1'
WHEN tabulacao = 'COMERCIAL - LIGAR' THEN '1'
WHEN tabulacao = 'Completar dados processuais' THEN '1'
WHEN tabulacao = 'Confirma presença no evento' THEN '1'
WHEN tabulacao = 'confirmou presença' THEN '1'
WHEN tabulacao = 'Confirmou presença' THEN '1'
WHEN tabulacao = 'Contato com o Gerente' THEN '1'
WHEN tabulacao = 'Dados do processo corrigidos' THEN '1'
WHEN tabulacao = 'Deixei Recado' THEN '1'
WHEN tabulacao = 'DEIXEI RECADO' THEN '1'
WHEN tabulacao = 'DESCONHECE EMPRÉSTIMO' THEN '1'
WHEN tabulacao = 'DESCONHECIDO NO TELEFONE' THEN '1'
WHEN tabulacao = 'Desconhecido no Telefone' THEN '1'
WHEN tabulacao = 'Dossiê Validado' THEN '1'
WHEN tabulacao = 'Duvidas Processuais' THEN '1'
WHEN tabulacao = 'Dúvidas sobre minuta' THEN '1'
WHEN tabulacao = 'Duvidas sobre pagamento' THEN '1'
WHEN tabulacao = 'ENVIADA' THEN '1'
WHEN tabulacao = 'Enviar Proposta por Email' THEN '1'
WHEN tabulacao = 'Enviar Proposta por WhatsApp' THEN '1'
WHEN tabulacao = 'ENVIO DE BOLETO' THEN '1'
WHEN tabulacao = 'FALECIDO' THEN '1'
WHEN tabulacao = 'Mensagem de operadora' THEN '0'
WHEN tabulacao = 'MINUTA ENVIADA - NOVA PROPOSTA' THEN '1'
WHEN tabulacao = 'MUDOU-SE' THEN '1'
WHEN tabulacao = 'Não Atende' THEN '0'
WHEN tabulacao = 'NÃO ATENDE' THEN '0'
WHEN tabulacao = 'Não confirma presença' THEN '0'
WHEN tabulacao = 'Não Conhece o Processo' THEN '1'
WHEN tabulacao = 'NÃO EXISTE' THEN '0'
WHEN tabulacao = 'Não Existe' THEN '0'
WHEN tabulacao = 'Não Quer Fazer Acordo' THEN '1'
WHEN tabulacao = 'Não Quer Fazer Acordo - HONORÁRIOS FEBRAPO' THEN '1'
WHEN tabulacao = 'NOVA PROMESSA DE PGTO / BOLETO PARCIAL' THEN '1'
WHEN tabulacao = 'NOVA PROMESSA DE PGTO / QUITAÇÃO' THEN '1'
WHEN tabulacao = 'OCUPADO' THEN '0'
WHEN tabulacao = 'Pesquisa de Validação Concluída' THEN '1'
WHEN tabulacao = 'Possível fraude' THEN '1'
WHEN tabulacao = 'PROMESSA DE PGTO / BOLETO PARCIAL' THEN '1'
WHEN tabulacao = 'PROMESSA DE PGTO / QUITAÇÃO' THEN '1'
WHEN tabulacao = 'Proposta Enviada' THEN '1'
WHEN tabulacao = 'Proposta Enviada ao Cliente' THEN '1'
WHEN tabulacao = 'REALIZARÁ PAGAMENTO' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Dentro Da Alçada' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Em Outro Escritório' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Fora Da Alçada' THEN '1'
WHEN tabulacao = 'Rec - Dúvidas Processuais ' THEN '1'
WHEN tabulacao = 'Rec - Honorários' THEN '1'
WHEN tabulacao = 'Rec - Minutas' THEN '1'
WHEN tabulacao = 'Rec - Outras Informações' THEN '1'
WHEN tabulacao = 'Rec - Pagamentos' THEN '1'
WHEN tabulacao = 'Rec - Processo Não Localizado ' THEN '1'
WHEN tabulacao = 'SEM CONDIÇÕES NO MOMENTO' THEN '1'
WHEN tabulacao = 'SEM INTERESSE' THEN '1'
WHEN tabulacao = 'SOLICITA DESCONTO' THEN '1'
WHEN tabulacao = 'SOLICITA RENEGOCIAÇÃO' THEN '1'
WHEN tabulacao = 'Solicitou Retorno' THEN '1'
WHEN tabulacao = 'TELEFONE MUDO' THEN '0'
WHEN tabulacao = 'Última tentativa infrutífera' THEN '0'
WHEN tabulacao = 'URA - Desligou antes de responder a proposta' THEN '1'
ELSE '0' 
END AS "CE",
CASE WHEN tabulacao = '(Planos) Caso já habilitado no site' THEN '0'
WHEN tabulacao = '(Planos) Sem Interesse - Forma de Pagamento' THEN '1'
WHEN tabulacao = '(Planos) Sem Interesse - Valor Baixo' THEN '1'
WHEN tabulacao = '(Reperformance) Contraproposta Inviável - Definitivo' THEN '1'
WHEN tabulacao = '(Reperformance) Não quer fazer acordo - Definitivo' THEN '1'
WHEN tabulacao = 'AÇÃO JURÍDICA' THEN '0'
WHEN tabulacao = 'Acordo Fechado - Dentro da Alçada' THEN '1'
WHEN tabulacao = 'Acordo Fechado - Fora da Alçada' THEN '1'
WHEN tabulacao = 'Acordo Realizado em Outro Escritório' THEN '1'
WHEN tabulacao = 'Adv sem Contato com o Cliente' THEN '0'
WHEN tabulacao = 'Advogado informa conta nova ou saldo divergente' THEN '0'
WHEN tabulacao = 'Aguardando documentação' THEN '1'
WHEN tabulacao = 'AGUARDANDO RETORNO' THEN '0'
WHEN tabulacao = 'ALEGA PAGTO. AGENDA ' THEN '1'
WHEN tabulacao = 'ALEGA PAGTO. BOLETO' THEN '1'
WHEN tabulacao = 'ALEGA PAGTO. C/C' THEN '1'
WHEN tabulacao = 'ATIVAS - OPERAÇÃO LIQUIDADA' THEN '0'
WHEN tabulacao = 'Ativas - Sem Condições de Pagamento' THEN '1'
WHEN tabulacao = 'Ativas - Verificar Condição Processual' THEN '1'
WHEN tabulacao = 'CLIENTE DESLIGOU / LIGAÇÃO PERDIDA' THEN '0'
WHEN tabulacao = 'CLIENTE ENVIARÁ MINUTA ASSINADA' THEN '1'
WHEN tabulacao = 'COMERCIAL - LIGAR' THEN '1'
WHEN tabulacao = 'Completar dados processuais' THEN '1'
WHEN tabulacao = 'Confirma presença no evento' THEN '1'
WHEN tabulacao = 'confirmou presença' THEN '1'
WHEN tabulacao = 'Confirmou presença' THEN '1'
WHEN tabulacao = 'Contato com o Gerente' THEN '0'
WHEN tabulacao = 'Dados do processo corrigidos' THEN '1'
WHEN tabulacao = 'Deixei Recado' THEN '0'
WHEN tabulacao = 'DEIXEI RECADO' THEN '0'
WHEN tabulacao = 'DESCONHECE EMPRÉSTIMO' THEN '0'
WHEN tabulacao = 'DESCONHECIDO NO TELEFONE' THEN '0'
WHEN tabulacao = 'Desconhecido no Telefone' THEN '0'
WHEN tabulacao = 'Dossiê Validado' THEN '1'
WHEN tabulacao = 'Duvidas Processuais' THEN '1'
WHEN tabulacao = 'Dúvidas sobre minuta' THEN '1'
WHEN tabulacao = 'Duvidas sobre pagamento' THEN '1'
WHEN tabulacao = 'ENVIADA' THEN '1'
WHEN tabulacao = 'Enviar Proposta por Email' THEN '1'
WHEN tabulacao = 'Enviar Proposta por WhatsApp' THEN '1'
WHEN tabulacao = 'ENVIO DE BOLETO' THEN '1'
WHEN tabulacao = 'FALECIDO' THEN '0'
WHEN tabulacao = 'Mensagem de operadora' THEN '0'
WHEN tabulacao = 'MINUTA ENVIADA - NOVA PROPOSTA' THEN '1'
WHEN tabulacao = 'MUDOU-SE' THEN '0'
WHEN tabulacao = 'Não Atende' THEN '0'
WHEN tabulacao = 'NÃO ATENDE' THEN '0'
WHEN tabulacao = 'Não confirma presença' THEN '0'
WHEN tabulacao = 'Não Conhece o Processo' THEN '0'
WHEN tabulacao = 'NÃO EXISTE' THEN '0'
WHEN tabulacao = 'Não Existe' THEN '0'
WHEN tabulacao = 'Não Quer Fazer Acordo' THEN '1'
WHEN tabulacao = 'Não Quer Fazer Acordo - HONORÁRIOS FEBRAPO' THEN '1'
WHEN tabulacao = 'NOVA PROMESSA DE PGTO / BOLETO PARCIAL' THEN '1'
WHEN tabulacao = 'NOVA PROMESSA DE PGTO / QUITAÇÃO' THEN '1'
WHEN tabulacao = 'OCUPADO' THEN '0'
WHEN tabulacao = 'Pesquisa de Validação Concluída' THEN '0'
WHEN tabulacao = 'Possível fraude' THEN '1'
WHEN tabulacao = 'PROMESSA DE PGTO / BOLETO PARCIAL' THEN '1'
WHEN tabulacao = 'PROMESSA DE PGTO / QUITAÇÃO' THEN '1'
WHEN tabulacao = 'Proposta Enviada' THEN '1'
WHEN tabulacao = 'Proposta Enviada ao Cliente' THEN '1'
WHEN tabulacao = 'REALIZARÁ PAGAMENTO' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Dentro Da Alçada' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Em Outro Escritório' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Fora Da Alçada' THEN '1'
WHEN tabulacao = 'Rec - Dúvidas Processuais ' THEN '1'
WHEN tabulacao = 'Rec - Honorários' THEN '1'
WHEN tabulacao = 'Rec - Minutas' THEN '1'
WHEN tabulacao = 'Rec - Outras Informações' THEN '1'
WHEN tabulacao = 'Rec - Pagamentos' THEN '1'
WHEN tabulacao = 'Rec - Processo Não Localizado ' THEN '1'
WHEN tabulacao = 'SEM CONDIÇÕES NO MOMENTO' THEN '1'
WHEN tabulacao = 'SEM INTERESSE' THEN '1'
WHEN tabulacao = 'SOLICITA DESCONTO' THEN '1'
WHEN tabulacao = 'SOLICITA RENEGOCIAÇÃO' THEN '1'
WHEN tabulacao = 'Solicitou Retorno' THEN '1'
WHEN tabulacao = 'TELEFONE MUDO' THEN '0'
WHEN tabulacao = 'Última tentativa infrutífera' THEN '0'
WHEN tabulacao = 'URA - Desligou antes de responder a proposta' THEN '0'
ELSE '0' 
END AS "CPC",
CASE WHEN tabulacao = '(Planos) Caso já habilitado no site' THEN '0'
WHEN tabulacao = '(Planos) Sem Interesse - Forma de Pagamento' THEN '0'
WHEN tabulacao = '(Planos) Sem Interesse - Valor Baixo' THEN '0'
WHEN tabulacao = '(Reperformance) Contraproposta Inviável - Definitivo' THEN '0'
WHEN tabulacao = '(Reperformance) Não quer fazer acordo - Definitivo' THEN '0'
WHEN tabulacao = 'AÇÃO JURÍDICA' THEN '0'
WHEN tabulacao = 'Acordo Fechado - Dentro da Alçada' THEN '1'
WHEN tabulacao = 'Acordo Fechado - Fora da Alçada' THEN '1'
WHEN tabulacao = 'Acordo Realizado em Outro Escritório' THEN '1'
WHEN tabulacao = 'Adv sem Contato com o Cliente' THEN '0'
WHEN tabulacao = 'Advogado informa conta nova ou saldo divergente' THEN '0'
WHEN tabulacao = 'Aguardando documentação' THEN '0'
WHEN tabulacao = 'AGUARDANDO RETORNO' THEN '0'
WHEN tabulacao = 'ALEGA PAGTO. AGENDA ' THEN '1'
WHEN tabulacao = 'ALEGA PAGTO. BOLETO' THEN '1'
WHEN tabulacao = 'ALEGA PAGTO. C/C' THEN '1'
WHEN tabulacao = 'ATIVAS - OPERAÇÃO LIQUIDADA' THEN '1'
WHEN tabulacao = 'Ativas - Sem Condições de Pagamento' THEN '0'
WHEN tabulacao = 'Ativas - Verificar Condição Processual' THEN '0'
WHEN tabulacao = 'CLIENTE DESLIGOU / LIGAÇÃO PERDIDA' THEN '0'
WHEN tabulacao = 'CLIENTE ENVIARÁ MINUTA ASSINADA' THEN '1'
WHEN tabulacao = 'COMERCIAL - LIGAR' THEN '0'
WHEN tabulacao = 'Completar dados processuais' THEN '0'
WHEN tabulacao = 'Confirma presença no evento' THEN '0'
WHEN tabulacao = 'confirmou presença' THEN '0'
WHEN tabulacao = 'Confirmou presença' THEN '0'
WHEN tabulacao = 'Contato com o Gerente' THEN '0'
WHEN tabulacao = 'Dados do processo corrigidos' THEN '0'
WHEN tabulacao = 'Deixei Recado' THEN '0'
WHEN tabulacao = 'DEIXEI RECADO' THEN '0'
WHEN tabulacao = 'DESCONHECE EMPRÉSTIMO' THEN '0'
WHEN tabulacao = 'DESCONHECIDO NO TELEFONE' THEN '0'
WHEN tabulacao = 'Desconhecido no Telefone' THEN '0'
WHEN tabulacao = 'Dossiê Validado' THEN '0'
WHEN tabulacao = 'Duvidas Processuais' THEN '0'
WHEN tabulacao = 'Dúvidas sobre minuta' THEN '0'
WHEN tabulacao = 'Duvidas sobre pagamento' THEN '0'
WHEN tabulacao = 'ENVIADA' THEN '0'
WHEN tabulacao = 'Enviar Proposta por Email' THEN '0'
WHEN tabulacao = 'Enviar Proposta por WhatsApp' THEN '0'
WHEN tabulacao = 'ENVIO DE BOLETO' THEN '0'
WHEN tabulacao = 'FALECIDO' THEN '0'
WHEN tabulacao = 'Mensagem de operadora' THEN '0'
WHEN tabulacao = 'MINUTA ENVIADA - NOVA PROPOSTA' THEN '0'
WHEN tabulacao = 'MUDOU-SE' THEN '0'
WHEN tabulacao = 'Não Atende' THEN '0'
WHEN tabulacao = 'NÃO ATENDE' THEN '0'
WHEN tabulacao = 'Não confirma presença' THEN '0'
WHEN tabulacao = 'Não Conhece o Processo' THEN '0'
WHEN tabulacao = 'NÃO EXISTE' THEN '0'
WHEN tabulacao = 'Não Existe' THEN '0'
WHEN tabulacao = 'Não Quer Fazer Acordo' THEN '0'
WHEN tabulacao = 'Não Quer Fazer Acordo - HONORÁRIOS FEBRAPO' THEN '0'
WHEN tabulacao = 'NOVA PROMESSA DE PGTO / BOLETO PARCIAL' THEN '1'
WHEN tabulacao = 'NOVA PROMESSA DE PGTO / QUITAÇÃO' THEN '1'
WHEN tabulacao = 'OCUPADO' THEN '0'
WHEN tabulacao = 'Pesquisa de Validação Concluída' THEN '0'
WHEN tabulacao = 'Possível fraude' THEN '0'
WHEN tabulacao = 'PROMESSA DE PGTO / BOLETO PARCIAL' THEN '1'
WHEN tabulacao = 'PROMESSA DE PGTO / QUITAÇÃO' THEN '1'
WHEN tabulacao = 'Proposta Enviada' THEN '0'
WHEN tabulacao = 'Proposta Enviada ao Cliente' THEN '0'
WHEN tabulacao = 'REALIZARÁ PAGAMENTO' THEN '0'
WHEN tabulacao = 'Rec - Acordo Fechado Dentro Da Alçada' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Em Outro Escritório' THEN '1'
WHEN tabulacao = 'Rec - Acordo Fechado Fora Da Alçada' THEN '1'
WHEN tabulacao = 'Rec - Dúvidas Processuais ' THEN '0'
WHEN tabulacao = 'Rec - Honorários' THEN '0'
WHEN tabulacao = 'Rec - Minutas' THEN '0'
WHEN tabulacao = 'Rec - Outras Informações' THEN '0'
WHEN tabulacao = 'Rec - Pagamentos' THEN '1'
WHEN tabulacao = 'Rec - Processo Não Localizado ' THEN '0'
WHEN tabulacao = 'SEM CONDIÇÕES NO MOMENTO' THEN '0'
WHEN tabulacao = 'SEM INTERESSE' THEN '0'
WHEN tabulacao = 'SOLICITA DESCONTO' THEN '0'
WHEN tabulacao = 'SOLICITA RENEGOCIAÇÃO' THEN '0'
WHEN tabulacao = 'Solicitou Retorno' THEN '0'
WHEN tabulacao = 'TELEFONE MUDO' THEN '0'
WHEN tabulacao = 'Última tentativa infrutífera' THEN '0'
WHEN tabulacao = 'URA - Desligou antes de responder a proposta' THEN '0'
else '0'
end AS "PROM"

FROM 	
		TEMP_ANALITICO_PRE_CALL	
		
		