USE [THESYS_DEV]
GO

INSERT INTO THESYS_PRODUCAO..[Natureza_Operacao_Tipos]
           ([cod_tiponatureza]
           ,[descricao_tiponatureza]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device])
select 
			[cod_tiponatureza]
           ,[descricao_tiponatureza]
           ,[incl_data]
           ,[incl_user]
           ,[incl_device]
           ,[modi_data]
           ,[modi_user]
           ,[modi_device]
           ,[excl_data]
           ,[excl_user]
           ,[excl_device]
from [Natureza_Operacao_Tipos]